### ISSUE TITLE
add 2 terms for IEDB & DO

### ISSUE THREAD

**Issue by rvita** [oborel/obo-relations#105]
Hi, we would like to request 2 new terms to be used by the IEDB DO:
'has allergic trigger' is a relationship between a disease (domain) and material entity (range) where the realization of the disease results in pathological processes that includes an abnormally strong
immune response against the material entity which is not part of the host and is considered harmless to non allergic individuals.
Example: drug allergy (DOID_0060500) has_allergic_trigger some drug (CHEBI:23888).

'has autoimmune trigger' is a relationship between a disease (domain) and material entity (range) where the realization of the disease results in pathological processes that includes an immune response against the material entity, which is part of the host itself.

unsure of the parent terms b/c the RO_0002600 'capable of upregulating or causing pathological process' term causes a process, but a disease is a disposition.

**Comment by elviram** [comment]
Hello,
any news regarding those two relations?

Thank you.

**Comment by cmungall** [comment]
I'll take a look monday

**Comment by jamesaoverton** [comment]
@cmungall I have a couple of changes to check with Bjoern and Randi, then I'll update the ticket.

**Comment by jamesaoverton** [comment]
We want to use 'causes or contributes to condition' (http://purl.obolibrary.org/obo/RO_0003302) as the parent. So we'll swap the domain and range and adjust the definitions to better match that parent.

@cmungall Does this work for you? I can make the edits.

label: is allergic trigger for
parent: causes or contributes to condition
domain: material entity
definition: A relationship between a material entity and a condition (a phenotype or disease) of a host, in which the material entity is not part of the host, and is considered harmless to non-allergic hosts, and the condition results in pathological processes that include an abnormally strong immune response against the material entity.

label: is autoimmune trigger for
parent: causes or contributes to condition
domain: material entity
definition: A relationship between a material entity and a condition (a phenotype or disease) of a host, in which the material entity is part of the host itself, and the condition results in pathological processes that include an abnormally strong immune response against the material entity.

**Comment by jamesaoverton** [comment]
@cmungall Are these OK with you? I can make the edits.

**Comment by cmungall** [comment]
Yes these are fine. Note these don't represent the only way of modeling these; e.g. following a LEGO paradigm we would model this as the material entity being the substrate for some (possibly untyped) molecular event, with this having a causal relation to some downstream process, e.g. immune process

**Comment by cmungall** [comment]
Aside regarding your drug example:

  * CHEBI:23888 is a role, not a material entity, so this would yield an 
unsatisfiable class
  * CHEBI seems a bit fuzzy as to what a drug actually is. DO has 
'beta-lactam allergy' as a subclass of drug allergy, but CHEBI doesn't 
classify beta-lactam as a drug

**Comment by bpeters42** [comment]
Regarding the example: It should be updated to: 
(material entity and 'has role' some drug (CHEBI:23888)) is_allergic_trigger_of some drug allergy (DOID_0060500)
beta-lactams like penicillin exists in nature. and not all beta lactams are drugs, so I think it would be accurate to not assign it the drug role at the class level. At the same time, , I am not sure this degree of thought went into that assignment given that Chebi roles are in general not highly consistent. 

Great that you are okay with modeling it as a link between material and process. In all of allergy and auto-immunity, it is very unclear what the original molecular event that leads to sensitization, so I would prefer to keep it as is. 

- Bjoern

**Comment by jamesaoverton** [comment]
I prefer example to be in English rather than Manchester syntax, so I changed the example to: "penicillin (CHEBI:17334) is allergic trigger for penicillin allergy (DOID:0060520)".

**Comment by jamesaoverton** [comment]
Chris committed my changes earlier today #109. Thanks! These are the new IRIs:

http://purl.obolibrary.org/obo/RO_0001020 is allergic trigger for
http://purl.obolibrary.org/obo/RO_0001021 is autoimmune trigger for

They'll be included in future builds/releases of RO. We can start using the relations now.
