### ISSUE TITLE
include interaction terms suggested by Khabibullin 2016

### ISSUE THREAD

**Issue by jhpoelen** [oborel/obo-relations#110]
Khabibullin 2016 proposes a way to classify interactions based on living in / foraging in partners environment (e.g. living in (internal | surface | proximate external | distant external) and foraging in (internal | surface | proximate external | distant external ). At first glance, this might provide a secondary way to decontruct/define interaction terms like an endoparasite (e.g. living internal and foraging internally) and make it easier to search (e.g. list organisms that are known to live in a human body).

Khabibullin, V.F., 2016. Location and foraging as basis for classification of biotic interactions. Theory in Biosciences. Available at: http://dx.doi.org/10.1007/s12064-016-0228-8.

**Comment by nlharris** [comment]
Should this be discussed?

**Comment by jhpoelen** [comment]
I think the publication by Khabibullin 2016 is worth taking into account for classifying interactions, but, in hindsight, is perhaps a little too broad in scope to be discussed here. Thanks for following up.
