### ISSUE TITLE
in/decreased risk of condition

### ISSUE THREAD

**Issue by nlwashington** [oborel/obo-relations#117]
If I want to specify a link between a variant and it's association with an increased or decreased risk for a condition, the term "contributes to frequency of condition" [RO:0003306](http://purl.obolibrary.org/obo/RO_0003306) somewhat satisfies this, but not fully because it doesn't indicate the directionality of the contribution.  

Is is appropriate to add directionality into the ontology here, so that there are two sub-properties:
- contributes to increased frequency of condition
- contributes to decreased frequency of condition

Otherwise, should there be a different property for "risk"?  Because it's more about the likelihood of the condition in an individual, rather than at the population level (the above term is at the population level).

Or would "contributes to severity of condition" satisfy the individual-level here?  (My feeling is it isn't sufficient to express the meaning.)

**Comment by nlharris** [comment]
Nicole is long gone and this question was asked almost 6 years ago. Closing; reopen if needed.
