### ISSUE TITLE
NR: removes input for

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#120]
counterpart for provides input for. Document TBA

**Comment by dosumis** [comment]
CC @ukemi

**Comment by vanaukenk** [comment]
@cmungall   Following up on this ticket after the docathon.

We discussed again the need for 'removes input for' relations wrt a model involving serotonin catabolism:

http://noctua.berkeleybop.org/editor/graph/gomodel:59dc728000000287

Can you please add the following new relations to RO?

causally upstream of (RO:0002411)
-transitively removes input for (RO:new)
--directly removes input for (RO:new)
		
Possible definitions:

directly removes input for:
p1 directly removes input for p2 iff there exists some c such that p1 has_input c that, in turn, prevents the realization of p2 by altering the identity, or localization, of c

The current definition of 'transitively provides input for' is:
transitive form of directly_provides_input_for

so, by analogy, the definition of 'transitively removes input for' would be:
transitive form of directly_removes_input_for

Do the transitive relations need to be defined more specifically?

Also note that there is a comment associated with 'transitively provides input for':

'This is a grouping relation that should probably not be used in annotation. Consider instead the child relation 'directly provides input for' (which may later be relabeled simply to 'provides input for').'

What are your current thoughts on relabeling the 'directly provides/removes input for' relations?

Thx.

**Comment by nlharris** [comment]
@vanaukenk is this still needed?

**Comment by vanaukenk** [comment]
@nlharris - I'm not sure if we still need/want this relation for GO-CAMs.
Since this ticket is fairly old, I think we could go ahead and close it and reopen it later if needed.

**Comment by nlharris** [comment]
Thanks, closing!
