### ISSUE TITLE
'transformation of' is unsatisfiable

### ISSUE THREAD

**Issue by balhoff** [oborel/obo-relations#126]
RO:0002494 (transformation of) is inferred to have domain and range both equal to (occurrent and 'independent continuant'). Thus when there is a disjointness axiom between occurrent and continuant, the inferred domain and range are both owl:Nothing.

This is because it is a subproperty of both 'preceded by' (occurrent -> occurrent) and 'develops from' ('independent continuant' -> 'independent continuant'). It's been this way back to at least summer 2015.

I am not able to classify RO with HermiT in a reasonable amount of time, but Fact++ is able to infer this quickly.

Related question, should http://purl.obolibrary.org/obo/ro/bfo-classes-minimal.owl contain some disjointness axioms? There are none at the moment.

**Comment by cmungall** [comment]
you're quite right, this is not so good!

So we miss this for a few reasons, all of which are deficiencies that should be fixed:

 - we want the disjointness axioms, obviously (I thought we had them...)
 - even if present, we test for coherency and consistency using hermit, but not this. We can add a test to robot, e.g. D/R SubPropertyOf nothing. Is there a name for this? unsatisfiable object property?

The fact that we don't do any OP hierarchy tests as part of robot/owltools probably explains why we didn't notice hermit was so slow (it's superfast just to test coherency on RO!)

**Comment by balhoff** [comment]
FYI, same problem for its subproperty 'immediate transformation of'.

**Comment by cmungall** [comment]
FYI this was fixed here:

https://github.com/oborel/obo-relations/releases/tag/v2016-10-28

The requirement for an RBox check was brought up here: https://github.com/ontodev/robot/issues/104

And is implemented in Robot

In theory we should never see issues like this in the release file again
