### ISSUE TITLE
'existence starts at point' and 'existence ends at point' are unsatisfiable

### ISSUE THREAD

**Issue by balhoff** [oborel/obo-relations#128]
Both of these are in property chains like:
```
'existence ends at point' o inverse('existence ends at point') SubPropertyOf 'existence ends with'
```

 This makes the subject's existence end with itself, so the subject is both a continuant and an occurrent.

**Comment by cmungall** [comment]
huh, I'm not seeing that property chain in either ro-edit, or in the release http://purl.obolibrary.org/obo/RO_0002583

(but this kind of axiom looks familiar, the intent is to bridge point and relation algebra...)

**Comment by balhoff** [comment]
In Protege you see it when viewing 'existence starts with' or 'existence ends with'. In Ontobee: http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/RO_0002489

But Ontobee doesn't seem to display inverse property expressions correctly.
