### ISSUE TITLE
Illegal redeclarations of entities: reuse of entity ... in punning not allowed

### ISSUE THREAD

**Issue by donpellegrino** [oborel/obo-relations#130]
When making use of RO in Stanford Protege Desktop v5.1.0, a number of errors are reported to the log with the pattern "Illegal redeclarations of entities: reuse of entity ... in punning not allowed"

Level:       INFO
Time:        1477573771688
Message:     Finished loading imported ontology at http://purl.obolibrary.org/obo/ro/el-constraints.owl

Level:       ERROR
Time:        1477573771785
Message:     Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/BFO_0000063 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/BFO_0000063>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/BFO_0000063>))]

Level:       ERROR
Time:        1477573771786
Message:     Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/RO_0002222 in punning not allowed [Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002222>)), Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002222>))]

Level:       INFO
Time:        1477573771787
Message:     Finished loading imported ontology at http://purl.obolibrary.org/obo/ro.owl

Level:       ERROR
Time:        1477573771826
Message:     Illegal redeclarations of entities: reuse of entity http://www.w3.org/2004/02/skos/core#prefLabel in punning not allowed [Declaration(AnnotationProperty(<http://www.w3.org/2004/02/skos/core#prefLabel>)), Declaration(DataProperty(<http://www.w3.org/2004/02/skos/core#prefLabel>))]

Level:       ERROR
Time:        1477573771827
Message:     Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/BFO_0000063 in punning not allowed [Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/BFO_0000063>)), Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/BFO_0000063>))]

Level:       ERROR
Time:        1477573771827
Message:     Illegal redeclarations of entities: reuse of entity http://purl.obolibrary.org/obo/RO_0002222 in punning not allowed [Declaration(AnnotationProperty(<http://purl.obolibrary.org/obo/RO_0002222>)), Declaration(ObjectProperty(<http://purl.obolibrary.org/obo/RO_0002222>))]

**Comment by balhoff** [comment]
@donpellegrino I corrected RO_0002222 and BFO_0000063, but I don't see http://www.w3.org/2004/02/skos/core#prefLabel in RO. Could that be coming from another ontology in your workspace?

**Comment by donpellegrino** [comment]
@balhoff Thanks! The SKOS perfLabel is probably coming from another ontology. I think I misinterpreted the log output. It seems the last three errors are missing the corresponding "finished loading" INFO message in my initial report. Protege Desktop seems to report the errors before reporting which ontology file was being processed.

I could try just loading RO and BFO into a clean Protege instance. Have the changes been published such that they will be picked up with the default RO import URLs or should I use a different approach to test the changes?

**Comment by balhoff** [comment]
I don't think a release has been made yet. We made some other fixes this week so I expect @cmungall will make a release in the near future.

**Comment by cmungall** [comment]
2016-10-28 release is out
