### ISSUE TITLE
relate RO:member_of to org:memberOf

### ISSUE THREAD

**Issue by nlwashington** [oborel/obo-relations#133]
Should there be any logical definitions/relationship to [org:memberOf](https://www.w3.org/ns/org#memberOf) ?

They are clearly different in their domain/range, but obviously related.  

cc @yifei-men

**Comment by cmungall** [comment]
The RO relation is far more general, and can be used with any kind of collection.

I don't know if logical superProperty is correct, as org may be built on such different assumptions.

We can certainly support a loose non-semantic mapping (e.g. xref, skosRelated, etc) between RO and external semweb ontologies and leave the details for users to work out.

**Comment by nlwashington** [comment]
makes sense to me

**Comment by nlharris** [comment]
Can this be closed?

**Comment by nlharris** [comment]
Closing, please reopen if needed.
