### ISSUE TITLE
Improve editors guide

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#139]
We have a fairly generic editors guide:

https://github.com/oborel/obo-relations/blob/master/src/ontology/README-editors.md

This should be updated. For example, we are now exploring PRs, this has worked for some contributors like @mbrush. But this has to be done carefully. Versions of Protege must be synchronized, and long running branches will get harder to merge.

We should also point to

 - https://github.com/jamesaoverton/obo-tutorial/
 - https://github.com/Planteome/protege-tutorial

Also need to document design patterns (#52). In particular

 - what we do for inverses (policy is to add, but to minimize redundant annotations, point back to 'base' property)
 - DPs for specific areas such as interactions

**Comment by cmungall** [comment]
The overall goal is to have a broader section of the community able to do pull requests, e.g. #143, with RO editors acting as gatekeepers

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
