### ISSUE TITLE
Add gene-disease relations

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#146]
These should be tightly coupled with https://www.wikidata.org/wiki/User:ProteinBoxBot/Gene-disease_links#Properties

cc @mbrush @pnrobinson @stuppie

**Comment by mbrush** [comment]
May also be informed by gene-disease  relations used in Orphanet.  See  [here](https://github.com/monarch-initiative/dipper/issues/431#issue-212212959).

**Comment by nlharris** [comment]
Looks like maybe this is done?

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
