### ISSUE TITLE
New and amended relations requested for DAF specification

### ISSUE THREAD

**Issue by mbrush** [oborel/obo-relations#149]
@cmungall tapped me to follow the new Disease Association Format spec work and get required relations amended or added to the RO. 
 
**(1) Amendments:** DAF editors requested that the definitions of existing  **_'causes or contributes to condition'_** relations are amended such that chemicals and genes are included in examples.  I propose to amend these relationship definitions as below, from:

`"A relationship between an entity (a genotype, genetic variation or environment) and a condition (a phenotype or disease) where the entity has some causal or contributing role that influences the condition."`
to
`"A relationship between an entity (e.g. a genotype, genetic variation, chemical, or environmental exposure) and a condition (a phenotype or disease), where the entity has some causal or contributing role that influences the condition."`
 
Note here that I *do not include genes* in the entity examples, as genes _per se_ do not cause disease, but are associated with disease in virtue of a variant in them causing disease.  There is ongoing work as part of the Monarch Initiative and Wikidata to define new relations for linking genes to diseases and add them to RO. See the ticket [**here**](https://github.com/oborel/obo-relations/issues/146).  In cases where a gene rather than a variant is the subject of an association, we would suggest the DAF uses these new relations once they are available.
 
**(2) Additions:** Also requested were two new relations:

`'ameliorates condition' - A relationship between an entity (e.g. a genotype, genetic variation, chemical, or environmental exposure) and a condition (a phenotype or disease), where the presence of the entity reduces or eliminates some or all aspects of the condition.`
and
` 'exacerbates  condition' - A relationship between an entity (e.g. a genotype, genetic variation, chemical, or environmental exposure) and a condition (a phenotype or disease), where the presence of the entity worsens some or all aspects of the condition.`

These definitions were adapted from the proposals made in the DAF spec documentation under development by Steven Marygold, Ranjana Kishore, Susan Bello, and other AGR consortium members.

Note that I am happy to omit the list of entity examples form these definitions altogether, if folks feel it does not belong or causes confusion. I would prefer to retain these examples in the metadata somewhere however -  either in an rdfs:comment, or using an iao:'example of usage' annotation to give examples of associations with each kind of subject.

**Comment by cmungall** [comment]
What would you suggest as the names for shortcut relations between genes and diseases.

E.g. if R is the relation between the perturbation/change (e.g. variant, introduction of a chemical into environment, etc) and the disease/condition, would we have

`'has variant that R' <- 'has variant' o R`

?

**Comment by sjm41** [comment]
Hi Matt

For the "(2) Additions" item, the actual terms we plan to use in the DAF are 'condition ameliorated by' and 'condition exacerbated by' (i.e. the reciprocals to what's stated above).  Seems sensible to add all four terms, or would that be ontologically frowned upon?

Suggested defs below:

condition_ameliorated_by
A relationship between condition (a phenotype or disease) and an entity (e.g. a genotype, genetic variation, chemical or environmental exposure) where some or all aspects of the condition are reduced or eliminated by the presence of the entity. 

condition_exacerbated_by
A relationship between condition (a phenotype or disease) and an entity (e.g. a genotype, genetic variation, chemical or environmental exposure) where some or all aspects of the condition are worsened by the presence of the entity.

**Comment by sjm41** [comment]
Hmmm.  I'm not sure why I didn't see these before, but I've just noticed some existing RO terrms that overlap/relate to the new ameliorates/exacerbates type term requests (see below).  We probably need to review this area of the RO to work out what's really needed in terms of any new terms/relations/defs.  What do you think?

capable of upregulating or causing pathological process (RO_0002600)
Holds between a material entity c and a pathological process p if and only if c is capable of some activity a, where a negatively regulates p.

capable of inhibiting or preventing pathological process (RO_0002599)
Def. Holds between a material entity c and a pathological process p if and only if c is capable of some activity a, where a inhibits p.

is preventative for condition (RO_0003307)
Def. A relationship between an entity (a genotype, genetic variation or environment) and a condition (a phenotype or disease) where the entity prevents or reduces the severity of a condition.

is treated by substance (RO_0002302)
Def. Inverse of 'is substance that treats'

is substance that treats (RO_0002606)
Def. c is a substance that treats d if c is a material entity (such as a small molecule or compound) and d is a pathological process, phenotype or disease, and c is capable of some activity that negative regulates or decreases the magnitude of d.

**Comment by mbrush** [comment]
Thanks for the feedback @sjm41. 

I proposed adding the ameliorates and exacerbates relations as above because their 'directionality' goes from  entity -> condition, and this is the direction of all other relations proposed in the DAF spec (e.g. 'causes condition', 'is model of').  I figured you would want to be consistent here with respect to the entity being annotated (genotype, variant, chemical, etc) representing the subject of the relations used in the spec. But happy to add inverse relations if my assumptions are wrong.
 
Regarding the 'capable of upregulating or causing pathological process' (RO_0002600) relation, this is explicitly stated as a relation between a material entity and a pathological process.  While many efforts play loose w.r.t the ontological nature of phenotypes and conditions, they are generally treated as dependent continuants of some kind (qualities, dispositions), and distinguished from pathological processes in which such dispositions may be realized.  Furthermore, not all the entities DAF will annotate will be material (e.g. genes, genotypes, variants are often modeled as generically dependent continuants).  These issues were one motivation for creating a separate branch of relations specifically to link entities to conditions they cause or contribute to.  So, as you suggested there is some overlap here, but I think we want to use relations in this condition-specific branch of the RO.  
 
That said, we may want to consider generalizing relations such as 'is substance that treats' (RO_0002606) to be inclusive of pathological processes and 'conditions', so that we avoid duplication of properties with same core semantics but (perhaps unnecessary) distinct constraints on the range. 
More generally, I think there are a few issues to work out in the causes condition branch of the RO, and suspect there will be some minor shake-ups here as part of the ongoing work to define gene-condition relations.  

So, for now let me know about the direction of the relations you need for the DAF as per the first point above. And as we evolve this part of the RO, I will let you know about any changes relevant to the relations used by the DAF.

**Comment by sjm41** [comment]
Hi Matt

I see what you mean about the directionality business. Indeed, our initial efforts at the DAF spec allowed the 'modifier' to be the primary entity of a disease annotation line, employing the 'ameliorates' and 'exacerbates' terms as appropriate.  However, such "modifier" statements are always applied to an existing disease model, and that model needs to be specified in the annotation.  In that context, it made more sense to always make the disease model the primary entity of the annotation, and then (when relevant) append a modifier entity linked to the disease model with 'ameliorated_by' and 'exacerbated_by'.
Whatever the final decision, it's likely all 4 terms will be required - e.g. the reciprocal relationships may be automatically derived for display purposes, and these will use the reciprocal RO term.

So can you add both pairs of reciprocal relationships (similar to 'is treated by substance (RO_0002302)' / 'is substance that treats (RO_0002606)'):
ameliorates_condition
condition_ameliorated_by
exacerbates_condition
condition_exacerbated_by


Thanks for pointing out the material basis of the 'capable of upregulating or causing pathological process' (RO_0002600) relation.  And I see the same is true of 'capable of inhibiting or preventing pathological process (RO_0002599)'.
But we should still review 'is preventative for condition (RO_0003307)' wrt the requested 'ameliorates_condition' term.  The two definitions are almost identical - likely synonyms?

**Comment by sjm41** [comment]
Hi Matt
We're continuing to move forward with our DAF format and content, and will soon want to add modifier information into those files.  Will you be able to add those 4 modifier terms (ameliorates_condition, condition_ameliorated_by, exacerbates_condition, condition_exacerbated_by) to the RO some time soon?  Do they need further discussion?  Thanks.

**Comment by mbrush** [comment]
Hi @sjm41. I will revisit these and try to get them added this week. Only possible complication is that there  the existing 'causes or contributes to condition' hierarchy may need to be adjusted a bit to accommodate these new terms, and new requirements coming from other sources.

**Comment by mbrush** [comment]
Below is the final proposal for implementing the four properties discussed above.  I will give a few days for review and comment by DAF and RO folks, before doing a fork and PR to submit additions.  @cmungall @sjm41.
 
1. **'ameliorates condition':** A relationship between an entity (e.g. a chemical, environmental exposure, or some form of genetic variation) and a condition (a phenotype or disease), where the presence of the entity reduces or eliminates some or all aspects of the condition. 
2. **'exacerbates condition':** A relationship between an entity (e.g. a chemical, environmental exposure, or some form of genetic variation)and a condition (a phenotype or disease), where the presence of the entity worsens some or all aspects of the condition.
3. **'condition ameliorated by':** A relationship between condition (a phenotype or disease) and an entity (e.g. a chemical, environmental exposure, or some form of genetic variation) where some or all aspects of the condition are reduced or eliminated by the presence of the entity.
4. **'condition exacerbated by':** A relationship between condition (a phenotype or disease) and an entity (e.g. a chemical, environmental exposure, or some form of genetic variation) where some or all aspects of the condition are worsened by the presence of the entity.
 
--------------

Note that RO currently holds the relation `RO:0003307 ! 'is preventative for condition'` (_def = a relationship between an entity (a genotype, genetic variation or environment) and a condition (a phenotype or disease) where the entity prevents or reduces the severity of a condition_), which seems equivalent to the proposed 'ameliorates condition'. I will therefore not create a new term here, but update the label of `RO:0003307` to 'ameliorates condition', and make slight adjustments to the wording of the definition for consistency with the other relations in this set. The label 'is preventative for condition will also be documented as an alternative term. The proposed changes should be minimally disruptive, as I added the `RO:0003307` relation for Monarch Initiative use cases only recently, and suspect this property has not been widely used. 
 
As for placement in the RO hierarchy, the 'ameliorates condition' and 'exacerbates condition' relations will be asserted under `RO:0003305 ! 'contributes to severity of condition'`. Their inverses will be asserted under `RO:00002410 ! 'causally related to'` - unless I am missing some other location in the RO where these would fit.

Finally, as part of this PR I will amend definitions of the 'causes or contributes to condition' relations such that chemicals and genes are included in examples, as proposed [above](https://github.com/oborel/obo-relations/issues/149#issue-205015473).

**Comment by sjm41** [comment]
Thanks Matt!  The final proposal looks good to me.
Noticed a couple of minor errors in the definitions:
1. 'exacerbates condition': Add a space in this bit: "variation)and"
2. 'condition ameliorated by': Add an 'a' in this bit: "between condition"
3. 'condition exacerbated by': Add an 'a' in this bit: "between condition"

**Comment by mbrush** [comment]
Closed with merge of PR https://github.com/oborel/obo-relations/pull/179
