### ISSUE TITLE
Error in text definition of RO_0002600 

### ISSUE THREAD

**Issue by mbrush** [oborel/obo-relations#150]
Noted an error in the textual definition of RO_0002600 # 'capable of upregulating or causing pathological process'.  The current def:
 
_"Holds between a material entity c and a pathological process p if and only if c is capable of some activity a, where a **_negatively_** regulates p."_ 

should read
 
_"Holds between a material entity c and a pathological process p if and only if c is capable of some activity a, where a **_positively_** regulates p."_

If no objections, I can make this fix and submit with a PR I plan to make soon for adding relations for the DAF spec (#149).

**Comment by nlharris** [comment]
@mbrush did you make the fix?

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
