### ISSUE TITLE
how to annotate or express that an entity has a preferred measurement unit (label)

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [oborel/obo-relations#152]
Currently we can say that a particular datum "has measurement unit label" some [Unit Ontology id].

But in the interest of normalizing data across data repositories, it would be great to express that a type of entity has a recommended unit.  That way data repositories that buy into a particular application ontology's proscription could know which unit to eventually migrate their data store values to.  So something like "has preferred measurement unit label"?  E.g. "air temperature" "has preferred measurement unit label" some "celsius".

**Comment by cmungall** [comment]
This should probably go in the same ontology as 'has measurement unit', which is.. obi? iao?

Bit of an arbitrary split, but RO has tended to focus on relations between biological entities

**Comment by Public-Health-Bioinformatics** [comment]
Ah, I see.  I'd assumed RO was taking all comers. Ok, I'll head over to IAO.
Thx!
