### ISSUE TITLE
More property chains needed

### ISSUE THREAD

**Issue by ukemi** [oborel/obo-relations#153]
When generating annotations from Noctua models, not all all of the annotations are available because there appears to be missing property chains for downstream individuals. In particular I think we need chains like:
involved_in o causally_upstream_of -> acts_upstream_of
involved_in o causally_upstream_of_or_within -> acts_upstream_of_or_within

etc.

**Comment by vanaukenk** [comment]
@ukemi @balhoff 

It looks like we still need additional property chains to get the annotations we'd want in the GPAD files coming from Noctua.  I don't currently see them in RO, but it seems like we'd want (for the neutral as well as positive and negative children) these:

enables o part_of o causally_upstream_of -> acts_upstream_of
enables o part_of o causally_upstream_of_or_within -> acts_upstream_of_or_within

**Comment by cmungall** [comment]
OK we'll look at these next week

**Comment by phismith** [comment]
Can we require that each proposal of this sort provides

Name of proposer
Name of relation
Natural language definition of relation
OWL definition of relation
Specification of domain and range?

BS

**Comment by cmungall** [comment]
Hi Barry, as it's coming from github we have full provenance about proposer, when proposed, discussion of proposal

In this case Kimberley is proposing a new property chain axiom, no new relations
