### ISSUE TITLE
Unversioned artifacts

### ISSUE THREAD

**Issue by alanruttenberg** [oborel/obo-relations#154]
In creating a dated release for IAO, I want to ensure that the contents will not change over time. As a result I check whether any imported ontologies do not have a versionIRI and make a local copy if not. However I believe these should, in fact, all be given versionIRIs, so I'd request that adding them become a standard part of your release process. The artifacts in question are:

* http://purl.obolibrary.org/obo/ro/core.owl 
* http://purl.obolibrary.org/obo/ro/bfo-axioms.owl 
* http://purl.obolibrary.org/obo/ro/annotations.owl 
* http://purl.obolibrary.org/obo/ro/bfo-classes-minimal.owl

Thanks,
Alan

**Comment by cmungall** [comment]
+1

when do you need them by?

**Comment by alanruttenberg** [comment]
Whenever I do the next IAO release. Just did one.

**Comment by nlharris** [comment]
is this done?

**Comment by nlharris** [comment]
@alanruttenberg can this ticket be closed?

**Comment by alanruttenberg** [comment]
It's not done but I'm told that only merged ontologies are versioned now, so it isn't relevant. So closing.
