### ISSUE TITLE
Direct physical interaction required for 'molecularly interacts with' relation?

### ISSUE THREAD

**Issue by mbrush** [oborel/obo-relations#156]
Quick question about the RO:0002436 ! 'molecularly interacts with' hierarchy of properties in RO.  The definition does not seem to require that a direct physical interaction occur between molecular participants:L
  
`An interaction relationship in which the two partners are molecular entities and are executing molecular processes that are directly causally connected.`
  
But an 'alternative term' for this relation is 'binds' - which implies a necessary direct physical interaction.
This distinction is particularly relevant as we consider expanding the subhierarchy as per #144 to support drug-target interaction models.  Here, some drug-target interactions may not be based on direct binding interactions - so the question posed here has implications for where we would classify properties created for these interaction types.

**Comment by nlharris** [comment]
@mbrush do you still need an answer to this question?

**Comment by nlharris** [comment]
Closing; please reopen if needed.
