### ISSUE TITLE
Same definition for 'directly activates' and 'indirectly activates'

### ISSUE THREAD

**Issue by vanaukenk** [oborel/obo-relations#159]
Hi,

In looking over the causal relations, it seems that 'directly activates' and 'indirectly activates' share the definition for 'directly activates'.

id: RO:0002406
name: directly activates
def: "p directly activates q if and only if p is immediately upstream of q and p is the realization of a function to increase the rate or activity of q" []
property_value: IAO:0000114 IAO:0000428
property_value: IAO:0000117 "Chris Mungall" xsd:string
property_value: IAO:0000118 "directly positively regulates" xsd:string
property_value: IAO:0000119 http://purl.obolibrary.org/obo/ro/docs/causal-relations
property_value: IAO:0000589 "directly activates (process to process)" xsd:string
is_a: RO:0002629 ! directly positively regulates

id: RO:0002407
name: indirectly activates
def: "p directly activates q if and only if p is immediately upstream of q and p is the realization of a function to increase the rate or activity of q" []
property_value: IAO:0000117 "Chris Mungall" xsd:string
property_value: IAO:0000118 "indirectly positively regulates" xsd:string
property_value: RO:0002579 RO:0002213
holds_over_chain: RO:0002406 RO:0002406
holds_over_chain: RO:0002406 RO:0002407
holds_over_chain: RO:0002409 RO:0002409
is_transitive: true
is_a: RO:0002213 ! positively regulates
transitive_over: RO:0002406 ! directly activates

**Comment by nlharris** [comment]
Surely this must have been fixed by now?

**Comment by vanaukenk** [comment]
@nlharris 
Yes, this has been fixed, so I'll close the ticket.
Thx.
