### ISSUE TITLE
NTR: 'transports'

### ISSUE THREAD

**Issue by pgaudet** [oborel/obo-relations#161]
Hello, 

To make the equivalence axioms in GO it would be useful to have 'transports' as a child of 'transports or maintains location of'; since this is odd for terms that cover strictly transport, such as 'transmembrane transport'. 

Thanks, Pascale

**Comment by dosumis** [comment]
Fixed.  @pgaudet : Will need to be added to list of relations to import to GO.  But RO release needed first.
