### ISSUE TITLE
Add occurs_across relation

### ISSUE THREAD

**Issue by dosumis** [oborel/obo-relations#166]
We have a specific relation 'results in transport across'. This should be replaced with a more general relation 'occurs across', which can be used outside of transport.  This is needed for process affecting membrane polarization.  Use of occurs_in for these cases leads to unwanted inference in LEGO (GO-CAM) models.  

**has_part_that_occur_in**
    <- *subPropertyOf*- **occurs across**: "A barrier across which a  process occurs - typically a membrane.  Examples include transport across a membrane and membrane depolarization."

**Comment by cmungall** [comment]
Seems a bit of a circular def how about:

occurs across: "A relationship between a process and a barrier, where the process occurs in a region spanning the barrier. For cellular processes the barrier is typically a membrane. Examples include transport across a membrane and membrane depolarization."

It doesn't seem safe to replace existing relation? Keep as a subprop for now and possibly deprecate later?

**Comment by dosumis** [comment]
Added & have made it a 'results in transport across' a subprop for now.  But may be better to switch GO to just use the general relation only as a way of limiting complexity/relation numbers.
