### ISSUE TITLE
Make cryptic domain and range constraints more obvious

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#168]
http://purl.obolibrary.org/obo/RO_0001025 located in
'A relation between two independent continuants, the target and the location, in which the target is entirely within the location'
(note: OB doesn't seem to be showing all axioms)

Based on this and lack of D/R constraints we might assume located-in can be between any 2 ICs.

However, this isn't the case. See http://purl.obolibrary.org/obo/RO_0001018

Due to `located-in o part-of -> contained-in`, we effectively inherit the domain constraint from contained-in. See for example:

![image](https://cloud.githubusercontent.com/assets/50745/26561363/93bec214-4472-11e7-856b-9fc45ee09e97.png)

We might say that 'located in' has a cryptic domain constraint, since AFAICT it is not easy to view these inferred axioms

**Comment by cmungall** [comment]
It's not clear `located-in o part-of -> contained-in` is intended/correct

**Comment by dosumis** [comment]
This sounds very familiar (coin in a bottle?) - one of my major aims for BFO back in the day was getting a coherent story & set of axioms for this.

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
