### ISSUE TITLE
Improve documentation on 'has input' and subproperties, deprecating unnecessary terms

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#171]
This ticket subsumes:

#17
#18

Documentation here: 
https://docs.google.com/document/d/1QMhs9J-P_q3o_rDh-IX4ZEnz0PnXrzLRVkI3vvz8NEQ/edit?usp=sharing

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
