### ISSUE TITLE
Add annotations connecting ObjectProperties to design pattern URIs

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#174]
Either use a new AnnotationProperty, or use something like seeAlso.

This could be done automatically, using some registry of DPs

**Comment by jamesaoverton** [comment]
Can you give an example?

**Comment by cmungall** [comment]
https://github.com/geneontology/go-ontology/tree/master/src/design_patterns/validated_patterns/transmembrane_import_into_cell.yaml
from
RO:0002338

**Comment by jamesaoverton** [comment]
So this would be an annotation property that links from RO:0002338 to the (GitHub) URL for the template that was used to generate various axioms and annotation for RO:0002338.

I think it's a good idea. Some thoughts:

- it would be good to support different templating systems, but it's reasonable that any system would use a URL to identify a template
- once you use a URL to identify a template, there are questions about permanence and versioning
- related: for one of my current template tools, I would like to also keep the values that fill the template "slots" as distinct annotations on the generated term, and those annotations need predicate URLs; I haven't got a preferred solution yet

So like usual, I can foresee all sorts of complications. But I think we can safely start small with an AnnotationProperty that links a term to the URL of the template.

**Comment by cmungall** [comment]
* Different systems: exactly, no assumptions, just a URL
 * Provenance and versioning: we keep them all in the same github repo so should be easy to have current PURLs and versioned PURLs
 * We've considered this for DOSDPs, haven't come up with a solution

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
