### ISSUE TITLE
Relations describing correlation with response to treatment

### ISSUE THREAD

**Issue by mbrush** [oborel/obo-relations#178]
Many databases, e.g. CIViC, OncoKB,  document how  things like genetic variants or  expression levels  predict response  to a particular treatment (e.g. [here](https://civic.genome.wustl.edu/events/genes/5/summary/variants/12/summary#variant)).  To model this data, we need a property to describe this relationship.  Starting a discussion below with some straw man definitions and requirements, which will likely evolve as more use cases come up.
 
Proposing here two properties, that would be asserted under RO_0002610 ! 'correlated with':
1.	**'correlated with sensitivity to treatment'**, informally defined as a relation holding between an entity and a therapeutic treatment wherein a positive response to the treatment is statistically correlated with the presence of the entity.
2.	**'correlated with resistance to treatment'**, informally defined as a relation holding between an entity and a therapeutic treatment wherein a lack of response to the treatment is statistically correlated with the presence of the entity.
 
Optionally, we could have a parent/grouping property 'correlates with response to treatment'.

The subject of these properties is most often a particular genetic variant, but may also be some other genetic marker (e.g. expression level of a particular gene), a behavior or process in which the patient participates, or some exposure they have experienced. 
 
We will likely want the range of these properties to encompass treatments modeled as processes (e.g. exposures to drugs, as in [ECTO](https://github.com/cmungall/environmental-conditions)), or as chemicals (e.g. specific drugs or drug sets) - as both approaches are seen in various  databases and integration efforts.
 
We propose this as a property of _correlation_ rather than _causation_, as a causal relationship between the variant and a treatment response is often not established.

Note that these properties are intended to approximate the Wikidata properties 'positive therapeutic predictor' ([link](https://www.wikidata.org/wiki/Wikidata:Property_proposal/positive_therapeutic_predictor), [link](https://www.wikidata.org/wiki/Property:P3354)) and 'negative therapeutic predictor' ([link](https://www.wikidata.org/wiki/Property:P3355)).

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
