### ISSUE TITLE
'negatively regulates' should not be a transitive property

### ISSUE THREAD

**Issue by balhoff** [oborel/obo-relations#182]
[negatively regulates](http://purl.obolibrary.org/obo/RO_0002212) is marked as a transitive property. This should not be true.

**Comment by dosumis** [comment]
Why not?  Regulates is transitive.  Does this mean we are relying on rules alone and so can not assume inference across chains of neg reg in the ontology?

**Comment by balhoff** [comment]
It just doesn't make sense. If A negatively regulates B, and B negatively regulates C, A will impede the negative regulation of C. We have a chain `negatively regulates` o `negatively regulates` -> `positively regulates`. 

A `regulates` relationship will be inferred and it is still transitive.

**Comment by dosumis** [comment]
Doh....  You're right of course.  Ignore me.
