### ISSUE TITLE
increases expression of & decreases expression of need to be moved

### ISSUE THREAD

**Issue by dosumis** [oborel/obo-relations#186]
Should not be under direct reg relations as these require interaction between gene products.

Maybe move to under new relation  'activity regulates activity of'  under causally influences,  mirroring the process:process reg branch

![image](https://user-images.githubusercontent.com/112839/28509178-58d916f6-707b-11e7-8bf9-1c8ff64bec7b.png)

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
