### ISSUE TITLE
new 'has taxonomic identifier' relation?

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [oborel/obo-relations#189]
I'm not sure if this would be appropriate here or in NCBITaxon itself, but I have a need for an object relation 'has taxonomic identifier' to associate an organism with one or more identifiers in one or more taxonomic classification systems - identifiers may be from other ontologies like NCBITaxon, or may be dbxref style "ITIS:25262" string literals.  Examples:

'apple tree' 'has taxonomic identifier' some 'Malus pumila' [NCBITaxon:283210]
'apple tree' 'has taxonomic identifier' some 'ITIS:25262'
‘european anchovy’ ‘has taxonomic identifier’ some ‘Engraulis encrasicolus’
turtle 'has taxonomic identifier' some 'Testudines'

One could say that 'european anchovy' is a synonym for ‘Engraulis encrasicolus’ but I think it is better to keep separate the natural language term reference to an organism from the taxonomic system reference. In this way the common language class of "spinach" edible plant can have subclasses which are varieties of spinach that are not closely related to each other by taxonomy, but which have respective taxonomic identifiers to different species.  The taxonomic identifier relation provides access to differentia to distinguish one organism from another. Since an organism can be identified in more than one taxonomy system, and since these systems can vary in their description of differentia, this relation offers more information than synonymy alone provides. 

Term: **'has taxonomic identifier'**
Definition: "The 'has taxonomic identifier' relation exists between an organism or class of organism and one or more identifiers from one or more taxonomic databases that the organism(s) have been classified under.
Example usage: 'apple tree' 'has taxonomic identifier' some 'Malus pumila'

Thoughts?

**Comment by cmungall** [comment]
You could just use the existing hasDbXref property?

Alternatively, you could assume some semantic interpretation of the URI 
corresponding to the CURIE and make a more explicit axiom, e.g. 
equivalence axiom, in_taxon, etc

**Comment by Public-Health-Bioinformatics** [comment]
I could use an explicit axiom & relation in many cases, and just downgrade to a DBXref if range was textual (i.e. not a match to NCBITaxon) since reasoning on textual scientific name would be dubious.  Somehow I didn't notice "in_taxon" in RO.  Is it actually the same as the 'has taxonomic identifier'?  Is its range restricted to NCBITaxon?  Do you have a definition for it?  Thanks!

**Comment by cmungall** [comment]
Def is here: http://purl.obolibrary.org/obo/RO_0002162

> Is it actually the same as the 'has taxonomic identifier'? Is its range restricted to NCBITaxon?

No, it ranges over actual material entities, organisms, not identifiers

**Comment by Public-Health-Bioinformatics** [comment]
Ah, I thought OLS was showing definitions like Ontobee but I see it isn't.  

In this case I would like an 'has taxonomic identifier' relation which has domain some organism and has range some ontology IRI (i.e. NCBITaxon term). My apple example meant to imply that 

    'apple tree' 'has taxonomic identifier' some [NCBITaxon:283210]   # 'Malus pumila'

(Currently it is a FoodOn relation, and it could stay there.)

**Comment by ddooley** [comment]
We can close this.  I have switched to using 'only in taxon'.

**Comment by jamesaoverton** [comment]
@ddooley We've been discussing 'only in taxon' in a few other contexts recently:

https://github.com/OBOFoundry/COB/issues/58#issuecomment-595893809
https://github.com/OBOFoundry/COB/issues/60

Based on that discussion, I think the consensus is to use "'in taxon' only 'Homo sapiens'" rather than "'only in taxon' some 'Homo sapiens'" for new work.

**Comment by ddooley** [comment]
Ok. Will switch to "in taxon" in FoodOn. Luckily I didn't do a release with change yet so users won't get as much whiplash.

**Comment by nlharris** [comment]
Can this be closed?

**Comment by ddooley** [comment]
I think so!

**Comment by nlharris** [comment]
Ok, closing. 👻
