### ISSUE TITLE
'Is transmitted by' relation

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [oborel/obo-relations#190]
I was working on a model of infectious disease transmission, and weaving OBI, TRANS, IDO etc. terms together to get this DRAFT handcrafted diagram:

<img width="400" alt="screen shot 2017-08-02 at 12 29 22 pm" src="https://user-images.githubusercontent.com/10779910/29252364-3df05274-801a-11e7-9e48-4b09a180de3c.png">

Then I looked a bit closer at "transmitted by" in RO, and saw that it was meant to tie a disease directly to an infectious agent vector (the upper red arrow relation).  But domain/range haven't been defined yet for that relation.  Would it be ok to leave it loose and allow it to ALSO have domain infectious agent, and range transmission process (the center-bottom red relation)? Or we disambiguate and create a new relation.

Thanks,

**Comment by Public-Health-Bioinformatics** [comment]
Also I see "'susceptible organism' 'causally downstream of' some host" doesn't work because relation is for processes. Maybe 
    host 'derives from' 'susceptible organism'
    'transmission process' 'has input' some 'susceptible organism'
    'transmission process' 'has output' some host

**Comment by nlharris** [comment]
Is this a request for a new term, or to change an existing definition, or both?

**Comment by nlharris** [comment]
Can this be closed?

**Comment by nlharris** [comment]
Closing as won't do; reopen if needed.
