### ISSUE TITLE
Add labels to two GO entities in RO

### ISSUE THREAD

**Issue by ramonawalls** [oborel/obo-relations#191]
RO currently includes GO_0004872 and GO_0040011. Neither has labels. This doesn't really cause any problems, but it looks messy if I import RO.  Also GO_0040011 does not appear to have any usage in RO, so maybe it could just be removed.

**Comment by cmungall** [comment]
ugh, we really need a proper RO import module..

**Comment by cmungall** [comment]
ok closing as immediate issue addressed, but lack of proper imports is a problem

**Comment by nlharris** [comment]
You said "closing" so I'm going to close this.
