### ISSUE TITLE
is active in

### ISSUE THREAD

**Issue by dosumis** [oborel/obo-relations#193]
We currently have the property chain 
enables o occurs in -> part of

This is unsafe, especially when it interacts with axiomatization of compound functions.
e.g. GP-X enables 'transmembrane receptor kinase activity' has_part Kinase activity occurs in intracellular 
=> GP-X part of intracellular

To solve this, we should add a new relation/qualifier:  is_active_in

This is a subproperty of overlaps.

The textual definition should make it clear that it refers to some/any activity of a gene product.

**Comment by dosumis** [comment]
CC @vanaukenk

**Comment by dosumis** [comment]
We also need co-ordination with GO curator groups / EBI to make clear that this is a now a valid qualifier.  Perhaps this should be done more universally with an annotation property?

**Comment by balhoff** [comment]
Do you have an example model? Do you get "GP-X enables kinase activity" from `enables o 'has component activity' -> enables`? That chain seems unexpected to me.

**Comment by cmungall** [comment]
> We also need co-ordination with GO curator groups / EBI to make clear that this is a now a valid qualifier. Perhaps this should be done more universally with an annotation property?

+1

how about as a subset?

**Comment by cmungall** [comment]
@balhoff - valid question. I made a new ticket for clarifying the intended chains for enables here: #198 

I think we can proceed with this ticket regardless. The is-inactive-in shortcut is potentially useful for even the simpler case

```
[a GP] -enables->[a MF] -occurs_in->[a CC]
```

**Comment by cmungall** [comment]
Ah, turns out we already have this:

[RO:0002432](http://purl.obolibrary.org/obo/RO_0002432) ! enables activity in

Happy to change the label, or at least add a synonym

**Comment by dosumis** [comment]
See https://github.com/geneontology/noctua/issues/470 for another use-case where this is needed.

**Comment by dosumis** [comment]
CC @BarbaraCzub

**Comment by dosumis** [comment]
@ukemi @pgaudet @vanaukenk: As discussed during the Berkeley training meeting, the aim of this proposal is to add 'is active in' as a qualifier for GP -> MF.  This will be inferred from occurs_in relationships where part_of is now (unsafely) inferred.   With the edits now in place 'is active in' will be inferred in these cases, but I have yet to remove inference to part_of as I assume this needs wider agreement.  Are you OK for me to remove this now, or should I wait?
Cheers, 
David

**Comment by pgaudet** [comment]
Hi @dosumis 
1. Just a clarification: was this to capture CC when we don't know whether the activity of the GP takes place in that location ? 

2. I am not following your example: 
e.g. GP-X enables 'transmembrane receptor kinase activity' has_part Kinase activity occurs in intracellular
=> GP-X part of intracellular
We had this discussion many times. How I understand this statement is that the kinase activity is mediated by an intracellular *domain* of a protein; hence you are not annotating the full GP; is this correct? 
If that's the case then this proposal needs to also include how we'll capture which part of the protein you are making the assertion about. 

Otherwise I think we should stick to 'membrane' which would include surrounding areas. 

Thanks, 

Pascale

**Comment by dosumis** [comment]
I thought this was agreed in Berkeley.  We had a more detailed discussion
of the problems caused by inferring location 'part of' relationships for
gene products using 'occurs in'

On Sep 15, 2017 6:31 AM, "pgaudet" <notifications@github.com> wrote:

Hi @dosumis <https://github.com/dosumis>

   1.

   Just a clarification: was this to capture CC when we don't know whether
   the activity of the GP takes place in that location ?


This is an inferred GP to CC relation when MF occurs_in GP is used.


   1.
   2.

   I am not following your example:

   e.g. GP-X enables 'transmembrane receptor kinase activity' has_part
   Kinase activity occurs in intracellular
   => GP-X part of intracellular
   We had this discussion many times. How I understand this statement is
   that the kinase activity is mediated by an intracellular *domain* of a
   protein; hence you are not annotating the full GP; is this correct?
   If that's the case then this proposal needs to also include how we'll
   capture which part of the protein you are making the assertion about.


Otherwise I think we should stick to 'membrane' which would include
surrounding areas.


This allows more fine grained capture of where sub activities of MFs occur.
You may wish to discourage this in GOCAM, but it can be useful for clearly
defining some compound MFs in the ontology.

Thanks,

Pascale

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/oborel/obo-relations/issues/193#issuecomment-329685598>,
or mute the thread

**Comment by thomaspd** [comment]
I don't know if we want to prioritize this right now.  The main use for this inference, at least right now, would be in creating GPAD output, and we really want to keep things simple.  In the case of subfunctions, making a standard GO annotation from these, e.g. INSR active_in cytosol, will confuse both curators and users.

**Comment by cmungall** [comment]
> The property chain "enables o occurs in -> part of" makes this impossible without getting wrong inferences, so I'd like to delete it.

+1

This PR adds the relation to the GP->Term whitelist relation set: https://github.com/geneontology/minerva/pull/139

This should be synchronized otherwise we'll lose GPAD exports

**Comment by dosumis** [comment]
> In the case of subfunctions, making a standard GO annotation from these, e.g. INSR active_in cytosol, will confuse both curators and users.

This could be avoided by using more membrane associated terms in the design patterns to refer to the side of the membrane where a subfunction acts.

**Comment by pgaudet** [comment]
@dosumis in this case you are talking about design patterns in the ontology or in annotations ? 
I still think this should be taken in the context of the entity we are annotating (ie it cannot live in the ontology).

**Comment by dosumis** [comment]
On Sep 20, 2017 1:17 PM, "pgaudet" <notifications@github.com> wrote:

@dosumis <https://github.com/dosumis> in this case you are talking about
design patterns in the ontology or in annotations ?
I still think this should be taken in the context of the entity we are
annotating (ie it cannot live in the ontology).

—
You are receiving this because you were mentioned


Not sure what you mean.  This is about the inferred GP to CC relationship
when MF occurs_in CC is asserted in a GOCAM model.

**Comment by dosumis** [comment]
> @dosumis in this case you are talking about design patterns in the ontology or in annotations ?
I still think this should be taken in the context of the entity we are annotating (ie it cannot live in the ontology).

Either.  Could be useful in the ontology to record what domain is intracellular and what extracellular.

**Comment by nlharris** [comment]
What is the status of this?

**Comment by vanaukenk** [comment]
@nlharris 
I think we could close this one, too.
We now use the 'is active in' relation for standard GO CC annotations and we have the property chain of 'enables o occurs in' -> 'is active in', so I think we okay for now.
