### ISSUE TITLE
Add rule to infer involved_in for complex components

### ISSUE THREAD

**Issue by dosumis** [oborel/obo-relations#195]
GP-x part_of complex-A enables MF-1 part_of BP-1

=> GP-x involved_in BP1

**Comment by cmungall** [comment]
writing as a test in unambiguous ttl (assuming standard prefixes):

```
:gpx
    part_of: [a ComplexA: ;
                   enables: [a MF1: ;
                                    part_of: :bp1 ] ]
=>
:gpx involved_in: :bp1
```

This could be achieved by

`part_of o enables o part_of -> involved_in`

but note we already have:

`enables o 'part of' SubPropertyOf: 'involved in'`

so this could be simplified to:

`part_of o involved_in -> involved_in`

It's not clear if any of these would admit unwanted inferences

**Comment by dosumis** [comment]
I think I prefer the more explicit chain.  I can't spot problems with the more compact one right now, but it makes me uneasy.

**Comment by nlharris** [comment]
Closing as obsolete; reopen if desired.
