### ISSUE TITLE
clarify desired property chains for enables

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#198]
We currently have 

 * `enables o 'has component activity' -> enables`

We can imagine an even stronger

 * `enables o 'has part' -> enables`

This was proposed by @dosumis in the [MF refactor doc](https://docs.google.com/document/d/18VQaVHvTmNvJuRczlnmJnjLtd2WxvfGafXoU1LFEQ2c/edit?usp=sharing)

I back the proposal for the stronger axiom

**Comment by dosumis** [comment]
@balhoff comment copied from other ticket (seems more relevant here):

> Do you have an example model? Do you get "GP-X enables kinase activity" from enables o 'has component activity' -> enables? That chain seems unexpected to me.
