### ISSUE TITLE
Remove  transports or maintains localization of' o 'part of' -> 'occurs in'

### ISSUE THREAD

**Issue by dosumis** [oborel/obo-relations#200]
See geneontology/go-ontology#14117

**Comment by cmungall** [comment]
+1

**Comment by cmungall** [comment]
will take care of this next week, if urgent you can go ahead and do it

**Comment by nlharris** [comment]
Is this done?

**Comment by balhoff** [comment]
This chain is not in the ontology; must have been removed at some point.
