### ISSUE TITLE
Review "results in the formation of"?

### ISSUE THREAD

**Issue by pbuttigieg** [oborel/obo-relations#201]
The use of these relations outside of biological systems could be very useful for ENVO and other ontologies, however, their domains link them to biological processes resulting in inferred relations like:

![image](https://user-images.githubusercontent.com/2276146/30062370-d09294f4-9242-11e7-9d11-0238a7546ec9.png)

Is this something that can be relaxed for more general usage?

**Comment by nlharris** [comment]
Is there still an action item here?

**Comment by nlharris** [comment]
See also #72

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
