### ISSUE TITLE
Rename 'has consumer' relation to 'has potential consumer'

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [oborel/obo-relations#205]
As flagged in the past,  "[organism] 'has consumer' [organism]" leads to an instance of an organism necessarily having an instance of a consumer somewhere.  Can we rename this newish relation to 'has potential consumer' to avoid this?

**Comment by balhoff** [comment]
Would it work to confine such some-some relations to instance annotations? This could be a set of object property assertions documenting observed 'has consumer' relationships.

**Comment by Public-Health-Bioinformatics** [comment]
I see your point, 'has consumer' relation's raison-d-etre is to capture instance-instance annotations like "Milk_X 'has consumer' Frank".  Seems best not to rename that relation!
I was trying to describe food chains generally, where a class of organism or food product is consumable by another class of organism with often beneficial or at least no ill nutritional affect.  The problem I'm grappling with is that ultimately we have to provide for exceptions; now I'm thinking this can only be done via subclasses of humans, e.g. "lactose intolerant human' subClassOf human and 'has quality' lactose intolerant' and not 'consumer of' milk".  That's the best way? We define the negated consumer space instead?

**Comment by balhoff** [comment]
NCIt has a bunch of properties that include "may", like "Disease_May_Have_Cytogenetic_Abnormality". That might work for you, if you make a relation "may_have_consumer". But then since you already know about lactose-intolerant humans you should probably only make the relationship from milk to human, and not vice versa with an inverse property.

But then again there are theoretical subclasses of milk like 'rancid milk', that may not be consumed by anybody. So these "may" properties have their problems.

**Comment by Public-Health-Bioinformatics** [comment]
I'm sensing a different "process encapsulation" approach here is the way to go.  Its not that lactose intolerant people can't consume lactose laden milk (not a case of square peg and circular hole); its that consumption of such milk leads to ill health.  So its the beneficial and detrimental effects of an encapsulated feeding process which has subprocesses, some involving milk and the consumer's constitution.  "has consumer" becomes a relation that one can establish between inputs and participants of this feeding process where it has successful outcomes.  So I'm ready to close this one...

**Comment by nlharris** [comment]
If ghost was ready to close this in 2017, can we go ahead and close it?

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
