### ISSUE TITLE
Errors in some RO term textual definitions

### ISSUE THREAD

**Issue by sgehant** [oborel/obo-relations#206]
I'd like to report what I believe are errors in the textual description of some RO terms.

For RO_0002524:

"x has subsequence y iff all of the sequence parts of x are sequence parts of y"

while I think it should be the opposite: "x has subsequence y iff all of the sequence parts of **y** are sequence parts of **x**"

For RO_0002526:

"x overlaps the sequence of x if and only if x has a subsequence z and z is a subsequence of y."

while I think it should be "x overlaps the sequence of **y** if and only if x has a subsequence z and z is a subsequence of y."

For RO_0002527:

"x does not overlaps the sequence of x if and only if there is no z such that x has a subsequence z and z is a subsequence of y."

while I think it should be "x does not overlaps the sequence of **y** if and only if there is no z such that x has a subsequence z and z is a subsequence of y."

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.

**Comment by sgehant** [comment]
The issue was closed while what I believe are errors are still there.

Either one should explain me why these are not errors, or correct them

**Comment by wdduncan** [comment]
@sgehant The issue was closed due to inactivity. RO is not funded and relies on volunteers to contribute effort. If you wish to put effort into addressing the issue(s) you've identified, you are welcome to reopen the issue and continue working on it.

**Comment by wdduncan** [comment]
@sgehant If you want to attend, the next meeting is on 2023-01-31 at 9am PT, 18.00 CET. Damion Dooley is charing. 

Minutes/agenda : http://bit.ly/ro-minutes
Zoom link: https://lbnl.zoom.us/j/97163538233?pwd=czlTWTRzb0YvY0sxa1hwWERZUTFEQT09

**Comment by balhoff** [comment]
I'll take this on.
