### ISSUE TITLE
Move ro-edit.owl to functional syntax

### ISSUE THREAD

**Issue by dosumis** [oborel/obo-relations#207]
1. This would give much more usable diffs & the possibility to fix clashes by hand if required.

2. Now we're using 'branch - pull - merge' regularly with RO, can we move the master to functional syntax + have some guidance on what OWL-API versions serialised in a way that is safe to use with merging?  Merge with rdf xml makes me very nervous and the git-owl-tools appears to be broken https://github.com/ShahimEssaid/git-owl-tools/issues/4

**Comment by balhoff** [comment]
+1 !

**Comment by cmungall** [comment]
let's do it. After that we can make some other much needed changes like making proper import modules. See if I can find some time later today

**Comment by cmungall** [comment]
I'll let you do the merge @dosumis in case you have any outstanding commits (if you do, easy to redo)
