### ISSUE TITLE
generically depends on

### ISSUE THREAD

**Issue by msinclair2** [oborel/obo-relations#208]
What relation is used to describe a generically dependent continuant's inherence in its independent continuant bearer?

BFO specifies a "generically depends on" relation, but this does not exist in RO.

**Comment by cmungall** [comment]
Thanks for the wake up call on https://github.com/geneontology/go-ontology/issues/15894#issuecomment-399577484

Would you be able to make a pull request for this?

**Comment by nlharris** [comment]
Since the PR was merged, I think this issue can be closed, right?
