### ISSUE TITLE
has quality domain 

### ISSUE THREAD

**Issue by kaiiam** [oborel/obo-relations#209]
Hello RO development team,

I noticed that the RO relation [has quality](http://purl.obolibrary.org/obo/RO_0000086) has independent continuant specified as the domain. 

Pato also has the class [rate](http://purl.obolibrary.org/obo/PATO_0000161) which inheres in a process. Is there another relation for this, or should the domain of has quality be relaxed to include processes? 

I would like to be able to ascribe rate qualities to processes. 

Thanks,
Kai

**Comment by mah11** [comment]
I have had the same question for some time. At present (and over the past four years) the Fission Yeast Phenotype Ontology simply ascribes rates and durations to processes, despite the domain restriction in RO.

**Comment by cmungall** [comment]
I think this has to be relaxed to accomodate current usage. Not sure when that was added

**Comment by kaiiam** [comment]
Sounds good, thank you for agreeing to relax the domain.

**Comment by nlharris** [comment]
Was this done?

**Comment by cmungall** [comment]
will be closed by #284
