### ISSUE TITLE
NR: localized-to

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#215]
We need a relation for connecting gene products to cell components (that could be used more generally) that is inclusive of but weaker than part-of, and a super-property-of is is-active-in (See #193). @ukemi and @vanaukenk and I will work on a strict definition.

**Comment by dosumis** [comment]
Why?

**Comment by vanaukenk** [comment]
@nlharris 
Here's another one I think we can close.
For GO, at least, we've agreed to use 'located in' to capture this information.
