### ISSUE TITLE
Consider consolidating RO artifacts

### ISSUE THREAD

**Issue by balhoff** [oborel/obo-relations#216]
Are there use cases for the various modules by which RO is currently distributed? Currently the main ontology imports pieces of RO:

* annotations.owl
* temporal-intervals.owl
* core.owl
* el-constraints.owl
* rohom.owl
* *etc.*

as well as extracts of other ontologies:
* pato_import.owl
* go_cc_import.owl
* go_mf_import.owl
* *etc.*

This arrangement makes it hard for a downstream user to exclude the extracts from other ontologies (e.g. when separately importing the complete versions of those ontologies) but keep all the RO content. From my perspective it would be ideal if RO were distributed as one file, for its own content. This relates to strategies I'm working on for https://github.com/OBOFoundry/OBOFoundry.github.io/issues/483, but isn't dependent on that.

I guess the question is, are there direct users of those various ontology subsets? If, so there's no reason to stop publishing them, but the content could also be folded into ro.owl, instead of imported, at release time.

**Comment by cmungall** [comment]
We should get on this as soon as we convert to functional syntax. Some make sense to live as imports for the editors version (e,g rohom, which is made automatically) but the others should be merged, with the exception of the imports (and the axioms that should be moved to imports)

**Comment by nlharris** [comment]
Is this something that's still desired?

**Comment by balhoff** [comment]
We're now publishing `ro-base`, which generally satisfies this issue. Although I'm not really sure what the need is for all those different modules.
