### ISSUE TITLE
Relations for connecting processes to time measurements

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#218]
From: https://github.com/EnvironmentOntology/envo/issues/577

Is OWL Time compatible with RO/BFO? What relation should connect a process boundary to a time point, or a process to an owl time interval? Is there a preferred scheme?

**Comment by pbuttigieg** [comment]
Some draft thoughts: 

Every process (p) has at least two [process boundaries](http://purl.obolibrary.org/obo/BFO_0000035), a beginning and an end. 

Consider that a given p [starts with]( http://purl.obolibrary.org/obo/RO_0002224)  and [ends with](http://purl.obolibrary.org/obo/RO_0002230) a [zero-dimensional temporal region](http://purl.obolibrary.org/obo/BFO_0000148). The start time point then [precedes](http://purl.obolibrary.org/obo/BFO_0000063) p and the end time point then [ends](http://purl.obolibrary.org/obo/RO_0002229) p (although "ends" sounds a bit too causal). 

The times themselves could be two cases of IAO's [time measurement datum](http://purl.obolibrary.org/obo/IAO_0000416) that are about the start and end time points. ([This IAO relation](http://purl.obolibrary.org/obo/IAO_0000581) may be of interest, but seems overly specific)

**Comment by cmungall** [comment]
So would the TSMD be connected to the process boundary via IAO's 
is_about?

How would the IAO datum classes related to OWLTime? One view is that we 
ignore OWLTime as it's not OBO formalized but I think it's good to have 
at least a translation layer

**Comment by pbuttigieg** [comment]
>So would the TSMD be connected to the process boundary via IAO's
is_about?

Yes.

>How would the IAO datum classes related to OWLTime? One view is that we
ignore OWLTime as it's not OBO formalized but I think it's good to have
at least a translation layer

I think translating or at least a "hard wired" mapping via an AP is good as there are many users of OWLTime. I think IAO would need to create explicit equivalent classes to OWLTime's content, with the OBO formalisms. Shall we ping them?

**Comment by pbuttigieg** [comment]
> Every process (p) has at least two process boundaries, a beginning and an end.
>
>Consider that a given p starts with and ends with a zero-dimensional temporal region. The start time point then precedes p and the end time point then ends p (although "ends" sounds a bit too causal).

Do we need to express that the process boundary is the ZDTR?

**Comment by dosumis** [comment]
I'd certainly be in favor of making a bridge between the two.   From a quick look, I'd say that the OWL Time classes should be treated as more general than the BFO ones. 

BFO:'process boundary' SubClassOf https://www.w3.org/TR/owl-time/#time:Instant
BFO:'process' SubClassOf https://www.w3.org/TR/owl-time/#time:Interval

OR they could be linked by a 'has temporal extent' relation.

The latest [OWL Time](https://www.w3.org/TR/owl-time) also has Allen interval relations (although unfortunately not the composition table as property chains).  A mapping here might be useful too.

CC @Public-Health-Bioinformatics

**Comment by hoganwr** [comment]
In BFO a process boundary is distinct from a temporal instant.  In particular, BFO calls temporal instants "zero dimensional temporal region".

So it would be more correct to say: 
BFO:'zero-dimensional temporal region' rdfs:subClassOf <https://www.w3.org/TR/owl-time/#time:Instant>

or possibly even: BFO:'zero-dimensional temporal region' owl:equivalentClass <https://www.w3.org/TR/owl-time/#time:Instant>

or more accurately: <http://purl.obolibrary.org/obo/BFO_0000148> owl:equivalentClass <<https://www.w3.org/TR/owl-time/#time:Instant>

**Comment by cmungall** [comment]
Thanks! Where should these axioms live? A bridge ontology distributed with BFO?

Happy to host from an RO purl in the short term, since we're set up for frequently releases

**Comment by nlharris** [comment]
What needs to be done to finish this?

**Comment by nlharris** [comment]
Is this still needed or can we close it?

**Comment by nlharris** [comment]
Closing as won't do; reopen if needed.
