### ISSUE TITLE
Request new relationships used in the antibiotic resistance ontology

### ISSUE THREAD

**Issue by arpcard** [oborel/obo-relations#219]
The antibiotic resistance ontology (ARO) uses a few relationships not in the relations ontology. These are:

**confers_resistance_to**:  A relationship where a class of genes or proteins (e.g. a gene family) confers or contributes to antibiotic resistance to a class of antibiotics 

**confers_resistance_to_drug**: A relationship where a specific gene or protein confers or contributes to antibiotic resistance to a specific antibiotic drug compound

**targeted_by**: A relationship where a class of genes or proteins is targeted by a class of antibiotics or other AMR-related molecules

**targeted_by_drug**: A relationship where a specific gene or protein is targeted by a specific antibiotic drug or other compound

We welcome any feedback or suggested improvements to our definitions.

**Comment by cmungall** [comment]
cc @mbrush @putmantime

**Comment by Public-Health-Bioinformatics** [comment]
Anything more the RO team needs to evaluate integrating these?

**Comment by cmungall** [comment]
targets/targetted-by should be straightforward. 

need more details on the resistance ones. can you give more examples for these, e.g. efflux pumps. would this apply only to genes in organisms for which resistance has evolved, or for any potential mechanism of resistance?

**Comment by arpcard** [comment]
Hi Chris, after some discussion, we'd actually like to modify the resistance relationships to make them clearer:

**confers_resistance_to_drug_class**: A relationship where an AMR Gene Family (e.g. macrolide phosphotransferases) confers or contributes to resistance to an antibiotic drug class (e.g. macrolide antibiotic).

**confers_resistance_to_antibiotic**: A relationship where an antibiotic resistance gene or protein (e.g. mphA) confers or contributes to resistance to a specific antibiotic (e.g. erythromycin). 

@cmungall could you clarify what you mean by "any potential mechanism of resistance"? thanks

**Comment by agmcarthur** [comment]
@cmungall anything we can do at CARD to help integrate these relationships into the RO?

**Comment by leechuck** [comment]
I would like to propose some more extensive definitions for some of these relations:

First, I suggest to use "resistant to" as a primitive relation between instances, first without any reference to some "normal" response to a drug/antibiotic:
Between individuals: x is resistant to y if and only if x is a pathogen and y is a chemical compound, and x does not decrease its fitness when exposed to y.
For classes: the class of pathogens X is resistant to the class of chemicals Y if and only if all instances of X are resistant to some instance of Y. 
Being a "resistance-conferring feature" is a ternary relation between a class of pathogens, chemicals, and the resistance-conferring feature: 
x is a resistance-conferring feature for y with respect to z if and only if (a) x is a part of y, (b) y is resistant to z, (c) x is normally not a part of y and y is normally not resistant to z, and (d) y would not be resistant to z if x would not be a part of y.
The last definition requires the "normally" operator and some form of reference, however.

**Comment by nlharris** [comment]
Does this require more discussion?

**Comment by arpcard** [comment]
Hi @nlharris , I've updated the definitions to incorporate some of the suggestions from @leechuck. The terms we want added to the relations ontology and their definitions can be viewed here: https://card.mcmaster.ca/ontology/40324 (targeted_by, targeted_by_antibiotic, confers_resistance_to_drug_class, and confers_resistance_to_antibiotic). Please let me know if there's more I can do to move this along
