### ISSUE TITLE
Update definitions of 'directly positively regulates' and 'directly negatively regulates'

### ISSUE THREAD

**Issue by vanaukenk** [oborel/obo-relations#221]
The currently proposed GO-CAM guidelines indicate that curators should use the 'directly positively regulates' or 'directly negatively regulates' relations for cases where one activity regulates another either via direct physical interaction or via addition or removal of a small molecule that directly binds to a downstream gene product.

However, the current definitions of RO:0002630 directly negatively regulates and RO:0002629 directly positively regulates only describe regulation via direct physical interaction between the two agents executing the processes.

To include regulation by addition or removal of a small molecular, we will need to add to the definitions.  Here are suggested new definitions:

Process(P1) directly postively regulates process(P2) iff: P1 positively regulates P2 via direct physical interaction between an agent executing P1 (or some part of P1) and an agent executing P2 (or some part of P2), or P1 (or some part of P1)  results in synthesis of a small molecule that directly binds to and activates an agent executing P2  (or some part of P2). For example, if protein A has protein binding activity(P1) that targets protein B and this binding positively regulates the kinase activity (P2) of protein B then P1 directly positively regulates P2.  Alternatively, if protein A has catalytic activity (P1) that synthesizes a small molecule, e.g. cAMP, that binds and positively regulates the catalytic activity (P2) of protein B, then P1 directly positively regulates P2.

Process(P1) directly negatively regulates process(P2) iff: P1 negatively regulates P2 via direct physical interaction between an agent executing P1 (or some part of P1) and an agent executing P2 (or some part of P2), or or P1 (or some part of P1)  results in catabolism of a small molecule that directly binds to and activates an agent executing P2  (or some part of P2). For example, if protein A has protein binding activity(P1) that targets protein B and this binding negatively regulates the kinase activity (P2) of protein B then P1 directly negatively regulates P2.  Alternatively, if protein A has catalytic activity (P1) that catabolizes a small molecule, e.g. acetylcholine, that binds and positively regulates the receptor activity (P2) of protein B, then P1 directly negatively regulates P2.

@cmungall 
@thomaspd
@ukemi
@pgaudet

**Comment by pgaudet** [comment]
Hi @vanaukenk 
These definitions are nice because they are much more precise. I am unclear about he use of 'process'; I guess this is not in the GO meaning, since it looks like Process can be a MF. 

Would it be possible to make it that only a MF can regulate a BP? And if we can, adjust the definitions accordingly ? It would be easier for annotators. 

Thanks, Pascale

**Comment by dosumis** [comment]
> The currently proposed GO-CAM guidelines indicate that curators should use the 'directly positively regulates' or 'directly negatively regulates' relations for cases where one activity regulates another either via direct physical interaction or via addition or removal of a small molecule that directly binds to a downstream gene product.

I thought we'd agreed *not* to go this route.  I personally think it would be a big mistake to do so.  There's a long thread on one of the GO tickets from last year discussing why. 

To recap just a some of the arguments on that thread:

1. Does biosynthesis of a steroid hormone or an endocannabinoid in one cell regulate its receptor in another cell - maybe one in different part of the body?  What about cAMP as an EC ligand in Dicty?  

2. This breaks the logical definitions of X inhibitor/activator classes. I think it would be very unintuitive to call something an enzyme inhibitor if it just affects the concentration of some small molecule inhibitor.

3. Should GO gloss over the control of local concentration of ligands and second messengers when these are often critical regulatory and integrative steps in biological patheways? For example, many things control the local concentration of calcium in the cytosol and many downstream processes are affected by it.  Wouldn't it be better if GO-CAM models allowed for this step to be recorded directly. Something like this.

voltage-gated calcium channel activity --positively regulates^--> (cytoplasmic calcium concentration*) --positively_regulates --> calmodulin activity

\*We already have OBA terms for some of these, but GO-Cam needs a way to record define them compositionally.  This could have the slots: small molecule; location (CC).
^ This use of regulates for regulation of quality is found extensively in GO already.

**Comment by nlharris** [comment]
What is the status of this?

**Comment by vanaukenk** [comment]
@nlharris 
I think this ticket needs to be reviewed in the context of the current GO-CAM modeling guidelines.  
I'll add it to the agenda for the 2020-10-21 GO-CAM call.

**Comment by lpalbou** [comment]
Linking to https://github.com/geneontology/go-shapes/pull/256

**Comment by pgaudet** [comment]
Right - this can be closed maybe ? @vanaukenk

**Comment by vanaukenk** [comment]
@nlharris 
I think we can close this, too.
We've agreed to only use 'positively' or 'negatively' regulates in our GO-CAM models and we are handling small molecule regulators with new, different relations.

**Comment by nlharris** [comment]
Thanks for your help, @vanaukenk! Always nice to do a bit of ticket housecleaning.
