### ISSUE TITLE
"causes or contributes to condition" under rdf:Description ?

### ISSUE THREAD

**Issue by drseb** [oborel/obo-relations#222]
Hi,

not sure this an issue, but maybe someone can help me understand.

Most RO-classes are found as owl:ObjectProperty, e.g.:
```
 <owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/RO_0002448">
        <rdfs:label>activity directly regulates activity of</rdfs:label>
...
```

but I found two that are stored as rdf:Description.

```
<rdf:Description rdf:about="http://purl.obolibrary.org/obo/RO_0001025">
        <rdfs:label xml:lang="en">located in</rdfs:label>
...
<rdf:Description rdf:about="http://purl.obolibrary.org/obo/RO_0003302">
        <rdfs:label xml:lang="en">causes or contributes to condition</rdfs:label>
...
```

How can I interpret this difference? 

p.s.: I am looking at RO_import in upheno.

**Comment by cmungall** [comment]
These are all ObjectProperties in RO, e.g.

`curl -L http://purl.obolibrary.org/obo/RO_0001025`

what is probably happening is some declaration is being lost when making the upheno import. I don't believe it's anything inherent in RO... but probably my fault one way or another

**Comment by balhoff** [comment]
I think this should be fixed by https://github.com/obophenotype/upheno/pull/250
