### ISSUE TITLE
email exchange following Causal relation meeting 2017

### ISSUE THREAD

**Issue by RLovering** [oborel/obo-relations#226]
Dear Kimberly and Chris
 
Pascale and I were in Rome last week at the Curation workshop on molecular and causal interactions discussing causal relations with the several groups submitting protein/molecular interaction data.
 
The aim is to standardise the IDs used to create causal relation annotations, similar to how the IMEx Consortium has guidelines for creating IMEx or MIMIx standard annotations.
 
Pablo has shared with me the draft guidelines IntAct has developed for describing causal relations (attached)
 
As you know Protein2GO provides a graph of the GOrel relations (https://www.ebi.ac.uk/QuickGO-Old/AnnotationExtensionRelations.html) that can be used when annotating directly in the Annotation Extension field.
 
However, it is not clear to me what relations are allowed in GO-CAM, do you have a list of the current GO-CAM relations (ideally with definitions) that you can send to us so that we can look at how well aligned the different existing relation ontologies are?
 
I feel that there is currently a lack of alignment between the Annotation Extension relations being exported from GO-CAM to GPAD files and the relations allowed in the Annotation Extension field when edited directly, but perhaps this is just because I have not seen the full range of relations being exported from GO-CAM.
 
With different groups capturing interactions and implying a causal relationship between gene products/molecules finding an agreed standard approach will improve the interoperability of these resources and enable users to maximise the investment in annotation.
 
It was a general agreement that the use of the relations ontology would be the best approach to ensure standard and consistent guidelines, however the other question that arose was whether there is an option to update RO with any new relations that might be required by the ‘molecular and causal interactions’ group.
 
Finally do you think that GO-CAM users would be interested in following curation guidelines to enable the GO-CAM data to be include in causal relation models?
 
All the best
 
Ruth

**Comment by RLovering** [comment]
From Chris:
First, everyone should use RO here.

The key thing to bear in mind is that we have one set of relations for connecting activities/processes together in GOCAMs. We have another set of relations for connecting physical entities together. GO folks won't have seen this latter set as take an activity centric view in GO, but these relations should be aligned with and have xrefs to MI. They are also formally connected through property chains.

I think throwing extension relations into the mix here has the potential to be confusing. Can we scope this task to aligning the GOCAM relations with physical entity pairwise relations first?

I also recommend looking over my very general intro to reasoning over GOCAM relations from the GO meeting this year:
https://docs.google.com/presentation/d/1aSr1kguPM9im_SHWGVVDe-7T0PNyvJUnXhMZk54on6Y/edit#slide=id.p

I should have also mentioned: like all ontologies in OBO, RO welcomes requests on its issue tracker https://github.com/oborel/obo-relations/

We are also open to pull requests if we have people familiar with Protege and reading the guidelines

**Comment by RLovering** [comment]
Hi Chris

Thanks for explaining this to me.

In addition, please could you direct me to a list of the relations used in GOCAM (with their definitions and use). 

I would  like to confirm that when Noctua models are exported to GPAD and lead to the creation of AE data that the relations included in the AE field align with the existing AE relations (created by adding data directly to the AE field.

Thanks

Ruth

**Comment by nlharris** [comment]
@RLovering do you still need your questions answered?

**Comment by RLovering** [comment]
Hi 
well it would be very nice to have a page that lists all the allowable relations in GO-CAM, when they should be used and how these align (or not) with the relations being used in AEs.  

Plus how AEs are created when GO-CAM models are exported

Probably this information exist but I have missed the notification about it

Thanks
Ruth

**Comment by nlharris** [comment]
Those seem like GO issues rather than tasks for RO, though, wouldn't you say?

**Comment by RLovering** [comment]
well yes that is true - sorry if I put this in the wrong place. I have created a ticket on the helpdesk instead as I couldn't work out where to add this.
https://github.com/geneontology/helpdesk/issues/373
Thanks
Ruth
