### ISSUE TITLE
Definition of 'acts upstream of'

### ISSUE THREAD

**Issue by vanaukenk** [oborel/obo-relations#228]
We are working on the gene product-to-GO term relations and have a question about the formal definition of 'acts upsteam of'.

The current definition, as seen on OLS, is:
c involved in regulation of p if c enables f and f causally upstream of p

https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002263

We were not sure about the 'involved in regulation' part and we were wondering if this new definition would be suitable:

c acts upstream of p1 if c enables some f that is involved in p2 and p2 occurs chronologically before p1, is not part of p1, and affects the execution of p1.  c is a material entity and f, p1, p2 are processes.

Thx.
--Kimberly and Pascale

**Comment by cmungall** [comment]
Looks like a mistake in the def. +1 to your suggestion - want to go ahead and make the change or shall I?

**Comment by vanaukenk** [comment]
@cmungall 
I've not edited RO before, so it might be faster for you to do it.  
That said, though, it might be good to be able to edit in the future, so would the SOP for setting up an RO repo be essentially the same as we did for GO?
