### ISSUE TITLE
Relations for craters and the sites they "contain"

### ISSUE THREAD

**Issue by pbuttigieg** [oborel/obo-relations#229]
Greetings all, 

Over at ENVO, I'd like to express that a crater "contains" a site much in the same way an eye socket contains an eye. 

The site isn't completely contained by the container, so "[located in](http://purl.obolibrary.org/obo/RO_0001025)" doesn't seem right. Also, "[contained in](http://purl.obolibrary.org/obo/RO_0001018)" requires that the immaterial entity is containing the material one, which is the inverse of the case here. 

Any advice?

**Comment by balhoff** [comment]
[overlaps](http://purl.obolibrary.org/obo/RO_0002131)?

**Comment by cmungall** [comment]
I just checked uberon, and we have orbit of skull as being the location_of the eye. This induces an immaterial entity that bulges out somewhat from the plane formed by the rim of the socket (at least is some species).

I would say it is up to the relevant structural ontology to define which space a structure "owns" using whatever authority they have. For anatomy it may be acceptable to have bulges. For craters, it may make less sense.

You could of course name a new immaterial entity that extends upwards some arbitrary distance. This may potentially make some sense for geographic entities (thinking of looking down on a map) but I'm always wary of naming new immaterial entities that don't have any cognate to usage by people in the domain.

Overlaps is definitely valid. It's not clear that defining either new entities or new relations will give any additional inferential power or afford users more precise queries.

**Comment by cmungall** [comment]
are they linked by processes in any way? E.g formation, causal disposition to affect how one forms from another?

**Comment by pbuttigieg** [comment]
Thanks @balhoff. Considered that, but this site doesn't really overlap the crater, more the space in the crater. 

Perhaps the label is off, I mean the site bounded by a depression and a fiat boundary which separates the space in the depression from that outside of (above the shoulders of) the depression. Akin to site inside a teacup.

Very scientific diagram below, with red bounding the site I'm talking about:
![image](https://user-images.githubusercontent.com/2276146/39062612-604bad50-44c8-11e8-8dbd-e14a87116505.png)

**Comment by balhoff** [comment]
Aha, I misinterpreted "isn't completely contained by".

**Comment by pbuttigieg** [comment]
Thanks @cmungall 

> I just checked uberon, and we have orbit of skull as being the location_of the eye. This induces an immaterial entity that bulges out somewhat from the plane formed by the rim of the socket (at least is some species).

That sounds like the fiat boundary understood to exist by convention in the field. So here the orbit includes the eye entirely it seems. Again, the material and immaterial parts are switched in the crater example (a site bounded by the crater-[air, space, etc] interface plus a fiat boundary extending from the edges of the depression), which is causing issues. 

> I would say it is up to the relevant structural ontology to define which space a structure "owns" using whatever authority they have. For anatomy it may be acceptable to have bulges. For craters, it may make less sense.
>
> You could of course name a new immaterial entity that extends upwards some arbitrary distance. This may potentially make some sense for geographic entities (thinking of looking down on a map) but I'm always wary of naming new immaterial entities that don't have any cognate to usage by people in the domain.

Agreed - I don't want to create unintuitive immaterial entities or boundaries. 


> Overlaps is definitely valid. It's not clear that defining either new entities or new relations will give any additional inferential power or afford users more precise queries.

I could work with overlaps, but I do think that more precision would be useful. Using the teacup analogy above, I want to talk about the region that contains tea, not the region which also overlaps the cup itself.

**Comment by pbuttigieg** [comment]
@cmungall 
> are they linked by processes in any way? E.g formation, causal disposition to affect how one forms from another?

Yes, in the sense that the site we're dealing with is formed as a result of the same processes that form the depression (just like the space in the teacup formed when the cup is molded).

**Comment by ukemi** [comment]
luminal_space_of  ?

**Comment by pbuttigieg** [comment]
@cmungall @balhoff @ukemi

@ukemi - that's close! Lumens are typically tubular, so this won't be exactly right for craters and the like. I also think it's tied to biological entities, but it need not be (it would work for tunnels and boreholes). The issue of part hood comes up again, too.

I think the key to  may be boundaries. 
The site is bounded by a 2D boundary along the indentation's surface and a 2D fiat boundary extending over the indentation at the same isocline as the surrounding, non-indented surface. 

Perhaps we can work with the 'surrounded by' semantics, assuming they can work for material and immaterial entities (seems they can).

For a while, ENVO has had "[partially_surrounded_by](http://purl.obolibrary.org/obo/ENVO_01001307)". If we can push this to RO, then we can say that there is a site that is partially surrounded by the crater.

**Comment by cmungall** [comment]
Ah yes, overlaps is not correct for the crater itself. We could have a new relation `overlaps_location_of <-> overlaps o contained_in`

@ukemi:
[RO_0002572](http://purl.obolibrary.org/obo/RO_0002572) ! luminal space of 
Yes, this works for defining the bit insider Pier's red lines. We could have an overlaps_luminal_space_of also

But it sounds like this is not strong enough to capture some other essence of the relationship. Perhaps the crater where a glacier formation process occurrs, and the glacier is the output of the glacier formation process. @ukemi can you think of any developmental biology analogs?

**Comment by pbuttigieg** [comment]
@cmungall 
@ukemi:
> RO_0002572 ! luminal space of
Yes, this works for defining the bit insider Pier's red lines. We could have an overlaps_luminal_space_of also

Crater's aren't tubular though, and this relation suggests parthood, which isn't quite right.

>Perhaps the crater where a glacier formation process occurrs, and the glacier is the output of the glacier formation process. @ukemi can you think of any developmental biology analogs?

Yup, this is about a `crater glacier`, which is contained in the site I've sketched out above.

**Comment by cmungall** [comment]
I agree about shifting http://purl.obolibrary.org/obo/ENVO_01001307 to RO. If we can decide on what constitutes a non-trivial portion.

re: your def

[this is getting more towards the envo modeling...]

you know how I get about unions, I'm always suspicious of them. Is your list complete? If the crater is buried in rubble is not still a crater? I suppose it's still surrounded by gas in that air is in the spaces between the rocks.

I posit that the class we're implicitly looking for here is a region with basal boundary [ENVO:01000324](http://purl.obolibrary.org/obo/ENVO_01000324) ! planetary surface. I think we could name this as a class. This has the nice property in it's explicit that the zone crosses two major subdivisions of space.

**Comment by cmungall** [comment]
I just realized my suggestion doesn't work, as surroundment (partial or complete) implies adjacency, and our zone here intersects the super-surface zone rather than is surrounded by it.

I also realize I may have mistaken the original Q. I jumped to the conclusion that the challenge was that the glacier sometimes protruded outside the red boundary, like the eyes of some vertebrates protruding from the surface defined by the rim of their eye sockets.

If it's the case the glacier is within it (is it always?), I think it's much simpler.

I think a simple [located in](http://purl.obolibrary.org/obo/RO_0001025) is fine. This is analogous to tubes, grooves and the like in anatomy ontologies. We generally treat these as the mereological sum of the space plus the walls. Unfortunately the extent of the space is often not defined, but it's generally taken to be something convex-hully. For example, I swallow some food, it is located in my mouth, then in my esophagus, my stomach, etc.

**Comment by pbuttigieg** [comment]
Cross-reference #308

**Comment by pbuttigieg** [comment]
>you know how I get about unions, I'm always suspicious of them. Is your list complete? If the crater is buried in rubble is not still a crater? I suppose it's still surrounded by gas in that air is in the spaces between the rocks.

Good point, completeness would come with more examples.

> I posit that the class we're implicitly looking for here is a region with basal boundary ENVO:01000324 ! planetary surface. I think we could name this as a class. This has the nice property in it's explicit that the zone crosses two major subdivisions of space.

As long as basal also means lateral (the "sides" of a crater), which it may in this case.

**Comment by nlharris** [comment]
@pbuttigieg can this issue be closed, or are you waiting for anything further?

**Comment by nlharris** [comment]
See also #38

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
