### ISSUE TITLE
New relation request: has substrate

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#230]
proposal outlined here
https://docs.google.com/document/d/1QMhs9J-P_q3o_rDh-IX4ZEnz0PnXrzLRVkI3vvz8NEQ/edit

**Comment by phismith** [comment]
3 Introduce new sub-relation has-substrate

"p has substrate c iff p has-input c, and..."
Characteristics: Functional (a process cannot have two substrates)

Suggestion:

"p has substrate c 
= def. 
#p realizes function f at t & f has material basis c at t

**Comment by dosumis** [comment]
> Characteristics: Functional (a process cannot have two substrates)

Not sure about this. Where does it come from?

My favoured definition of has_substrate (not completely formalised).

p has_substrate c iff p is a catalytic process and c is transformed or destroyed as a result of p

**Comment by cmungall** [comment]
On 13 Jul 2018, at 4:20, David Osumi-Sutherland wrote:

>> Characteristics: Functional (a process cannot have two substrates)
>
> Not sure about this. Where does it come from?

I think it has some favorable characteristics but could go either way

If we drop this, does it propagate to parts? E.g. if C is a complex and 
a substrate, are the protein parts substrates, sometimes/always?

> My favoured definition of has_substrate (not completely formalised).
>
> p has_substrate c iff p is a catalytic process and c is transformed or 
> destroyed as a result of p

The disjointness between MF and BF is a bit awkward here, if we want 
this to be used e.g. catabolic processes and kinase activity

**Comment by cmungall** [comment]
Was responding to @dosumis without seeing @phismith's comment.

Barry suggests:

"p has substrate c =def p realizes function f at t & f has material basis c at t"

From my reading of section 3.7.8 in BFO2 reference this doesn't correspond to the intent of this relation, but it may help to have function elucidations in 3.7.8 as well as 'plain' dispositions.

Note: I have an outstanding ticket seeking clarification on has-material-basis on the BFO tracker: https://github.com/BFO-ontology/BFO/issues/113 (was sidetracked a bit by discussion of fields, which is a different matter)

**Comment by cmungall** [comment]
I asked for an elucidation here: https://github.com/BFO-ontology/BFO/issues/219 - I think this one is for you @phismith

**Comment by LEHunter** [comment]
With regard to David O-S's narrowness concern, that  "p has_substrate c iff p is a catalytic process and c is transformed or destroyed as a result of p” excludes entities transported, one could either define a separate relation (has_cargo?) or refine the definition to include "...and c is transformed, translocated, or destroyed as a result..."  If the latter, one could define sub-relations has_cargo and has_reaction_substrate if that would be useful.

**Comment by LEHunter** [comment]
With regard to David O-S's broadness concern, that both the kinase and the ATP are substrates of a protein kinase reaction, I agree that this doesn't bother me much.  However, if one wanted to hew more closely to biologists' common usage, one could create a defined class of either ubiquitous_substrates (perhaps a cardinality restriction) or energy_contributing_substrates and exclude them from the range of the relationship.  Seems unwieldy and probably unnecessary, but could be done.

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
