### ISSUE TITLE
Change RO license to CC-0

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#238]
Current license is CC-BY, I propose that we either

 1. Completely switch to CC-0 (my preference)
 2. Define an CC-0 axioms subset that can be  licensed under CC-0

Let's first take a quick poll with most frequent committers on thoughts on 1 vs 2, then look at a formal license transition: @jamesaoverton @dosumis @diatomsRcool @mbrush 

See https://github.com/OBOFoundry/OBOFoundry.github.io/issues/285

**Comment by cmungall** [comment]
PR ready to go. We can discuss this at the meeting

**Comment by jamesaoverton** [comment]
I'm fine with both. I prefer 1 because it's simpler.

**Comment by dosumis** [comment]
I agree with switching to CC-0.

(although wasn't the original discussion around CC-BY based on the idea that using PURLs was sufficient attribution?)

**Comment by cmungall** [comment]
There was a discussion here: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/285

**Comment by cmungall** [comment]
Final step, thanks @balhoff: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1077
