### ISSUE TITLE
Revise ROCore_Continuants.jpg?

### ISSUE THREAD

**Issue by msinclair2** [oborel/obo-relations#241]
Does the diagram [ROCore_Continuants.jpg](https://github.com/oborel/obo-relations/blob/master/docs/ROCore_Continuants.jpg) violate the rule of no higher order dependence in BFO as displayed in Figure 6 of the spec?  Personally, I view concretization as a kind of dependence.  I think the triad of GDC, SDC, and IDC should resemble Figure 7, right, with b = GDC, c = SDC, and d = IC.

**Comment by cmungall** [comment]
Not completely following, Fig6 is about s-depends on, so this does not apply to concretization?

```
3.8.1	Relation of concretization
ELUCIDATION: b concretizes c at t means: 
b is a specifically dependent continuant 
& c is a generically dependent continuant 
& for some independent continuant that is not a spatial region d, 
b s-depends_on d at t 
& c g-depends on d at t 
& if c migrates from bearer d to another bearer e than a copy of b will be created in e. [075-002]
```

**Comment by msinclair2** [comment]
You're right, strictly speaking.  My personal view is that the Figure (and concept of no higher order dependence) applies to all dependence, and I view concretization as a kind of dependence.

Be that as it may, the diagram still does not accurately depict the elucidation in 3.8.1.  If one looks for "c g-depends_on d" in the diagram, one does not find it.

**Comment by msinclair2** [comment]
How about the attached alternative?
![rocore_continuants_alt](https://user-images.githubusercontent.com/20292982/43243888-e446a2ca-9065-11e8-8aeb-fcc2c8cf6cf2.jpg)

**Comment by cmungall** [comment]
I see. Should we have some visual convention for "shortcut" relations, e.g. dashed lines (of course, we can still directly assert GDO, but from a BFO perspective this is a shortcut)

See also https://github.com/oborel/obo-relations/pull/233#issuecomment-408154269

**Comment by msinclair2** [comment]
We're (@mikebada) building [MSO](https://github.com/The-Sequence-Ontology/MSO) on the assumption there is GDO.

**Comment by msinclair2** [comment]
Sorry this took me so long.  I made the shortcuts dashed lines and incorporated the new "is carrer of" relation.

![rocore_continuants-01](https://user-images.githubusercontent.com/20292982/44885772-f9688200-ac7f-11e8-9537-1b7843ba7a30.png)

**Comment by jamesaoverton** [comment]
This revised diagram communicates the relations clearly.

When I made the diagrams, my goal wasn't to include all the relations, just the overall "shape". So I prefer the original without this addition, but I don't have a strong objection to this change.

**Comment by msinclair2** [comment]
@jamesaoverton I understand your preference.  Actually, it appears that your diagram is more correct.  @phismith made clear in his [preview](https://github.com/oborel/obo-relations/pull/233#issuecomment-416252522) of the new elucidation of generically depends on that a generically dependent continuant must be concretized in order to exist. I suppose I was a bit biased because of how important the generically depends on (shortcut) relation was in my current work on MSO/SO. So I now prefer the original diagram.

**Comment by mikebada** [comment]
@msinclair2 If you want to enforce that a GDC must be concretized, we could define 'generically depends on' as the property chain 'is concretized as' o 'inheres in'.

**Comment by msinclair2** [comment]
@mikebada I incorporated the property chain in the pull request of #233 at popular request.

**Comment by nlharris** [comment]
What is the status of this?
