### ISSUE TITLE
Self refrential 

### ISSUE THREAD

**Issue by TomConlin** [oborel/obo-relations#246]
Noting that the RO is defining itself, in terms of itself.

Not the end of the world, 
but when I see circular definitions in writing
I steeply discount the credibility of the authors.
 

     37 <http://purl.obolibrary.org/obo/RO_0001900>
      1 <http://purl.obolibrary.org/obo/RO_0002423>
      1 <http://purl.obolibrary.org/obo/RO_0002560>
      4 <http://purl.obolibrary.org/obo/RO_0002561>
      6 <http://purl.obolibrary.org/obo/RO_0002575>
      2 <http://purl.obolibrary.org/obo/RO_0002579>
      3 <http://purl.obolibrary.org/obo/RO_0002581>
      5 <http://purl.obolibrary.org/obo/RO_0002582>
      7 <http://purl.obolibrary.org/obo/RO_0004049>
      7 <http://purl.obolibrary.org/obo/RO_0004050>

**Comment by cmungall** [comment]
On 5 Aug 2018, at 12:15, Tom Conlin wrote:

> Noting that the RO is defining itself, in terms of itself.
>
> Not the end of the world,
> but when I see circular definitions in writing
> I steeply discount the credibility of the authors.
>
>
>      37 <http://purl.obolibrary.org/obo/RO_0001900>

Can you suggest changes in a PR?

This one is fairly trivial

It's an AP that connects an OP to a text string describing an 
interpretation. The AP could be prefixed wth 'has '

**Comment by cmungall** [comment]
I'm not sure I know what the action is here

I don't see a self-referentiality issue with the next one
http://purl.obolibrary.org/obo/RO_0002423

or the next one?
http://purl.obolibrary.org/obo/RO_0002560

**Comment by nlharris** [comment]
What's the status of this?
