### ISSUE TITLE
Discussion: Should RO form a complete subsumption lattice?

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#250]
This was proposed by Larry on a call.

The underlying assumption is that every OP should be arranged in a rich subsumption lattice (may be mis-phrasing).

I would question this. To be more specific, of course, if a subPropertyOf axiom is true, then it should be present in the release. But it's not the case that we would expect to see a rich deep hierarchy in all cases.

As case in point I present the Allen Interval Algebra, a rigorous ontology of temporal relations with precise definitions. The subsumption lattice of Allen is completely flat, every relation is disjoint, and there are no subPropertyOf relations between the members.

Of course, it is possible to define groupings of allen relations, and these naturally form a hierarchy. An example of some of these can be found in [this paper describing sequence relationships](http://biorxiv.org/content/early/2014/06/27/006650.abstract) (see table 2). But the number of possible grouping relations is large.

In some cases we may want to make groupings. For example, the causal relations are defined using a simple set of combinations of some base properties, and we name useful grouping relations for cases where a curator may not have sufficient knowledge. See https://github.com/oborel/obo-relations/wiki/causal-relations

So: there is no a-priori reason to _expect_ parts of RO to necessarily have a complete subsumption lattice. In many cases it is _pragmatic_ to have grouping classes. But to see some object properties without a parent is not _necessarily_ a problem.

**Comment by dosumis** [comment]
Strongly agree with Chris.  I'd prefer to limit logical assertions about relationships between properties to ones that we are confident of - with priority given to those that are useful for logical inference in known use-cases.  If the aim is to help NLP, then should we be looking at the non-logical axioms instead (Improving synonyms and their annotation)?

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
