### ISSUE TITLE
Transitivity of part-of

### ISSUE THREAD

**Issue by phismith** [oborel/obo-relations#253]
Another topic discussed at the ICBO meeting was the transitivity of part-of, and possible failures thereof as a result of the fact that one entity may be part of a second entity only for a certain part of the history of that second entity.

An example of such failure proposed by Alan Ruttenberg is:

phagosome part of macrophage 
macrophage part of bone marrow
but not: phagosome part of bone marrow

Another example (not from Alan) is:

11th Hussars (Prince Albert's Own) part of King's Royal Hussars 
King's Royal Hussars part of 12th Armoured Infantry Brigade
but not King's Royal Hussars part of 12th Armoured Infantry Brigade

This is because the King's Royal Hussars were disbanded before the 12th Armoured Infantry Brigade was formed.

Although such examples are rare, there are areas (especially development) where the logic of part-of will need to be carefully tailored to fit. Note that such examples only arise in the realm of continuants. Part of is trivially transitive for occurrents, since occurrents do not gain and lose parts.
BS

**Comment by phismith** [comment]
Please note the second example should read:

11th Hussars (Prince Albert's Own) part of King's Royal Hussars
King's Royal Hussars part of 12th Armoured Infantry Brigade
but not 11th Hussars (Prince Albert's Own) part of 12th Armoured Infantry Brigade

**Comment by cmungall** [comment]
I think you need more elucidation. You left out a t argument in your examples. Is this intended to be implicit or are you assuming a particular binarization? Otherwise provide a definition for transitivity for ternary relations

**Comment by phismith** [comment]
I deliberately left out the *t* argument -- thus you can see my examples as
illustrating two sorts of failure of transitivity for continuant part of *as
a binary relation* between, respectively

instances (Hussars)
universals (macrophage)

Matters are much clearer if you insert the t argument, of course, but that
is hard to do (as we know) if one is restricted to binary relations. This
is the problem Alan has, I believe, solved.

The Temporally Qualified Continuants approach of Ludger Jansen *et al.*
faces the objection we discussed on the phone, namely that we need far too
many terms to refer to all the TQCs needed e.g. for complex organisms
developing all their various bits at different times. Also it seems not yet
to be entirely clear that it works in OWL.

My favored solution is to define (for classes A and B and instances x, y)

[*] A continuant part of B =def all instances of A are
continuant-part-of-at-all-times some instance of B

where x continuant-part-of-at-all-times y means at all times during the
life of x

We would then provide warnings for users e.g. in areas of development where
there are known cases (if there are any known cases -- to me this is still
not clear) where a biologist might want to say, at the class level, that A
continuant part of B, but where the reading in [*] fails.
Barry

**Comment by ramonawalls** [comment]
This is a  common case in biodiversity where we have specimens that were once part of an organism. We want to be able to make inferences about a whole plant of which a herbarium specimen (which is usually a branch) was once part, based on some observation of the now disembodied branch. 

One possible solution:

'material sampling process' has input 'whole plant' (instance of material entity) and has output 'herbarium specimen' (instance of material sample)

implies 

'herbarium specimen' was part of 'whole plant'

where

B was part of A =def B is output of some 'material sampling process' that has input A

'was part of' could also be called 'sampled from' or 'derived from' or similar.


There are also leaves that are part of the branch that was sampled, so we want transitivity from that part of relation to be used to infer that the leaf was part of the whole plant as well:

C part of B  and B was part of A > C was part of A

**Comment by cmungall** [comment]
@ramonawalls have a look at the relations used for developmental lineage: http://purl.obolibrary.org/obo/RO_0002258

even though obviously you are not talking about development, the same patterns could be reused for any derivational relation. There are analogous property chains to the one you proposed.

**Comment by ramonawalls** [comment]
Thanks, @cmungall, very helpful. Still, having a transitive part of relation in RO is kind of key!

I'll start a separate issue to request the specific relations we need.

**Comment by cmungall** [comment]
Just to be clear, part-of is declared Transitive in RO.

**Comment by cmungall** [comment]
It's not clear what the action required on this ticket is - can we close it?

**Comment by nlharris** [comment]
If no one can clarify what the action is, then yes, let's close it.
