### ISSUE TITLE
Create report of usage of RO relations across OBO

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#264]

**Comment by cmungall** [comment]
In progress, but this is what it looks like (number is number of distinct ontologies - may be overcount due to MIREOT)

|Onts|Rel|Rel name|
|---|---|---|
|105|http://purl.obolibrary.org/obo/BFO_0000051|has part|
|100|http://purl.obolibrary.org/obo/BFO_0000050|part of|
|50|http://purl.obolibrary.org/obo/RO_0000052|inheres in|
|48|http://purl.obolibrary.org/obo/RO_0001025|located in|
|47|http://purl.obolibrary.org/obo/BFO_0000054|realized in|
|47|http://purl.obolibrary.org/obo/RO_0000057|has participant|
|45|http://purl.obolibrary.org/obo/RO_0000087|has role|
|44|http://purl.obolibrary.org/obo/RO_0000053|bearer of|
|42|http://purl.obolibrary.org/obo/RO_0000056|participates in|
|41|http://purl.obolibrary.org/obo/BFO_0000055|realizes|
|39|http://purl.obolibrary.org/obo/RO_0002202|develops from|
|35|http://purl.obolibrary.org/obo/BFO_0000062|preceded by|
|33|http://purl.obolibrary.org/obo/RO_0000059|concretizes|
|32|http://purl.obolibrary.org/obo/RO_0002087|immediately preceded by|
|30|http://purl.obolibrary.org/obo/RO_0002215|capable of|
|28|http://purl.obolibrary.org/obo/BFO_0000066|occurs in|
|27|http://purl.obolibrary.org/obo/RO_0002351|has member|
|25|http://purl.obolibrary.org/obo/RO_0000086|has quality|
|25|http://purl.obolibrary.org/obo/RO_0001000|derives from|
|25|http://purl.obolibrary.org/obo/RO_0002220|adjacent to|
|22|http://purl.obolibrary.org/obo/BFO_0000063|precedes|
|21|http://purl.obolibrary.org/obo/RO_0002473|composed primarily of|
|21|http://purl.obolibrary.org/obo/RO_0002219|surrounded by|
|20|http://purl.obolibrary.org/obo/RO_0002223|starts|
|19|http://purl.obolibrary.org/obo/RO_0001015|location of|
|18|http://purl.obolibrary.org/obo/RO_0000085|has function|
|17|http://purl.obolibrary.org/obo/RO_0002150|continuous with|
|16|http://purl.obolibrary.org/obo/RO_0003001|produced by|
|16|http://purl.obolibrary.org/obo/RO_0002234|has output|
|16|http://purl.obolibrary.org/obo/RO_0002218|has active participant|
|16|http://purl.obolibrary.org/obo/RO_0003000|produces|
|16|http://purl.obolibrary.org/obo/RO_0002211|regulates|
|15|http://purl.obolibrary.org/obo/RO_0002229|ends|
|15|http://purl.obolibrary.org/obo/RO_0002207|directly develops from|
|15|http://purl.obolibrary.org/obo/RO_0002566|causally influences|
|15|http://purl.obolibrary.org/obo/RO_0002418|causally upstream of or within|
|14|http://purl.obolibrary.org/obo/RO_0002488|existence starts during|
|14|http://purl.obolibrary.org/obo/RO_0002495|immediate transformation of|
|14|http://purl.obolibrary.org/obo/RO_0002496|existence starts during or after|
|14|http://purl.obolibrary.org/obo/RO_0002131|overlaps|
|13|http://purl.obolibrary.org/obo/RO_0002497|existence ends during or before|
|13|http://purl.obolibrary.org/obo/RO_0002221|surrounds|
|13|http://purl.obolibrary.org/obo/RO_0002176|connects|
|13|http://purl.obolibrary.org/obo/RO_0000058|is concretized as|
|13|http://purl.obolibrary.org/obo/RO_0002212|negatively regulates|
|13|http://purl.obolibrary.org/obo/RO_0002254|has developmental contribution from|
|13|http://purl.obolibrary.org/obo/RO_0002224|starts with|
|13|http://purl.obolibrary.org/obo/RO_0002387|has potential to develop into|
|12|http://purl.obolibrary.org/obo/RO_0002492|existence ends during|
|12|http://purl.obolibrary.org/obo/RO_0002489|existence starts with|
|12|http://purl.obolibrary.org/obo/RO_0002230|ends with|
|12|http://purl.obolibrary.org/obo/RO_0002353|output of|
|12|http://purl.obolibrary.org/obo/RO_0002493|existence ends with|
|12|http://purl.obolibrary.org/obo/RO_0002002|has 2D boundary|
|12|http://purl.obolibrary.org/obo/RO_0002007|bounding layer of|
|11|http://purl.obolibrary.org/obo/RO_0000081|role of|
|11|http://purl.obolibrary.org/obo/RO_0002494|transformation of|
|11|http://purl.obolibrary.org/obo/RO_0002233|has input|
|11|http://purl.obolibrary.org/obo/RO_0002572|luminal space of|
|10|http://purl.obolibrary.org/obo/RO_0002285|developmentally replaces|
|10|http://purl.obolibrary.org/obo/RO_0002551|has skeleton|
|10|http://purl.obolibrary.org/obo/RO_0002503|towards|
|10|http://purl.obolibrary.org/obo/RO_0002350|member of|
|10|http://purl.obolibrary.org/obo/RO_0002256|developmentally induced by|
|10|http://purl.obolibrary.org/obo/RO_0002180|has component|
|10|http://purl.obolibrary.org/obo/RO_0002433|contributes to morphology of|
|10|http://purl.obolibrary.org/obo/RO_0000091|has disposition|
|9|http://purl.obolibrary.org/obo/RO_0002385|has potential to developmentally contribute to|
|9|http://purl.obolibrary.org/obo/RO_0002508|determines|
|9|http://purl.obolibrary.org/obo/RO_0002178|supplies|
|9|http://purl.obolibrary.org/obo/RO_0002160|only in taxon|
|9|http://purl.obolibrary.org/obo/RO_0002576|skeleton of|
|9|http://purl.obolibrary.org/obo/RO_0002104|has plasma membrane part|
|9|http://purl.obolibrary.org/obo/RO_0002507|determined by|
|8|http://purl.obolibrary.org/obo/RO_0002354|formed as result of|
|8|http://purl.obolibrary.org/obo/RO_0002314|inheres in part of|
|8|http://purl.obolibrary.org/obo/RO_0000079|function of|
|8|http://purl.obolibrary.org/obo/RO_0002203|develops into|
|8|http://purl.obolibrary.org/obo/RO_0002134|innervates|
|8|http://purl.obolibrary.org/obo/RO_0002481|is kinase activity|
|8|http://purl.obolibrary.org/obo/RO_0002465|is symbiosis|
|8|http://purl.obolibrary.org/obo/RO_0002170|connected to|
|7|http://purl.obolibrary.org/obo/RO_0002213|positively regulates|
|7|http://purl.obolibrary.org/obo/RO_0002297|results in formation of|
|7|http://purl.obolibrary.org/obo/RO_0002376|tributary of|
|7|http://purl.obolibrary.org/obo/RO_0002371|attached to|
|7|http://purl.obolibrary.org/obo/RO_0002092|happens during|
|7|http://purl.obolibrary.org/obo/RO_0002380|branching part of|
|6|http://purl.obolibrary.org/obo/RO_0002524|has subsequence|
|6|http://purl.obolibrary.org/obo/RO_0002005|innervated_by|
|6|http://purl.obolibrary.org/obo/RO_0002573|has modifier|
|6|http://purl.obolibrary.org/obo/RO_0002225|develops from part of|
|5|http://purl.obolibrary.org/obo/RO_0002468|is parasitism|
|5|http://purl.obolibrary.org/obo/RO_0002467|is mutualism|
|5|http://purl.obolibrary.org/obo/RO_0002179|drains|
|5|http://purl.obolibrary.org/obo/RO_0002482|is ubiquitination|
|5|http://purl.obolibrary.org/obo/RO_0001019|contains|
|5|http://purl.obolibrary.org/obo/RO_0002466|is commensalism|
|5|http://purl.obolibrary.org/obo/BFO_0000067|contains process|
|5|http://purl.obolibrary.org/obo/RO_0002226|develops in|
|4|http://purl.obolibrary.org/obo/RO_0002411|causally upstream of|
|4|http://purl.obolibrary.org/obo/RO_0002162|in taxon|
|4|http://purl.obolibrary.org/obo/RO_0002093|ends during|
|4|http://purl.obolibrary.org/obo/RO_0002217|actively participates in|
|3|http://purl.obolibrary.org/obo/RO_0002200|has phenotype|
|3|http://purl.obolibrary.org/obo/RO_0002372|has muscle origin|
|3|http://purl.obolibrary.org/obo/BFO_0000060|obsolete preceded by|
|3|http://purl.obolibrary.org/obo/RO_0002377|distributary of|
|3|http://purl.obolibrary.org/obo/RO_0002292|expresses|
|3|http://purl.obolibrary.org/obo/RO_0002571|lumen of|
|3|http://purl.obolibrary.org/obo/RO_0002373|has muscle insertion|
|3|http://purl.obolibrary.org/obo/RO_0002091|starts during|
|3|http://purl.obolibrary.org/obo/RO_0002608|process has causal agent|
|3|http://purl.obolibrary.org/obo/RO_0002084|during which ends|
|3|http://purl.obolibrary.org/obo/RO_0002568|has muscle antagonist|
|3|http://purl.obolibrary.org/obo/RO_0002451|transmitted by|
|3|http://purl.obolibrary.org/obo/RO_0002216|capable of part of|
|3|http://purl.obolibrary.org/obo/RO_0002303|has habitat|
|3|http://purl.obolibrary.org/obo/RO_0002374|derived from ancestral fusion of|
|3|http://purl.obolibrary.org/obo/RO_0002427|causally downstream of or within|
|3|http://purl.obolibrary.org/obo/RO_0002352|input of|
|3|http://purl.obolibrary.org/obo/RO_0002404|causally downstream of|
|3|http://purl.obolibrary.org/obo/RO_0009001|has substance added|
|3|http://purl.obolibrary.org/obo/RO_0002120|synapsed to|
|3|http://purl.obolibrary.org/obo/RO_0002151|partially overlaps|
|3|http://purl.obolibrary.org/obo/RO_0002177|attached to part of|
|3|http://purl.obolibrary.org/obo/RO_0002090|immediately precedes|
|2|http://purl.obolibrary.org/obo/RO_0002509|determined by part of|
|2|http://purl.obolibrary.org/obo/RO_0002088|during which starts|
|2|http://purl.obolibrary.org/obo/RO_0002244|related via exposure to|
|2|http://purl.obolibrary.org/obo/RO_0002130|has synaptic terminal in|
|2|http://purl.obolibrary.org/obo/RO_0000080|quality of|
|2|http://purl.obolibrary.org/obo/RO_0002082|simultaneous with|
|2|http://purl.obolibrary.org/obo/RO_0001018|contained in|
|2|http://purl.obolibrary.org/obo/RO_0002479|has part that occurs in|
|2|http://purl.obolibrary.org/obo/RO_0002232|has end location|
|2|http://purl.obolibrary.org/obo/RO_0002296|results in development of|
|2|http://purl.obolibrary.org/obo/RO_0002100|has soma location|
|2|http://purl.obolibrary.org/obo/RO_0002502|depends on|
|2|http://purl.obolibrary.org/obo/RO_0001001|derives into|
|2|http://purl.obolibrary.org/obo/RO_0002159|serially homologous to|
|1|http://purl.obolibrary.org/obo/RO_0002106|synapsed_via_type_Is_bouton_to|
|1|http://purl.obolibrary.org/obo/RO_0002434|interacts with|
|1|http://purl.obolibrary.org/obo/RO_0009003|immersed in|
|1|http://purl.obolibrary.org/obo/RO_0004029|disease has feature|
|1|http://purl.obolibrary.org/obo/RO_0002477|child nucleus of in hermaphrodite|
|1|http://purl.obolibrary.org/obo/RO_0002114|synapsed_via_type_III_bouton_to|
|1|http://purl.obolibrary.org/obo/RO_0004028|realized in response to stimulus|
|1|http://purl.obolibrary.org/obo/RO_0002003|electrically_synapsed_to|
|1|http://purl.obolibrary.org/obo/RO_0009501|realized in response to|
|1|http://purl.obolibrary.org/obo/RO_0001022|has allergic trigger|
|1|http://purl.obolibrary.org/obo/RO_0002006|has synaptic terminal of|
|1|http://purl.obolibrary.org/obo/RO_0002583|existence starts at point|
|1|http://purl.obolibrary.org/obo/RO_0002491|existence starts and ends during|
|1|http://purl.obolibrary.org/obo/RO_0002201|phenotype of|
|1|http://purl.obolibrary.org/obo/RO_0002101|fasciculates with|
|1|http://purl.obolibrary.org/obo/RO_0002593|existence ends at point|
|1|http://purl.obolibrary.org/obo/RO_0002525|is subsequence of|
|1|http://purl.obolibrary.org/obo/RO_0002204|gene product of|
|1|http://purl.obolibrary.org/obo/RO_0002105|synapsed_via_type_Ib_bouton_to|
|1|http://purl.obolibrary.org/obo/RO_0002113|has presynaptic terminal in|
|1|http://purl.obolibrary.org/obo/RO_0004021|disease has basis in disruption of|
|1|http://purl.obolibrary.org/obo/RO_0004027|disease has inflammation site|
|1|http://purl.obolibrary.org/obo/RO_0004025|disease causes dysfunction of|
|1|http://purl.obolibrary.org/obo/RO_0002609|obsolete related via dependence to|
|1|http://purl.obolibrary.org/obo/RO_0004024|disease causes disruption of|
|1|http://purl.obolibrary.org/obo/RO_0003304|contributes to condition|
|1|http://purl.obolibrary.org/obo/RO_0002110|has postsynaptic terminal in|
|1|http://purl.obolibrary.org/obo/RO_0004020|disease has basis in dysfunction of|
|1|http://purl.obolibrary.org/obo/RO_0004030|disease arises from structure|
|1|http://purl.obolibrary.org/obo/RO_0002001|aligned with|
|1|http://purl.obolibrary.org/obo/RO_0002490|existence overlaps|
|1|http://purl.obolibrary.org/obo/RO_0002478|child nucleus of in male|
|1|http://purl.obolibrary.org/obo/RO_0004022|disease has basis in feature|
|1|http://purl.obolibrary.org/obo/RO_0004019|disease has basis in|
|1|http://purl.obolibrary.org/obo/RO_0002103|synapsed by|
|1|http://purl.obolibrary.org/obo/RO_0002083|before|
|1|http://purl.obolibrary.org/obo/RO_0002107|synapsed_via_type_II_bouton_to|
|1|http://purl.obolibrary.org/obo/RO_0002331|involved in|
|1|http://purl.obolibrary.org/obo/RO_0002476|child nucleus of|
|1|http://purl.obolibrary.org/obo/RO_0004026|disease has location|
|1|http://purl.obolibrary.org/obo/RO_0002309|has exposure stimulus|

**Comment by cmungall** [comment]
Experimenting with Seaborn

![image](https://user-images.githubusercontent.com/50745/46277907-960e9000-c55c-11e8-8442-1bdb958944fc.png)

The numbers are not that meaningful given the number of applicationesque ontologies that bring in large chunks of other ontologies..

**Comment by cmungall** [comment]
https://hub.docker.com/r/matentzn/ro_survey/

**Comment by dosumis** [comment]
Closing as assume @matentzn containerized code is sufficient.

**Comment by phismith** [comment]
looking at:
http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/RO_0004019
and
http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/RO_0004021
I see that

disease has basis in disruption of *has range: *process
disease has basis in disruption of *has superproperty: *disease has basis in

but

disease has basis in *has range: *disposition

Is there some mechanism to catch contradictions like this and post warnings
back to proposers?
BS
