### ISSUE TITLE
Add de-phosphorylation relation

### ISSUE THREAD

**Issue by cthoyt** [oborel/obo-relations#267]
http://purl.obolibrary.org/obo/RO_0002447 has the axiom:

`(capable of o is kinase activity o has direct input) subPropertyOf phosphorylates`

This is tightly related to the GO entry for protein phosphorylation ([GO:0006468](https://www.ebi.ac.uk/QuickGO/term/GO:0006468)), but maybe has subtle different semantics

The opposite process is protein de-phosphorylation ([GO:0006470](https://www.ebi.ac.uk/QuickGO/term/GO:0006470)), though I'm not really sure if there's a negative/inverse version of kinase activity that would make it possible to use the same form but with a replacement of the activity term.

What axiom could we use to represent a de-phosphorylation? I would also keeping in mind that whatever form we choose could also be applied to de-nitration, de-ubiquitination, and so on.

Apologies if starting with the axiom is the wrong place to building the ontology - I'm quite new to the lingo but I'm fascinated by the ideas!

**Comment by cmungall** [comment]
Sorry for the very late response

We should add this. The MF is phosphatase.

I don't love the rolification pattern (where we make an isX pred for a class; see https://github.com/oborel/obo-relations/wiki/ROGuide#interaction-relations), we should revisit this

we can also add RO:opposite-of between the two predicates

**Comment by cthoyt** [comment]
@cmungall maybe worth bringing up as an example at the meeting today?
