### ISSUE TITLE
Migrate from GH wiki to readthedocs

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#271]
RTD is IMHO more aesthetically pleasing, easier to navigate via a TOC, nex/tprev pages, etc.

alternatively we could do GH pages.

Also for some reason I don't seem to be able to update the wiki locally https://help.github.com/articles/adding-and-editing-wiki-pages-locally/

**Comment by nlharris** [comment]
Looks like this is done -- https://oborel.github.io/obo-relations/ uses RTD.

**Comment by cmungall** [comment]
indeed, thanks for closing!
