### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#272]
We run all standard ROBOT tests, e.g. ensuring ontology is coherent.

We want to also make sure that proposed changes don't break existing ontologies.

The following functionality could migrate to ROBOT/ODK, but let's try them out here first:

run `robot reason` for a combination of ro-edit (on current branch) plus ontology O, for various values of O. O can be a normal ontology release artefact, or a combined set of -base ontologies.

**Comment by cmungall** [comment]
Ticket for doing this in a standard way across OBOs via ODK: https://github.com/INCATools/ontology-development-kit/issues/118

**Comment by cmungall** [comment]
And similar ticket for robot integration tests: https://github.com/ontodev/robot/issues/369

**Comment by nlharris** [comment]
Do the child tickets cover this, or does this ticket need to be left open?

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
