### ISSUE TITLE
Add domain and range constraints for SO/MSO

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#281]
There are various relations whose domain and ranges encompass genes, transcripts etc. We need to import the module from the relevant ontology to fully restrict these.

In #280 this is being done using a more general ('material entity' OR 'generically dependent continuant'). This allows the same relation to be used with either the SO or the MSO counterpart.

When MSO is released on OBO we can strengthen this to ('SO:gene' OR 'MSO:gene'). Note the Protege does not handle duplicate labels well so we may need some strategy in MSO for distinguishing these.

TBD: have more specific relations for GDC vs ME forms?

cc @mikebada @msinclair2

**Comment by msinclair2** [comment]
Can you give me an example of duplicate labels in Protege and the problems it causes?

**Comment by balhoff** [comment]
When two entities in your ontology have exactly the same label, it can be challenging to know which one you are getting when you're typing out a class expression. And once you have a class expression, you can't really know which of the two terms is being used in it without either changing the renderer to display IRIs, or to look in your OWL file. If you click on the label within the expression, it jumps to a random entity with that label, not necessarily the one with the IRI actually used in the expression.

**Comment by balhoff** [comment]
If I understand correctly what you're asking, yes it's only a problem when both are loaded in the same workspace.

**Comment by mikebada** [comment]
I believe the only relations that are being used for both SO and MSO classes are mereotopological ones, particularly 'part of'.  I would think that this these would hold for both ICs and GDCs, but we can discuss.  I'm not sure exactly which relations @cmungall is referring to, but we can discuss at the RO meeting soon enough, ha ha.

**Comment by nlharris** [comment]
Ha ha indeed. 😀  Does this still need to be discussed?

**Comment by nlharris** [comment]
Is this still needed?

**Comment by nlharris** [comment]
Closing; reopen if needed.
