### ISSUE TITLE
Use of has curation status annotation property

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#283]
Many relations are tagged with the IAO curation status property, but this is not used consistently.

I propose removing these annotations, and instead using GH as the vetting mechanism. E.g. pending final vetting = unmerged PR. vetted = merged PR

**Comment by nataled** [comment]
Not that I have any objection, but I wanted to point out that this works only for those ontologies that rely on GitHub for updates. Also, it isn't clear how unmerged and merged imply pending and vetted, respectively. That is, it's entirely possible that a term is added that isn't fully vetted, but is released nonetheless.
