### ISSUE TITLE
in neural circuit with Domain is too strict

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#286]
With the new RO we are getting this for Uberon:

![image](https://user-images.githubusercontent.com/50745/47895360-2cb4c200-de25-11e8-883e-d037f2181e9a.png)

**Comment by cmungall** [comment]
RO is not consistent here

![image](https://user-images.githubusercontent.com/50745/47895474-c3817e80-de25-11e8-8f29-2707bab5ed9e.png)

INCW is neuron->neuron

The subproperty is:

Relation between an anatomical structure (including cells) and a neuron that chemically synapses to it.

**Comment by dosumis** [comment]
OK. The domain is clearly wrong. 

The relation is also rather useless for reasons Alan R pointed out at the time:  Ultimately every cell is in a nervous system (+inputs & outputs) is in a neural circuit with every other cell in that nervous system.  The relation might have had some use when we had fragmentary circuits mapped.  In an era of complete connectomes, it does not.  The subProperties (up/downstream in neural circuit with) are potentially useful for recording connectivity inferred from ephys where we don't know the number of intermediate cells.

**Comment by cmungall** [comment]
> I see you've fixed.

No, just a temporary workaround in uberon. Didn't touch RO

**Comment by dosumis** [comment]
That's odd. I went to fix and couldn't see the domain in ro-edit.owl.

**Comment by cmungall** [comment]
Maybe you had an earlier version?

I added these recently
https://github.com/oborel/obo-relations/blame/master/src/ontology/ro-edit.owl#L1065-L1066

to be consistent with the text definition.

should we weaken back? Then it wouldn't be consistent with the text def and label. Or move synapsed_by out from under it?
