### ISSUE TITLE
1D boundary of

### ISSUE THREAD

**Issue by aellenhicks** [oborel/obo-relations#290]
We would like a relation for 1D boundaries. In particular, we would like to model that the Equator is a 1D boundary between the North and South hemispheres.

**Comment by cmungall** [comment]
Are you comfortable making a pull request for this, or shall we add it?

**Comment by aellenhicks** [comment]
?I can make a pull request. Thanks.


________________________________

**Comment by nlharris** [comment]
Did this get done? What was the PR?

**Comment by nlharris** [comment]
Can this be closed? @aellenhicks
