### ISSUE TITLE
Add additional redundant EL domain constraint to located in

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#293]
Currently the domain is `'independent continuant'  and (not ('spatial region'))` as specified in BFO2 reference.

This is invisible to EL. We should add additional axioms

 * `located in domain: IC`
 * `spatial region DisjointWith located some Thing`

This is entailed under DL but not EL

More generally we should have a pipeline for relaxing DL axioms to EL

(pet peeve: spatial regions are perfectly useless classes in BFO, no one uses them AFAICT, this kind of needless complexity in an upper ontology causes issues computationally and cognitively. Perhaps we could at least have a grouping at the level below IC but excluding SR, not sure what this would be called, maybe "physical IC"? @phismith )

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
