### ISSUE TITLE
add tsv dump / table version of RO terms 

### ISSUE THREAD

**Issue by jhpoelen** [oborel/obo-relations#295]
as suggested by @cmungall -
"We could add this [ed. a table] to the release process for RO, easy to do with a sparql query"

See https://github.com/jhpoelen/eol-globi-data/issues/386 .

**Comment by marieALaporte** [comment]
Shouldn't the csv contain information about the domains and ranges of the properties? That can be useful information I think, particularly if someone wants to reuse the relationship in their own ontology and therefore prevent mistakes in the use of the properties.

**Comment by jhpoelen** [comment]
@marieALaporte for sure! I was hoping that the tabular form of RO would invite folks unfamiliar with rdf/owl to re-use RO terms/properties. Adding columns describing the domains and ranges to guide usage of terms/properties sounds like a good idea to me.

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
