### ISSUE TITLE
Add 2D counterparts for boundary relations

### ISSUE THREAD

**Issue by ChristianKleineidam** [oborel/obo-relations#297]
@cmungall wrote on [OpenData.SE](https://opendata.stackexchange.com/a/13724/1359):

> The OBO Relation Ontology is an ontology of relationship types that has many spatial relations that are axiomatized in OWL/SWRL. The focus of this ontology is the life sciences, but the same relations we use to say that a cell is surrounded by a cell wall can also be used to describe e.g. city boundaries. In fact the RO is being used by a broader range of ontologies such as Environment Ontologies and the Common Core Ontologies

This seems to me a surprising claim.  Neither the top nor the bottom of a city is surrounded by the city wall. 
The relationship where most of the 3D surface of X is covered by Y is qualitatively different from the relationship where if you do a 3D to 2D projection from X all of the surface of the resulting 2D shape is covered by the boundary.

The description of RO_0002219 also doesn't make it clear whether it's either (1) or (2) or whether both criteria are supposed to be requried.

**Comment by cmungall** [comment]
This is a good point, my example only applies to futuristic science fiction cities inside giant bubbles. I think this domain needs relations that pertain to their 2D projection. I did some work on this in common logic a while ago for GAZ will try and look it up

**Comment by ChristianKleineidam** [comment]
It feels to me like even in anatomy there might be cases where one entity surrounds another in 2D but not in 3D. How about adding a new property to OBO with a name like "has boundary" for the 2D case?

**Comment by cmungall** [comment]
OK, I think it is safest if we make a family of 2D relations whose D+Rs are 2D entities. Here has_2d_boundary would be functional.

We could also have convenience relations for 3D entities, but here the projected 2D boundary would not be functional (consider a sea mount projecting above the top of the water, it would have a 2D boundary of ocean at one place, and of seafloor at another)

**Comment by ChristianKleineidam** [comment]
I don't think it's completely without function for 3D entities. In your example there's valid knowledge expressed by saying that the sea mount has the boundary of the ocean. It's not 100% precise, but I think that's okay.

**Comment by cmungall** [comment]
Agreed, just that we may want separate relations. The 3D-3D relation would not be marked as functional (i.e. there may be >1 boundary), but the 2D-2D relation could be stricter

**Comment by nlharris** [comment]
What are the remaining action item(s) here?
