### ISSUE TITLE
'has vector' subPropertyOf 'is vector for'

### ISSUE THREAD

**Issue by balhoff** [oborel/obo-relations#298]
RO contains these axioms:

- 'has vector' subPropertyOf 'is vector for'
- 'has vector' inverseOf 'is vector for'

Is the sub property axiom correct? These properties end up being inferred to be equivalent, which doesn't seem correct.

**Comment by phismith** [comment]
This subproperty relation is clearly incorrect
The inverse relation is correct
BS

**Comment by cmungall** [comment]
Protege slip. Fixed in master and will be in next release
