### ISSUE TITLE
susceptible to

### ISSUE THREAD

**Issue by GoogleCodeExporter** [oborel/obo-relations#31]
```
we need a relationship that aids in describing the susceptibility of a disease 
due to variation(s) of genomic regions.

for example:
http://omim.org/entry/607339

this entry describes variants in the genomic region of human chr16pter-p13 as 
contributing to the susceptibility of coronary heart disease.

this kind of relationship is necessary for relationships created through 
statistical associations.
```

Original issue reported on code.google.com by `nicole.l...@gmail.com` on 12 Jan 2015 at 9:22

**Comment by mbrush** [comment]
We recently added a hierarchy of properties for linking genetic variants or environments to 'conditions' (inclusive of phenotypes or diseases).  See #91 for details.  I suspect that the 'contributes to condition' property would either itself suffice to meet the need for a 'contributes to susceptibility' relationship, or would serve as a parent relation under which a 'contributes to susceptibility for condition' property could be added.  Some discussion may be needed as to the distinction/relationship between 'contributes to severity of condition', and a 'contributes to susceptibility of condition' -  i.e. if severity goes from 0 - 100, then it would seem to cover susceptibility, no?

**Comment by nlharris** [comment]
What's the status of this? I hope if this term was added, it was spelled correctly. 😀

**Comment by nlharris** [comment]
Since this is so old, I'm going to close it -- please reopen if still needed.
