### ISSUE TITLE
"R-zero" appearing instead of "RO" for one entry in ro.owl (RO:0009004)

### ISSUE THREAD

**Issue by saramsey** [oborel/obo-relations#312]
See this excerpt of ro.owl:

>     
> 
>     <owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/R0_0009004">
>         <obo:IAO_0000112 xml:lang="en">sardine has consumer some homo sapiens</obo:IAO_0000112>
>         <obo:IAO_0000114 rdf:resource="http://purl.obolibrary.org/obo/IAO_0000428"/>
>         <obo:IAO_0000115 xml:lang="en">&apos;has consumer&apos; is a relation between a material entity and an organism in which the former can normally be digested or otherwise absorbed by the latter without immediate or persistent ill effect.</obo:IAO_0000115>
>         <obo:IAO_0000117>Damion Dooley</obo:IAO_0000117>
>         <rdfs:label xml:lang="en">has consumer</rdfs:label>
>     </owl:ObjectProperty>

**Comment by cmungall** [comment]
This was fixed in #303 and will be in the next release coming soon!

**Comment by saramsey** [comment]
Ah, sorry, Chris. I did a search in the issues but must have missed this.
