### ISSUE TITLE
[ bug]created_by annotation property

### ISSUE THREAD

**Issue by rajaram5** [oborel/obo-relations#313]
There are two "created_by" annotation properties in the release "2019-02-02".  It looks like a bug. I have listed IRIs of these properties below.  

1) http://www.geneontology.org/formats/oboInOwl#created_by 
2) ttp://www.geneontology.org/formats/oboInOwl#created_by

**Comment by nlharris** [comment]
Is this now fixed?

**Comment by nlharris** [comment]
This was an old release; I'm assuming this has been dealt with. Closing, but reopen if it's still a problem.
