### ISSUE TITLE
occupies temporal region

### ISSUE THREAD

**Issue by pfabry** [oborel/obo-relations#317]
Hello,

The relation "occupies temporal region" between an occurent and a temporal region is defined in BFO (BFO 2.0 Specification and User's guide, chap. 3.9.2).
However the corresponding object property can't be found in ro,wether it is ro-core or any other modules.
is there a specific module for this property?

**Comment by cmungall** [comment]
I can go ahead and do this, cc @jamesaoverton

**Comment by nlharris** [comment]
Not sure what the action item is here.

**Comment by nlharris** [comment]
Is this a new relation request?

**Comment by pfabry** [comment]
I'm not sure it is a new property as it already exists (BFO_0000155) and is used in several ontologies. See for example:

http://www.ontobee.org/ontology/OMIABIS?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000155

However, it seems the only way to import it is via an external ontology as it is not available in RO. In addition, I don't think it could be replaced by the property "temporally related to" (RO_0002222) or one of its children.

**Comment by ddooley** [comment]
I'll note that this term and its parent "exists at" don't show under the BFO that OLS and Ontobee have (Ontobee shows BFO 1.1 and BFO [2.0] as separate ontologies).

**Comment by nlharris** [comment]
Ok to close, then?

**Comment by pfabry** [comment]
Yes, thank you!
