### ISSUE TITLE
Base and default namespace for RO core

### ISSUE THREAD

**Issue by mark-jensen** [oborel/obo-relations#318]
I notice that Core's base and default namespaces are identical to BFO's. I realize these are typically not used for expressing ontologies in OWL and can safely be ignored. It does stand out as odd that these wouldn't align with the ontology IRI, like most Foundry ontologies. Is the duplication with BFO intentional? Or perhaps an artifact of how the Core was created?

`xmlns="http://purl.obolibrary.org/obo/bfo.owl#"`
`xml:base="http://purl.obolibrary.org/obo/bfo.owl"`

**Comment by cmungall** [comment]
These could easily be changed

**Comment by mark-jensen** [comment]
I'm happy to do so on a branch if that helps.

**Comment by cmungall** [comment]
go for it!

**Comment by cmungall** [comment]
Thanks!
