### ISSUE TITLE
Generalising relations for geospatial entitites 

### ISSUE THREAD

**Issue by pbuttigieg** [oborel/obo-relations#320]
Related to #229 as well as  https://github.com/EnvironmentOntology/gaz/issues/24 in GAZ and multiple ENVO issues like https://github.com/EnvironmentOntology/envo/issues/625.

Many of RO's more structural relations are grounded in anatomy or biology. With either small revisions or the addition of more general superclasses, we can more accurately use them for geological and geographic entities in ENVO and GAZ. 

Perhaps we can discuss a general strategy to do that in this issue, branching off new issues if/when appropriate?

The theme of generalising some relations also applies to issues like #201

**Comment by cmungall** [comment]
See also #297, RO spatial relations are 3D

Sometimes we will need an explicit 2D relation that is different

What about located_in? Is mt Kilimanjaro ro:located_in Africa? Yes if we consider Africa as a 3D object extending at least 20k feet above sea level. If this starts getting us into odd territory about air rights etc then I think it's much simpler to have a 2D analog or the main RO located_in

**Comment by alanruttenberg** [comment]
There's a missing general relation of site to host that I've advocated to Barry be added.

**Comment by cmungall** [comment]
is this host in the organismal sense?

**Comment by alanruttenberg** [comment]
No, in the sense that the a site necessarily is in reference to material entities. The most current elucidation:

b is a site means: b is either (1) a three-dimensional immaterial entity that whose boundaries either (1) (partially or wholly) coincide with the boundaries of one or more material entities or (2) have locations determined in relation to some material entity

By host I mean those material entities. There are still issues that need to be resolved. One that comes to mind is the case of a site created by two material entities. Is the host the aggregate or are there two hosts. Still, having the relation would be a step forward. Another is whether there should be a different (sub?)relations for case (1) vs (2). The material entity in the second case seems to be more by fiat than the first case.

The host relation can be further specialized, for organisms, or for the particular spatial relation between the host and the site. One of the issues mentioned containment such as an eye in an eye socket. I think this relation (or at least part of it) is something like: significant overlap of the convex hulls of the spatial locations of eye and the socket.

**Comment by cmungall** [comment]
ok makes sense

would be great if bfo can avoid the term 'host' for the abstract
classes/relations since this will confuse biologists

>

**Comment by alanruttenberg** [comment]
Sure. Any suggestions?

**Comment by kaiiam** [comment]
This idea came up again today at the ESIP semantic harmonization committee meeting (xref https://github.com/EnvironmentOntology/envo/issues/1010) in conversation with @pbuttigieg Mark Schildhauer and @brandonnodnarb  when trying to axiomatize terms like `subglacial` and `supraglacial`, it would be great to have some more generic meriotopological relations like above and below. Would there be scope for addition of such relation types in RO? Perhaps we could prototype them in ENVO first.

**Comment by phismith** [comment]
I have no objection to adding this relation. But can someone suggest a
label?
Barry

**Comment by cmungall** [comment]
@kaiiam - go ahead. I think RO is a good home for these but there's also a case for ENVO

You might find some inspiration in BSPO, see the paper linked here http://obofoundry.org/ontology/bspo

I wouldn't advocate a super-generic above/below. Assume something that is relative to a center of gravity or planetary surface?

**Comment by pbuttigieg** [comment]
>I wouldn't advocate a super-generic above/below. Assume something that is relative to a center of gravity or planetary surface?

We're trying to engage some geospatial experts on this. 
For many astronomical bodies, they centre of gravity is a good approximation; however, the datum can change so we'll think about a more generic class.

**Comment by pbuttigieg** [comment]
xref: [GeoSPARQL](https://en.wikipedia.org/wiki/OGC_GeoSPARQL) and its Region Connection Calculus
