### ISSUE TITLE
Add warning to non-temporally quantified relations

### ISSUE THREAD

**Issue by dosumis** [oborel/obo-relations#321]
Some relations need a comment clarifying their temporal interpretation and warning about uses which are potentially unsafe. 

Draft for part_of (BFO:0000050):

part_of is potentially unsafe to use between two classes of continuant where one or both are non-rigid or where a relationship is transitory.  This is particularly a problem when building models of developmental anatomy or recording the relationships of migrating cells to tissues.

Examples:  
A cell type is part_of a primordium at an early stage and part_of a mature structure at a later stage.  In this case BFO:000050 should NOT be used to link the cell type to either structure.

.... (MORE WORK NEEDED)

**Comment by jamesaoverton** [comment]
@cmungall: 'part of' has an outdated annotation pointing to the old wiki, which needs to point to something such as <https://github.com/oborel/obo-relations/wiki/ROAndTime>.

There are also 'temporal annotation' annotations on some terms. These need improvement.
