### ISSUE TITLE
Typo in definition of involved in regulation of?

### ISSUE THREAD

**Issue by Mttbnchtt** [oborel/obo-relations#326]
The definition of "involved in regulation of" seems to contain a typo: _c involved in regulation of p if c is involved in some 'p' and p' regulates some p_. I think it should be: _c involved in regulation of p if c is involved in some p' and p' regulates some p_ (with the first ' removed).

**Comment by nlharris** [comment]
Did someone check whether this is indeed a typo?

**Comment by pgaudet** [comment]
this looks like a typo to me

**Comment by nlharris** [comment]
I was thinking maybe I could find where this is defined and make a PR, but although I found that text in multiple files (https://github.com/oborel/obo-relations/search?p=3&q=%22c+involved+in+regulation+of+p%22) I couldn't identify the "master" location of the definition.

**Comment by pgaudet** [comment]
As @Mttbnchtt described the def, there seemed to be a typo, however it seems to be corrected in the current version of the ro-edit.owl file 

> c involved in regulation of p if c is involved in some p' and p' regulates some p

Close?

**Comment by nlharris** [comment]
Thanks, Pascale!
