### ISSUE TITLE
overlaps o part of --> overlaps should be added to RO

### ISSUE THREAD

**Issue by matentzn** [oborel/obo-relations#330]
We have been using this chain for a long time in the Flybase ontologies:

```
[Typedef]
id: overlaps
name: overlaps
xref: RO:0002131
transitive_over: part_of ! part_of
```

"If it overlaps with the door, it overlaps with the house the door is part of."

As part of our Flybase ontology spring clean, we would like this to be added to RO. If someone tells me where (which file) I can make a pull request. @cmungall @dosumis

**Comment by cmungall** [comment]
ro-edit

can't believe we were missing this...

**Comment by matentzn** [comment]
Made PR. Would be cool in future if I could create a PR in future without forking :P
