### ISSUE TITLE
Replacement for "has active participant"

### ISSUE THREAD

**Issue by pbuttigieg** [oborel/obo-relations#333]
[has active participant](http://purl.obolibrary.org/obo/RO_0002218) was obsoleted. Is there a replacement? 

The inverse is live, however, [actively participates in](http://purl.obolibrary.org/obo/RO_0002217)

We need this relation for developments processes in SDGIO and elsewhere.

Links to #18 #40

**Comment by pbuttigieg** [comment]
Perhaps linked to [causal agent in](http://purl.obolibrary.org/obo/RO_0002500)?

**Comment by cmungall** [comment]
This commit: https://github.com/oborel/obo-relations/commit/eb0579c4c6d887803942a2cd0657561440c7f6d1

In this PR: https://github.com/oborel/obo-relations/pull/291

I think this was just a mistake. The fact the inverse is there is telling. In fact ideally the pipeline should prevent logical axioms referencing obsoletes.

**Comment by pbuttigieg** [comment]
To clarify (@cmungall sitting next to me) the mistake was that this term was obsoleted in the PR. 

That being said, 'has causal agent' (with no cardinality restrictions) does the same work and will likely replace "has active participant", as the latter is ambiguous (one can be active but not the causal agent)

**Comment by dosumis** [comment]
> That being said, 'has causal agent' (with no cardinality restrictions) does the same work and will likely replace "has active participant", as the latter is ambiguous (one can be active but not the causal agent)

I've only ever used has_active_particpants for causal agents (e.g. enzyme as causal agent in GO catalytic activity) - so I'm happy with this change.

**Comment by nlharris** [comment]
Seems like this has been resolved -- if not, please reopen.
