### ISSUE TITLE
New relation request: 'has result' and 'has cause'

### ISSUE THREAD

**Issue by txpo-ontology** [oborel/obo-relations#334]
Dear obo-relations group,

I would like to request new relation terms “has result” and “has cause." We'd like to use these relations in ToXic Process Ontology TXPO. 

1. has result　(or result in)
inverse of 'has cause':
p 'has cause' q if p exerts some causal influence on q directly, where p is a cause and q is its effect.

Domain: process
Range: process
is-a hierarchy:
causal relation between processes (http://purl.obolibrary.org/obo/RO_0002501)
 causally downstream of or within (http://purl.obolibrary.org/obo/RO_0002427)
  causally downstream of (RO_0002404) -> In TXPO, this term is not referred to because curation status is "requires discussion."
   has result  

Example: 'insulin deficiency' has result 'increasing blood glucose level'

Other examples used in toxic course maps can be viewed at the TOXPILOT site: https://toxpilot.nibiohn.go.jp
ICBI 2019 paper: https://drive.google.com/file/d/12jZ69MIDiBxswAPZunHDirG8gP0NjueI/view

2. has cause
p 'has cause' q if p exerts some causal influence on q directly, where p is a cause and q is its effect.
is-a hierarchy:
causal relation between processes (http://purl.obolibrary.org/obo/RO_0002501)
 causally upstream of or within (http://purl.obolibrary.org/obo/RO_0002418)
  causally upstream of -> In TXPO, I skip this term because curation status is "requires discussion"
   has cause  
Domain: process
Range: process

At present, these terms are given TXPO-specific URIs, but after approval, we want to change them to RO URIs.

I'm sorry for sending this mail not this GitHub issues site but to Google group mailing list wrongly two days ago.

Sincerely, 
Yuki Yamagata, Ph.D.
y-yamagata@nibiohn.go.jp
Laboratory of Toxicogenomics Informatics
National Institutes of Biomedical Innovation, Health and Nutrition
7-6-8 Asagi, Saito, Ibaraki,
567-0085, Osaka, Japan

**Comment by cmungall** [comment]
Hello. No worries about sending to list, either is fine, but GitHub is best.

I would go ahead and use RO_0002404. The curation status metadata flags need to be revised as they are not particularly meaningful.

**Comment by txpo-ontology** [comment]
Thank you.

**Comment by nlharris** [comment]
This seems like it has been addressed.
