### ISSUE TITLE
Restrict range of 'composed primarily of'

### ISSUE THREAD

**Issue by pbuttigieg** [oborel/obo-relations#335]
Over at ENVO, during a moment of confusion, I asserted that a planetary surface was composed primarily of some desert area. 

As desert area is a BFO:site, this doesn't make sense. It would be good to prime reasoners to pick this sort of thing up. Restricting this relation's range to "material entity" may work.

**Comment by cmungall** [comment]
would you be up for making a PR on ro-edit?

**Comment by balhoff** [comment]
Domain and range for 'composed primarily of' are already both 'material entity'. @pbuttigieg you may have gotten tripped up by ELK 0.4.3 not checking ranges at all.

To me 'material entity' seems overly specific; perhaps this relation should have "contextual" domain and range, like 'part of', where they have to be "compatible".

**Comment by cmungall** [comment]
Do you envision using this for processes, spaces Jim?

**Comment by balhoff** [comment]
I didn’t have a particular use case in mind. You could say something like a musical work is composed primarily of slow movements.

**Comment by nlharris** [comment]
I prefer fast movements. 🎶 Speaking of which, any movement on this issue?

**Comment by nlharris** [comment]
closing as won't do; reopen if desired.
