### ISSUE TITLE
Add license to ontology header

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#342]
http://obo-dashboard-test.ontodev.com/ - the ontology is failing the 'open' check

the release owl should contain:

```
     xmlns:terms="http://purl.org/dc/terms/"
...
        <terms:license rdf:resource="https://creativecommons.org/publicdomain/zero/1.0/"/>
```

See https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1041

**Comment by balhoff** [comment]
This is already done.
