### ISSUE TITLE
dup definitions: existence starts at point & existence ends at point 

### ISSUE THREAD

**Issue by srobb1** [oborel/obo-relations#346]
Hello,

I noticed that these two terms have the same def. 

id|label|def|
-- | -- | --
[RO:0002583](http://purl.obolibrary.org/obo/RO_0002583) | existence starts at point | x existence starts at point y if and only if   the time point at which x starts is equivalent to the time point at which y   ends.
[RO:0002593](http://purl.obolibrary.org/obo/RO_0002593) |existence ends at point | x existence starts at point y if and only if the time point at which x   starts is equivalent to the time point at which y ends.

Would you like me to update and make a pull request? Though I am a bit confused by 'point at which y ends' part of the definition. How can x start at point y if y is ending?

Sofia

**Comment by phismith** [comment]
It is perhaps interesting that 2 of the (very small number of) additions in
BFO 2020 (as compared to BFO 2.0) is the addition of two new relations

first-instant-of and last-instant-of

with domain: process and range: time instant

I don't think the definiendum in
RO:0002583 <http://purl.obolibrary.org/obo/RO_0002583>
makes sense in English

**Comment by srobb1** [comment]
I think that for

RO:0002583 | existence starts at point
-- | --

The definition could change:

**from**:
X existence starts at point y if and only if the time point at which x starts is equivalent to _the time point at which y ends_.

**to**:
1) X existence starts at point y if and only if the time point at which x starts is equivalent to _a time point after y begins and before y ends._

-or-

2) X existence starts at point y if and only if the time point at which x starts is equivalent to _a discrete time point which is y._


It seems that y should be a discrete instant, a single moment, and not a time range. If so, suggestion 2 fits better.


Sofia

**Comment by nlharris** [comment]
Is this still needed?

**Comment by cmungall** [comment]
Fixed in #357

**Comment by cmungall** [comment]
the definitions are now distinct, and I believe formally correct, if a little formal. Open new issues/PRs for any further clarifications
