### ISSUE TITLE
Question about correct usage of 'existence overlaps'

### ISSUE THREAD

**Issue by vanaukenk** [oborel/obo-relations#349]
Hi,

We are reviewing use of relations in GO annotation and are at an impasse with trying to find the best one to relate a structure (i.e. cellular component) and the BP during which it exists.

Past curation used the relation 'exists during' which is in gorel.obo, but I'm wondering if we can switch this to use 'existence overlaps' from RO.

Here's the relevant info from the 'exists during' entry in gorel.obo:

id: exists_during
name: exists_during
namespace: go/extensions/gorel
comment: Previous definition "c exists_during p if and only if the temporal extent bounded by the start and end of c is part_of the temporal extent of p." [BFO:cjm]
subset: AE_biological_process
subset: AE_developmental_stages
property_value: usage "Identifies a process or life stage during which a cellular component is present" xsd:string

and here is the RO entry:

![image](https://user-images.githubusercontent.com/1730534/74466734-d88cf000-4e65-11ea-807e-935e4c65663d.png)

Would we be correct in replacing 'exists during' with 'existence overlaps' in GO annotation?

Note that a similar question has come up before:  #8

**Comment by nlharris** [comment]
Can anyone answer this question?

**Comment by Clare72** [comment]
Based on the previous definition in your comment on exists_during, I think RO:0002491 'existence starts and ends during' is the RO equivalent (existence of c is only during p).
