### ISSUE TITLE
Any updates on TemporallyQualifiedContinuants?

### ISSUE THREAD

**Issue by lydiang** [oborel/obo-relations#352]
Hi,

I came across this discussion in the Wiki on how to handle "part_of" relationship that can change over time:  https://github.com/oborel/obo-relations/wiki/ROAndTime.

In particular, I am curious if the concept of temporally qualified continuants that is functional in OWL was explored further?

My particular use case of the tracking of anatomical parts of an organism where we have data from when it was still "part_of" the organism and also after it has been extracted and subdivided etc.

Thanks,
Lydia

**Comment by phismith** [comment]
You may be interested in the BFO 2020 treatment of part of and other
relations. The owl formalization is available here: BFO-ISO
<https://buffalo.app.box.com/v/bfo-iso-owl-cl>
This relates to an ISO standardization of BFO which will be published in
final form in the next weeks.

**Comment by lydiang** [comment]
Hi Barry,
Thank you so much for the link, this is what I was looking for.
I was wondering if there are any presentation or docs that have simple examples to show how to properly link the time component for instances?
Thanks,

**Comment by nlharris** [comment]
Can anyone help @lydiang find the documentation? Maybe @jamesaoverton?

**Comment by jamesaoverton** [comment]
Sorry, I can't help with this.

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
