### ISSUE TITLE
GO import pulls in obsolete GO:0044456 and GO:0044464

### ISSUE THREAD

**Issue by matentzn** [oborel/obo-relations#356]
Should be removed by next release, but since I am on a spring cleaning spree, I will mention it all.

**Comment by matentzn** [comment]
GO:0044456 and GO:0044464

**Comment by nlharris** [comment]
Can this be closed?

**Comment by nlharris** [comment]
Now can it be closed?

**Comment by nlharris** [comment]
Closing; reopen if needed
