### ISSUE TITLE
Check OBO Dashboard results

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#361]
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1076
See http://obo-dashboard-test.ontodev.com/ro/dashboard.html

**Comment by nlharris** [comment]
Is this the same as #358?
@nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
Looks like it. Feel free to close one, Nomi.

**Comment by nlharris** [comment]
Note that the dashboard URL for RO is now http://dashboard.obofoundry.org/dashboard/ro/dashboard.html
RO's not scoring too badly, but it looks like there are a few things to look at.

**Comment by matentzn** [comment]
Note that there are only two remaining issues according to the OBO dashboard, the rest are overly draconian https://github.com/OBOFoundry/OBO-Dashboard/issues/60.

This was the only real RO error:
https://github.com/oborel/obo-relations/pull/554
