### ISSUE TITLE
Update CONTRIBUTING with more details

### ISSUE THREAD

**Issue by balhoff** [oborel/obo-relations#365]
`CONTRIBUTING.md` is pretty out of date. In particular it discourages pull requests, which shouldn't be a problem currently.

**Comment by cmungall** [comment]
ugh yes that is very old

Let's just use the default odk one:

https://github.com/INCATools/ontology-development-kit/blob/master/template/CONTRIBUTING.md.jinja2

**Comment by nlharris** [comment]
PR #428 updated as per @balhoff's comments; ready to merge when approved.
