### ISSUE TITLE
New neuron -> region synaptic connectivity relation needed

### ISSUE THREAD

**Issue by dosumis** [oborel/obo-relations#379]
.	has_synaptic_terminal_in
.	.	has_synaptic_IO_in
.	.	.	receives_(synaptic)_input_in
.	.	.	.	receives_(synaptic)_input_throughout
.	.	.	sends_(synaptic)_output_to

+ all input/output neutral variants 

Definitions:

has_synaptic_IO_in: a relationship between a neuron and a region where the neuron has a functionally relevant number of input &/or output synapses in that region.
receives_synaptic_input_in: a relationship between a neuron and a region where the neuron has a functionally relevant number of input synapses in that region.
receives_synaptic_input_throughout: a relationship between a neuron and a region where the neuron has a functionally relevant number of input synapses distributed throughout that region (rather than confined to a subregion).

Background:

VFB is ingesting connectomic data.  The current relations are (has_synaptic_terminal_in etc) are too sensitive - triggered by the presence of single synapse - which may be exptl noise, biological noise, or not functionally significant.  We therefore need relations for functionally significant input/output.  In the short term, these will only be used on the class level.

**Comment by Clare72** [comment]
I wasn't sure if these should also be children of 'receives input from' and 'sends output to', thought they probably shouldn't be under 'connected to' as well as 'overlaps'.

**Comment by dosumis** [comment]
connected_to defined as adjacent & sharing a boundary, disjoint with overlaps.
