### ISSUE TITLE
NTR: results in adhesion of

### ISSUE THREAD

**Issue by vanaukenk** [oborel/obo-relations#388]
This new relation request is part of a review of the use of the GO relation 'has agent' in annotation extensions.

The 'has agent' relation has been used with a variety of different BP (and a handful of MF) terms, with one of the more common BP terms being cell-cell adhesion or a child thereof.

To qualify the cell-cell adhesion annotations, the GO ontology editors propose addition of a relation, results in adhesion of, to capture the cell types involved in the adhesion process.

Here's a proposed term placement and definition:

has anatomical participant (RO:0040036)
- results in adhesion of (RO:new)

Def.  The relationship that links anatomical entities with a process that results in the adhesion of two or more entities via the non-covalent interaction of molecules expressed in, located in, and/or adjacent to, those entities.

@ukemi @pgaudet @cmungall 
Please comment on the definition if you think it needs to be revised.  I was trying to capture something about what mediates the adhesion, but am not sure if the spatial information is necessary here.

**Comment by pgaudet** [comment]
Done.
