### ISSUE TITLE
purl for 'realizes' does not resolve

### ISSUE THREAD

**Issue by bpeters42** [oborel/obo-relations#390]
The purl for 'realizes', http://purl.obolibrary.org/obo/BFO_0000055, does not resolve. When browsing in Ontobee through RO, it does display fine: http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/BFO_0000055

so I suspect it is the rewrite rule that has a hickup when looking for a RO class with a BFO namespace in the ID.

**Comment by jamesaoverton** [comment]
RO adopted a small number of relations from BFO's IDSPACE. BFO:0000055 'realizes' is defined in RO core here:

https://github.com/oborel/obo-relations/blob/master/src/ontology/core.owl#L163

The PURL system has a small number of overrides to handle these, but BFO:0000055 is not on the current list:

https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/obo.yml#L22

I'm responsible for this stuff. It seems strange that I would have simply missed this, but at the moment I can't find any useful notes on the relevant repositories. Does any one else recall a reason why 'realizes' is not redirected in the PURL system?

**Comment by jamesaoverton** [comment]
I didn't have time to figure this out. Jie pointed out a few more. I'd like someone else to take care of this.

**Comment by zhengj2007** [comment]
I found few more BFO relations in RO that URLs don't resolve.
 
http://purl.obolibrary.org/obo/BFO_0000054 realized in 
http://purl.obolibrary.org/obo/BFO_0000063 precedes 
http://purl.obolibrary.org/obo/BFO_0000067 contains process

**Comment by nlharris** [comment]
Looks like this was fixed! Thanks, @balhoff!
