### ISSUE TITLE
Add new subsets for GO annotation

### ISSUE THREAD

**Issue by vanaukenk** [oborel/obo-relations#391]
The GO is working to make sure that all relations currently used for annotation are ultimately represented in RO (with the exception of some chained relations, e.g. regulates_o_occurs_in, that will remain in gorel for the foreseeable future).

We think it would be helpful for curators and tool developers to categorize RO relations with one or more subset tags to indicate those that can be used in GO.

Minimally, we could have a subset of:

valid_for_go

or we could perhaps create more granular subsets, for example:

valid_for_go_ontology

valid_for_go_gp2term

valid_for_go_annotation_extension 

valid_for_gocam

@ukemi @cmungall @pgaudet - what do you think about general vs specific subsets?  
-> Decision was to create the specific subsets

----
**Notes/changes are in this document:** 

https://docs.google.com/spreadsheets/d/1qLvHreUfhycfvMrT_jpRhklcFlTccldFz7Zg-Z7dK90/edit#gid=0

* valid_for_go_ontology -> check usage in the ontology

* valid_for_go_gp2term -> check ShEX: https://github.com/geneontology/go-shapes/blob/master/shapes/go-cam-shapes.shex

* valid_for_gocam -> check ShEX: https://github.com/geneontology/go-shapes/blob/master/shapes/go-cam-shapes.shex

* valid_for_go_annotation_extension -> check usage  https://docs.google.com/spreadsheets/d/1zB8UKtG3JRGMkHgXmMpby-K5RFmYxGGRMEXULCCtcPo/edit#gid=1781021565

**Comment by balhoff** [comment]
Shouldn't these subsets be maintained by GO and not by RO? We can have a file of these annotations in the GO repo—unless RO folks think it would be nice for RO to indicate which different ontology projects use various terms.

**Comment by pgaudet** [comment]
@balhoff How do you see the list being maintained by GO ? We would need another version of GOREL ? 

I guess I assumed that GO keeps that sort of information for other groups (go-slim-flybase, etc), so this was similar.

**Comment by balhoff** [comment]
Sort of like GOREL, but it wouldn't create any new terms. Just OWL axioms talking about RO terms.

**Comment by vanaukenk** [comment]
One additional benefit I can see to having subsets in RO is that the information on usage would then be available to users of browsers like OLS or Ontobee which I know curators use.

**Comment by pgaudet** [comment]
Agreed on the GO editors call that we will create a subset in RO.

**Comment by pgaudet** [comment]
And we'll go for the more granular terms: 

* valid_for_go_ontology
* valid_for_go_gp2term
* valid_for_go_annotation_extension
* valid_for_gocam

**Comment by nlharris** [comment]
So can this ticket be closed, @pgaudet?

**Comment by pgaudet** [comment]
This is still in progress.

**Comment by pgaudet** [comment]
Add valid_for_go_gp2term to 
- contributes_to
- colocalizes_with
