### ISSUE TITLE
causally upstream of or within

### ISSUE THREAD

**Issue by ValWood** [oborel/obo-relations#392]
Hi @cmungall 

I'm looking at the relations which can be used for connections between activities.
These seem to be, (if what I am reading is correct) those below causally related to, so:

<img width="378" alt="MF-MF relation connectors" src="https://user-images.githubusercontent.com/7359272/93120368-2e0ad300-f6bb-11ea-8ec9-c497fed08b1b.png">

So,  does "causally upstream or within" have any meaning for MF?

I looked at the def
definition
p 'causally upstream or within' q iff (1) the end of p is before the end of q and (2) the execution of p exerts some causal influence over the outputs of q; i.e. if p was abolished or the outputs of p were to be modified, this would necessarily affect q.

I guess the issue is the these relations can describe the relationships of entities to each other, to processes and to activities, or  activities to each other and  some terms are not relevent for the annotation of activities to each other. Is this an issue.

For example  "causally upstream of or within" has only one descendant  "causally upstream of" 
- seems fine when describing the  relationship of one activity of one activity to another.

However, I would often want to use these terms to say that "entity " act upstream of process B (ie is causally upstream of, but not within the process, it acts upstream of the process start, I think this is whey these relations originally existed?)

 So, this would be used to say rather than 
this entity (gene product) is part_of this process
or
this entity  is causally_upstream of this process  (in the 'qualifier field that describes the relationship of the entity to the annotation)

but something seems wrong. This means that by implication, if an entity  is 
causally upstream or within, so it is either  I0 causally upstream or ii) within. Within in the process context is part_of. So, should  part_of be a descendant of "causally upstream or within" and a sibling of
"causally upstream of"?

 is used when a gene product activity may be within  the process of interest, or upstream of the process, you don't know which. So, if you do know it isn't upstream

**Comment by ValWood** [comment]
I now found "acts upstream of" by looking at the QuickGO annotations. 
So maybe this is the  relation to say a gene product acts upstream of a process.

c acts upstream of p if and only if c enables some f that is involved in p' and p' occurs chronologically before p, is not part of p, and affects the execution of p. c is a material entity and f, p, p' are processes.

but I have the same issue here.
Acts upstream of or within has only one descendant  , "acts upstream of"
What is it's sibling? 

https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002263&viewMode=All&siblings=false

**Comment by balhoff** [comment]
> Acts upstream of or within has only one descendant , "acts upstream of"
> What is it's sibling?

There are more—click on 'Show all siblings' (gray box).

**Comment by balhoff** [comment]
> So, should part_of be a descendant of "causally upstream or within" and a sibling of "causally upstream of"?

@ValWood the relation 'occurrent part of' is a subproperty of both 'part of' and 'causally upstream of or within'.

**Comment by ValWood** [comment]
Got it! 

I also now get that there are 3 things

1. causal relation between entities
i.e. gene product a regulates gene product b

2. causal relation between material entity and a process
i.e 
gene product is involved in a process 
gene product enables activity

(although I don't understand the difference between involved_in a process and capable_of_part_of a process aren't they the same thing?)

3. causal relation between a process (which here means a process or a activity?)
so 
protein kinase activity   (enabled by wee1) directly_positively_regulates  protein kinase activity   (enabled by cdc2)

I guess the thing I still don't understand is how the relationship between two activities can be "causally upstream or within", it can only be causally upstream, but maybe that doesn't matter.

It also doesn't seem to be easy to be precise be precise in GO cam if an activity acts upstream of a process. The model seems to always assume   that causal relations between entities are describing 
activities, i.e activity A is upstream of activity B.

There does not seem to be a way (at least with the templates ) to say 
activity a  is causally upstream of activity B which is part of process X
and activity a is upstream  of process X 

i.e. to say explicitly when you have some causal effect that is not part of a process.
 
OK!
