### ISSUE TITLE
A suggestion for causal relation between entities

### ISSUE THREAD

**Issue by ValWood** [oborel/obo-relations#393]
I would like to suggest an ancestor of
"regulates quantity of"

"NTR regulates availability of" 
definition
The entity A, immediately upstream of B, has an activity that directly regulates the availability of B.

 - "regulates quantity of"

so that
- "NTR regulates location of"  
definition
The entity A, immediately upstream of B, has an activity that directly regulates the location of B.

can be a descendant
(you can regulate availability via quantity or location)

( in fact, sequestering  seems to be the main way that  phosphorylation events regulate protein kinases and transcription factors )

and if you regulate the location you likely don't affect the quantity.

**Comment by pgaudet** [comment]
@ValWood 

looks like your sentence is incomplete - as an ancestor or what term ?

**Comment by ValWood** [comment]
edited

**Comment by pgaudet** [comment]
Hi @ValWood 

We discussed this on the ontology call. Those relations are used by Signor /Causal-TAB. 

They are not consistent with our GO-CAM specifications- how would you like to use those for GO? 

Thanks, Pascale

**Comment by ValWood** [comment]
I'm not using them for GO. We would like to be able to automatically create entity based models in addition to activity-based models.

but happy to close this for now because this seemed to make sense based on the thesis I was examining.  I can come back to this once we have looked in more detail at the logic.

**Comment by pgaudet** [comment]
In this case please request the relation from the obo-relations tracker: https://github.com/oborel/obo-relations/issues

Thanks, Pascale

**Comment by pgaudet** [comment]
oups ! This *is*  the obo-relations repo. 

@cmungall are these appropriate terms ?

**Comment by nlharris** [comment]
Is this still needed?
