### ISSUE TITLE
relationship missing between causally influences and descendants

### ISSUE THREAD

**Issue by ValWood** [oborel/obo-relations#394]
There seem to be some  useful relation missing between

"causally influences" which can apply to anything  (a phenotype shape size)

and the descendants "regulates the activity of"and "regulates the quantity of"

It seems that some relations that for non-specific regulation is required. We often know that an entity  (in a signalling pathway ) is regulating its substrate but we don't necessarily know the mechanism
 
For a kinase  regulating a kinase we would not know if it was regulating activity, or localization (location is more common), although I suspect most curators would annotate to 'regulates the activity of'

**Comment by nlharris** [comment]
Do you want to propose a specific new term to add in between?

**Comment by ValWood** [comment]
I'll close this. Will open a new ticket with specific examples once I get to  the models that need it.
