### ISSUE TITLE
decreases by repression quantity of/  up-regulates quantity by expression 

### ISSUE THREAD

**Issue by ValWood** [oborel/obo-relations#396]
term: decreases by repression quantity of RO_0011007
The entity A has an activity that down-regulates by repression the quantity of B. The down-regulation is due to A having an effect on an intermediate entity (typically a DNA or mRNA element) which can produce B. For example, protein A (transcription factor) indirectly decreases by repression the quantity of protein B (gene product) if and only if A negatively regulates the process of transcription or translation of a nucleic acid element that produces B.

This term name should be made explicit

decreases quantity by repression of gene expression 

similarly the 'opposite' term
up-regulates quantity by expression RO_0011008 
should be
decreases quantity  by activation of gene expression 

to be unambiguous and consistent

**Comment by ValWood** [comment]
corrected above comment

**Comment by nlharris** [comment]
So is this a request for a new relation, or changing the wording of an existing one, or...?

**Comment by ValWood** [comment]
Just to standardize the upregulation and th down regulation  so that the term names match  each other (the other sting s can be synonyms)

**Comment by dosumis** [comment]
Hi Val, 

If these refer to existing relations, can you add the IDs to the ticket and also specify general types for domain and range?

Also, I think I understand at least some of the intention, but these don't sound like relation names.  This doesn't make a sentence:

A 'decreases quantity of by repression of gene expression' B 

Maybe 

A 'decreases quantity by repressing expression of' B

Or simpler

A 'represses expression of' B ?

& infer decreases quantity of from heirarchy

'decreases quantity of'
...      'represses expression of'

**Comment by ValWood** [comment]
Edited above.

represses/activates expression of sounds fine. Much easier to read.

My main concern was that I could not easily find the 'opposite' term, because it had a completely different label.

**Comment by nlharris** [comment]
Is this still needed? (cc @vanaukenk)

**Comment by vanaukenk** [comment]
@nlharris I'll defer to @ValWood on this one.

**Comment by ValWood** [comment]
You can ignore. I can't even remember the context. Happy New "Year.

val
