### ISSUE TITLE
`RO:0002092` (happens during) should be a `RO:0002091` (starts during) subproperty

### ISSUE THREAD

**Issue by althonos** [oborel/obo-relations#397]
Hi there!

The `RO:0002092` (happens during) relationship is defined as being a subproperty of `RO:0002093` (end during), but not of `RO:0002091` (starts during). However, the logical definition of it suggest that it should be a suproperty of both of these, unless I'm wrong.

**Comment by pgaudet** [comment]
GO editors agree to fix this.
