### ISSUE TITLE
Adding new relationship "encircle"

### ISSUE THREAD

**Issue by teleaslamellatus** [oborel/obo-relations#399]
So the exoskeleton (cuticle) in insects is composed of more and less flexible (sclerotized) regions (sclerites and conjunctivae), that are continuous with each other (they have fiat boundaries). Quite often, especially when the exoskeleton is evaginated, these structures "surround" each other. Like on the attached drawings, A "surrounds" B, B "surrounds" C, C "surrounds" D and D "surrounds" E.

This is basically the case for most insect appendages (e.g. antennae, legs, male genitalia).

I put "surround" in quotation marks because the RO terms surround and 'surrounded by', I think, should not be used in this case. It is like if you would like to say that the skin of the small finger is "surrounded by" the skin of the rest of your hand...perhaps. 

![IMG-1823 (1)](https://user-images.githubusercontent.com/9273125/94178073-98b0d100-fe68-11ea-90dd-8de971dc261e.JPG)
![IMG-1826 (1)](https://user-images.githubusercontent.com/9273125/94178076-98b0d100-fe68-11ea-9387-1efee27b02a4.JPG)
![IMG-1825 (1)](https://user-images.githubusercontent.com/9273125/94178078-99496780-fe68-11ea-902c-425adb04003f.JPG)
![IMG-1824 (1)](https://user-images.githubusercontent.com/9273125/94178079-99496780-fe68-11ea-85c9-3bfeb790066e.JPG)

**Comment by ddooley** [comment]
Reminds me of varieties of enclave/exclave - and pene-exclave : https://en.wikipedia.org/wiki/Enclave_and_exclave

**Comment by teleaslamellatus** [comment]
That sounds really interesting and perhaps reflects much better the situation than encircle.

**Comment by matentzn** [comment]
Closing this as it seems @teleaslamellatus you have reflected on this issue.

**Comment by matentzn** [comment]
Please reopen if I am wrong!
