### ISSUE TITLE
Involved in regulation of vs. regulation 

### ISSUE THREAD

**Issue by pgaudet** [oborel/obo-relations#400]
Hi, 

I just realized we have both 'involved in regulation' and 'regulation' - 
**involved in regulation:** c involved in regulation of p if c is involved in some p' and p' regulates some p
**regulates**: process(P1) regulates process(P2) iff: P1 results in the initiation or termination of P2 OR affects the frequency of its initiation or termination OR affects the magnitude or rate of output of P2.

Do we really need both terms ? 

Thanks, Pascale

**Comment by vanaukenk** [comment]
@pgaudet 
Yes, I think RO does need both.

These relations have different parents:
**involved in regulation** is a causal relation between a material entity and a process
**regulates** is a causal relation between processes

Does that address your question?

**Comment by pgaudet** [comment]
So for gp2term we should use involved in regulation ? I dont think we do ?

**Comment by pgaudet** [comment]
or is it that we always link the MF to the BO so we dont use it ? 

In this case I wont add it to the GO subsets, right ?

**Comment by vanaukenk** [comment]
For gp2term we did not include 'involved in regulation' (or positive/negative children) on the list of allowed relations.

We decided to use 'involved in' and a regulation term in the ontology.

**Comment by pgaudet** [comment]
ok thanks
