### ISSUE TITLE
abandon has-curation-status

### ISSUE THREAD

**Issue by nlharris** [oborel/obo-relations#402]
In #143, @cmungall wrote:
> I think we need to abandon has-curation-status, it's not used consistently and meaningfully. Instead have links to tickets.

**Comment by nlharris** [comment]
Is this redundant with #283?

**Comment by bpeters42** [comment]
Discussed in the call 2/9/2021. There is an annotation property "term tracker item", http://purl.obolibrary.org/obo/IAO_0000233 . This could be used. Arguably that property should be in OMO. People on the call were of the opinion that this is not a direct replacement of curation status, and that it doesn't hurt to keep the status, but that we should regardless point to active tracker items as suggested here independent on retaining curation status or not.

**Comment by jamesaoverton** [comment]
IAO:0000233 is included in OMO.
