### ISSUE TITLE
Adapt standard github configurations and contribution documentation

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#404]
The ODK allows us to create a repo with standardized layouts for github issue templates, intstructions for contributors etc
https://github.com/INCATools/ontology-development-kit/

E.g.

https://github.com/INCATools/ontology-development-kit/blob/master/template/CONTRIBUTING.md.jinja2

(note this needs something about PRs)

We shoudl adapt for RO

**Comment by cmungall** [comment]
This is very out of date:

https://github.com/oborel/obo-relations/blob/master/CONTRIBUTING.md

**Comment by nlharris** [comment]
https://github.com/oborel/obo-relations/blob/master/CONTRIBUTING.md seems to have been updated in Feb 2021

**Comment by anitacaron** [comment]
ODK new term issue template is set.

**Comment by wdduncan** [comment]
Can this issue be closed?

**Comment by anitacaron** [comment]
I'll update the `CONTRIBUTING.md` using the template in ODK.
