### ISSUE TITLE
'bounds' in RO (http://purl.obolibrary.org/obo/fma#bounds)

### ISSUE THREAD

**Issue by teleaslamellatus** [oborel/obo-relations#407]
Shouldn't this OP be part of RO?

http://purl.obolibrary.org/obo/fma#bounds

We were told not to use taxon specific terms.

**Comment by balhoff** [comment]
I'm pretty sure this is [2D boundary of](http://purl.obolibrary.org/obo/RO_0002000).

**Comment by teleaslamellatus** [comment]
Thanks!
