### ISSUE TITLE
'contralateral to'

### ISSUE THREAD

**Issue by teleaslamellatus** [oborel/obo-relations#408]
Shouldn't this OP be part of RO?

http://purl.obolibrary.org/obo/BSPO_0000106

We used this OP to express if a structure is paired (e.g. antennae of insects are paired, so 

antenna SubClassOf 'contralateral to' exactly 1 antenna

Is there a reason why not all BSPO OP-s are in RO?

**Comment by teleaslamellatus** [comment]
Thanks! Do you know any other ways to express 'paired'?

**Comment by balhoff** [comment]
There's a bit of a pattern exhibited by Uberon [pair of lungs](http://purl.obolibrary.org/obo/UBERON_0000170). @cmungall anything to add about that?
