### ISSUE TITLE
new term: "co-roosting with", subtype of "ecologically co-occuring with"

### ISSUE THREAD

**Issue by jhpoelen** [oborel/obo-relations#419]
In recent discussions (see https://github.com/globalbioticinteractions/globalbioticinteractions/issues/583), it appears that co-roosting is an ecologically relevant interaction term especially for bats (Chiroptera). Suggest to add the co-roosting term as a "child" of the term ecologically co-occurs with.

**Comment by jhpoelen** [comment]
@balhoff @cmungall what is the most efficient way to introduce a term these days?

**Comment by balhoff** [comment]
I think PRs are very welcome, but the need to generate a term ID complicates things. I'm not set up for that. Do you have an ID range assigned to you? Or maybe @diatomsRcool does?

**Comment by jhpoelen** [comment]
@balhoff Thanks for your response!

As far as I know, I don't have an ID range assigned to me. What is the process for getting an ID range assigned? Happy to put in some work so that I do not have take time from others to create a pull request. However, as I am getting up to speed, I think I'd benefit from looking over the shoulder of a more experience contributors (like @diatomsRcool) as they prepare an example pull request for the proposed co-roosting RO term.

**Comment by jhpoelen** [comment]
fyi @qgroom

**Comment by balhoff** [comment]
I have a dream of eliminating the need for ID ranges :-) (https://github.com/ontodev/robot/issues/763). I'll probably implement that soon but it will be a while before getting into workflows. Hoping @cmungall can comment on handling ID ranges in the immediate term. Here are the folks who are set up to mint new IDs: https://github.com/oborel/obo-relations/blob/master/src/ontology/ro-idranges.owl

**Comment by cmungall** [comment]
go ahead and make a PR on ro-idranges.owl and just assign yourself an
unused block

**Comment by qgroom** [comment]
Here is a suggestion for a definition, please feel free to correct if you don't think this covers it.

The propensity for different species to actively congregate in the same place for rest or sleep

**Comment by jhpoelen** [comment]
An updated definition by Nancy Simmons - 

Bat Co-roosting:  Two or more bats (Order Chiroptera) sharing the same roost site (cave, mine, tree hollow, animal burrow, leaf tent, rock crack, space in man-made structure, etc.).

Note that this is different from birds co-roosting.

**Comment by cmungall** [comment]
Hmm, my immediate reaction is that this is excessive pre-composition, we could end up with subproperties named for many different taxa.

Can we not have a generic co-roosting relation? This should be defined in terms of an NBO class (which does not exist: https://www.ebi.ac.uk/ols/search?q=roost&ontology=nbo). Note: it would be up to the core RO developers to axiomatize this, we would not ask this of the relation submitter.

Then it would be the business of a separate ontology or knowledge base to contain knowledge about the ENVO classes in which particular species roost in. E.g.

|taxon|relation|envo|ref|
|---|---|---|---|
|ncbitaxon:chiroptera|roosts in|envo:cave|doi:123|
|ncbitaxon:gallus|roosts in|envo:chicken coop|doi:456|

**Comment by jhpoelen** [comment]
@cmungall I can see you point. 

Earlier, I proposed a generic co-roosting relation to a bat expert, Nancy Simmons. She described "co-roosting" in context of bats (a bat co-roosts with another bat) and "co-roosting" in context of birds as homonyms. They mean different things, so not just co-roosting in different contexts with different species, but different ecological relations altogether. This is why she settled on this definition and the unambiguous label. 

Nancy @nancybsimmons please meet Chris @cmungall , one of the editors/maintainer Relations Ontology. Hoping you can strike up a conversation to help vet the proposed "bat co-roosts with" term from biological and ontological angles.

**Comment by diatomsRcool** [comment]
Can we get a definition of co-roosting for birds and a definition for co-roosting for bats? That might help us tease apart these two relations.

**Comment by jhpoelen** [comment]
@diatomsRcool I much like you idea to get a better understanding of bat vs. bird co-roosting. Here's a document that related to the bat co-roosting - https://docs.google.com/document/d/1HjpHVdoPw8MVeL7CWYjf8IqB57CjdWQspRns1eIr7rs/edit . The document and related comments should give an impression of the difference between bat and bird roosting.

I am sure that Nancy @nancybsimmons or others have a lot to add on the subject.

**Comment by nancybsimmons** [comment]
Looks like we need to consider "communal roosting" as a more general phenomenon - https://en.wikipedia.org/wiki/Communal_roosting

**Comment by jhpoelen** [comment]
After some discussion, the proposed definition was updated to be more general. This means that separate roosting terms for bats and birds are no longer proposed.

(updated) proposed definition 

> Communal Roosting:  Two or more individuals sharing the same roost site (cave, mine, tree hollow, animal burrow, leaf tent, rock crack, space in man-made structure, etc.). 

where co-roosting is short for communal roosting. 

@cmungall @diatomsRcool thanks for chiming in and curious to hear your thoughts on the updated definition of co-roosting.

**Comment by diatomsRcool** [comment]
Will you want to label a taxon as being a synchronous, intraspecific, contact communal rooster? or some other compound term?

**Comment by jhpoelen** [comment]
For starters, I imagine we'll start with a single term for ```co-roosting``` and add additional terms if needed, but am open to thoughts of others in this thread.

**Comment by diatomsRcool** [comment]
OK, so it sounds like, for the moment, you just want to add "co-roosting with" to RO and root it in a "communal roosting" term in NBO. That seems reasonable to me.

**Comment by jhpoelen** [comment]
@diatomsRcool I had a ID range assigned and installed Protege. I tried to add a new term, but I got lost. Any chance you can show me how you add terms?

**Comment by diatomsRcool** [comment]
Oh sure. Let's find a time via email?

**Comment by jhpoelen** [comment]
Thanks to @cmungall @diatomsRcool  @arw36 @nancybsimmons @qgroom @balhoff @nlharris and others for helping to introduce RO's term "co-roosting" http://purl.obolibrary.org/obo/RO_0002801 .

It take a village . . . 

@arw36 already started using the term in her interaction dataset available via https://www.globalbioticinteractions.org/?accordingTo=globi%3Aarw36%2Fwilloughby-etal-2017-roost-interactions (see attached screenshots).
![Screenshot from 2021-03-18 10-52-21](https://user-images.githubusercontent.com/1084872/111675959-ef291780-87da-11eb-9e89-9996c5f5688d.png)
![Screenshot from 2021-03-18 10-51-45](https://user-images.githubusercontent.com/1084872/111675975-f05a4480-87da-11eb-8536-ca5c9fbeb93e.png)



![Screenshot from 2021-03-18 11-07-40](https://user-images.githubusercontent.com/1084872/111675938-ec2e2700-87da-11eb-9039-0ab6aadc019b.png)
