### ISSUE TITLE
BFO-2020 Temporalized Relations Review

### ISSUE THREAD

**Issue by neilotte** [oborel/obo-relations#420]
Is the RO organization reviewing the temporalized relations in BFO-2020 for adoption? Is there a plan to do so?

**Comment by phismith** [comment]
There is no RO organization
It is just the OBO foundry people.
They focus on relations relevant to biology and other relations get added
in through different, random means
We need to work on finding use cases for those relations eg in iof

**Comment by neilotte** [comment]
@phismith I'll re-direct my question then to the OBO foundry people who provide governance for the artifacts hosted on this GitHub site. 

There are articles on this site regarding the relationship of the RO to BFO and to time. Are the temporalized relations in BFO-2020 being reviewed by anyone here presently for adoption by the RO or an update to these articles?

**Comment by cmungall** [comment]
I'm not sure what barry means by it's just the obo foundry people. If there is a specific proposal please post a link here, being specific about how the relations would be implemented in OWL

**Comment by neilotte** [comment]
@cmungall 

 BFO 2.0 is no longer the latest version of BFO. BFO-2020 is the latest version. There are new relations published as part of BFO-2020. See https://github.com/BFO-ontology/BFO-2020/tree/master/21838-2/owl In particular, there are two versions of the relations being made available in BFO-2020. These are distinct from those released under earlier versions. 

I am wondering if you or others here have reviewed these, and if you plan to do so. I am particularly interested in your opinion on this matter, since I believe it was [your critique of the earlier version](https://github.com/cmungall/trel-crit/raw/master/trc.pdf) of the temporalized relations that was cause for dropping them.

**Comment by cmungall** [comment]
Hi Neil, I wasn't aware that this repo existed - great! but it hasn't been announced on the bfo list, and is not linked from either the existing github repo or from the main BFO website. You say BFO-2020 is the latest version, but this confuses me. The version that is on OBO, OLS, BioPortal, OntoBee and everywhere else is still BFO2 as far as I can tell. The version registered in OBO and that is evaluated in the dashboard is BFO2.0. None of the new PURLs in the BFO-2020 ontology resolve. 

Is this really the latest version? Note that as an ontology within OBO, BFO should follow OBO principles. One of these is retaining PURLs. BFO 2.0 has PURLs like http://purl.obolibrary.org/obo/BFO_0000144 "process profile" but these are not present in BFO-2020. We never delete PURLs - We would create an obsoletion record. Also in this particular case, this could be a major breaking change for users. I strongly encourage you to engage with your user community, advertise this change in advance and give your users clear migration instructions. Note you will also want to preserve ontology PURLs, such as the one for the classes-only version of BFO that many people use. 

I haven't checked if there are any other breaking changes. But it's customary to include some kind of Changes notice when making a new release of a software/ontology, this is especially important for when breaking changes have been introduced.

I might also suggest including a bit more documentation with BFO-2020. The repo is a bit sparse on docs.

You will now have two repos. Which one should bfo issues be tracked on?

It seems like you have a bit of work ahead of you in making BFO-2020 release-ready. Other members of OBO may be able to help you with this, we have a lot of tooling now like ODK and ROBOT to help you.

Once the actual release status is clarified let's return here. I suggest we close this issue, and when ready you can make a more specific request. I'm not sure what exactly is entailed in a request for a review, from me or others, or how the comments in my 2013 review are to be addressed.

What is the request of RO specifically? Is it to import the BFO-2020 relations? To replace existing relations with these? To use the same patterns for the 100s of relations in RO? (and if so, what tools are there to help us do this). Help us see what you think is the path forward.

**Comment by cmungall** [comment]
It looks like the PURLs in BFO 2020 still don't resolve, e.g. http://purl.obolibrary.org/obo/BFO_0000136

And it looks like this file still has the temporarlized versions
https://raw.githubusercontent.com/BFO-ontology/BFO-2020/master/21838-2/owl/bfo-2020-without-some-all-times.owl
