### ISSUE TITLE
Requesting ID range 

### ISSUE THREAD

**Issue by pgaudet** [oborel/obo-relations#422]
Hi @cmungall 

Can I also get an ID range for RO ? I used RO_0012000 to RO_0012007 until now 

Thanks, Pascale

**Comment by cmungall** [comment]
go ahead and make the PR!

**Comment by matentzn** [comment]
It seems like you have an id range! 
https://github.com/oborel/obo-relations/blob/82cab564ddc54826fb491a63db558fca4bce95f2/src/ontology/ro-idranges.owl#L64

Please reopen if that is not what you were looking for..assuming you are pg.
