### ISSUE TITLE
problematic domain for 'relation between physical entity and a process or stage'

### ISSUE THREAD

**Issue by balhoff** [oborel/obo-relations#423]
[relation between physical entity and a process or stage](http://purl.obolibrary.org/obo/RO_0002487) has two domains:
- [independent continuant](http://purl.obolibrary.org/obo/BFO_0000004) --_seems fine_
- [material anatomical entity](http://purl.obolibrary.org/obo/CARO_0000006) or [immaterial anatomical entity](http://purl.obolibrary.org/obo/CARO_0000007) --_not good_

Any objections to just deleting the second domain?

**Comment by balhoff** [comment]
@dosumis any idea where that came from? It's using CARO terms.

**Comment by nlharris** [comment]
@dosumis not sure if you saw this question?
