### ISSUE TITLE
Does characteristic of need to be functional?

### ISSUE THREAD

**Issue by wdduncan** [oborel/obo-relations#452]
At the last RO meeting (March 2021), I it was decided that `characteristic of` should be a `functional` object property; meaning that if the instance`quality#1` is a `characteristic of` two other instances like so:
```
quality#1 characteristic-of instance#1, instance#2 
```
then `instance#1`, `instance#2`  are the same individuals.

Not trying to start a controversy, but do we need `characteristic of` to be that "strong". I'm not seeing the practical benefit, and conversely, I'm not seeing the risk of not having it `functional`.

If we need a characteristic to apply to anatomical regions that encompass multiple body parts (e.g, head & neck), this is still possible if `characteristic of` is not functional and you don't need to create a `head & neck` anatomical entity.

Do users need to leverage the inferencing power of `functional` for error checking or inferring same-as?

**Comment by matentzn** [comment]
Yeah its a good question. I would say the main benefit is quality control (in a well-axiomised ontology (disjointness complete), you will get a warning when trying to associate a quality with multiple entities), which I think is good. And I guess this was the whole purpose of this: keeping people from associating multiple entities with the same quality?

**Comment by wdduncan** [comment]
Yes ... I can see that, but I wondering how practical that is since it requires disjointness to hold characterized entities.

**Comment by matentzn** [comment]
at least some branches are well disjointed in Uberon. I guess the question here is now: if it has a bit of an advantage, why would we not make it functional? Are you worried it will lead to uncaught faulty inferences? Or why do you suggest to make it less strong?

**Comment by wdduncan** [comment]
My main reason is that it requires more complex axioms to get the inferences you mention. E.g.: you have to declare things disjoint if want to detect errors, and if you don't declare things as disjoint a developer may inadvertently reason to entities to be the same.

This is not necessarily a bad thing ... it just adds level of complexity to properly using the `characteristic of` relation. You can (of course) declare `characteristic of` relation to be functional during testing time to check for incoherencies.

**Comment by matentzn** [comment]
Yeah ok, makes sense.. My position is: if there is no harm in having it functional, but some small benefits from doing it, I would do it. But I will follow @cmungall on this..

**Comment by wdduncan** [comment]
Sure ... I'm not sure if there is harm or not. I'm thinking of cases like "pain being present in the foot and calf" or "discoloration present in the abdomen and chest area". If you use `characteristic of` to relate pain/discoloration to the different anatomical regions you may get unwanted inferences. You can (of course) argue that pain/discoloration aren't qualities (that's a different discussion).

**Comment by matentzn** [comment]
Yeah, I hear you, I am not too convinced here of anything. In my view, they would simply be different qualities.

**Comment by wdduncan** [comment]
Not going to delve into the debate concerning the number of qualities :)

But, I would note that specifying `characteristic of` as functional forces the issue of deciding how many qualities there are (or I supposed you can declare an entity that is mereological sum of the anatomical entities).

**Comment by cmungall** [comment]
I don't think we need to reopen this, we discussed this on the 2019-07-30 RO call https://docs.google.com/document/d/19dhzj5QoliQZQgDJRczI878rLtexzMDo1g0K9_LRUWk/edit#

I think the onus needs to be on saying why it should not be functional. I can't think of any examples. Note for so called relational qualities we use a separate relation to connect to the second entity. We get huge error checking benefits from a stricter relation.

For the head+neck case, we can talk about the craniocervical region if we want a union, or if we want to say the head and neck both have a particular characteristic we can make two characteristic instances c1-in-neck c2-in-head and optionally a mereological sum c3 = c1 + c2.
