### ISSUE TITLE
bridge CHEBI:role to BFO:role

### ISSUE THREAD

**Issue by balhoff** [oborel/obo-relations#467]
In GO there is an axiom: [role](http://purl.obolibrary.org/obo/BFO_0000023) EquivalentTo [role](http://purl.obolibrary.org/obo/CHEBI_50906)

This equates the role class in CHEBI to the one used in RO, and catches cases when chemical roles (specifically dependent continuants) are accidentally used as chemicals (material entities).

When I merge several OBO ontologies together, like GO, Uberon, MP, and HP, I often run into disjointness violations with use of chemical roles. Generally this is because this bridging axiom is randomly placed in GO and not imported into other ontologies.

Can we add this axiom to RO? It would be nice to have this shared across all these ontologies. Maybe this will be the sort of thing COB is used for down the road, but this is an immediate problem and RO is a nice central place.

I'm putting an example explanation for one of these problems in the next comment.

**Comment by balhoff** [comment]
## [aminoaciduria](http://purl.obolibrary.org/obo/MP_0003311) EquivalentTo [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [aminoaciduria](http://purl.obolibrary.org/obo/MP_0003311) SubClassOf [aciduria](http://purl.obolibrary.org/obo/MP_0010028)
    - [aciduria](http://purl.obolibrary.org/obo/MP_0010028) EquivalentTo [has part](http://purl.obolibrary.org/obo/BFO_0000051) some 
([increased amount](http://purl.obolibrary.org/obo/PATO_0000470) and ([inheres in](http://purl.obolibrary.org/obo/RO_0000052) some 
([acid](http://purl.obolibrary.org/obo/CHEBI_37527) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [urine](http://purl.obolibrary.org/obo/UBERON_0001088)))) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [abnormal](http://purl.obolibrary.org/obo/PATO_0000460)))
      - [acid](http://purl.obolibrary.org/obo/CHEBI_37527) SubClassOf [chemical role](http://purl.obolibrary.org/obo/CHEBI_51086)
        - [chemical role](http://purl.obolibrary.org/obo/CHEBI_51086) SubClassOf [role](http://purl.obolibrary.org/obo/CHEBI_50906)
          - [role](http://purl.obolibrary.org/obo/BFO_0000023) EquivalentTo [role](http://purl.obolibrary.org/obo/CHEBI_50906)
            - [role](http://purl.obolibrary.org/obo/BFO_0000023) SubClassOf [realizable entity](http://purl.obolibrary.org/obo/BFO_0000017)
              - [realizable entity](http://purl.obolibrary.org/obo/BFO_0000017) SubClassOf [specifically dependent continuant](http://purl.obolibrary.org/obo/BFO_0000020)
      - [urine](http://purl.obolibrary.org/obo/UBERON_0001088) EquivalentTo [excreta](http://purl.obolibrary.org/obo/UBERON_0000174) and ([produced by](http://purl.obolibrary.org/obo/RO_0003001) some [kidney](http://purl.obolibrary.org/obo/UBERON_0002113))
        - [excreta](http://purl.obolibrary.org/obo/UBERON_0000174) EquivalentTo [organism substance](http://purl.obolibrary.org/obo/UBERON_0000463) and ([output of](http://purl.obolibrary.org/obo/RO_0002353) some [excretion](http://purl.obolibrary.org/obo/GO_0007588))
          - [organism substance](http://purl.obolibrary.org/obo/UBERON_0000463) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [multicellular organism](http://purl.obolibrary.org/obo/UBERON_0000468)
            - [multicellular organism](http://purl.obolibrary.org/obo/UBERON_0000468) SubClassOf [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000)
              - [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000) EquivalentTo [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) and ([has quality](http://purl.obolibrary.org/obo/RO_0000086) some [multicellular](http://purl.obolibrary.org/obo/PATO_0001993))
                - [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) SubClassOf [existence starts during or after](http://purl.obolibrary.org/obo/RO_0002496) some [zygote stage](http://purl.obolibrary.org/obo/UBERON_0000106)
                  - [existence starts during or after](http://purl.obolibrary.org/obo/RO_0002496) SubPropertyOf: [relation between physical entity and a process or stage](http://purl.obolibrary.org/obo/RO_0002487)
                    - [relation between physical entity and a process or stage](http://purl.obolibrary.org/obo/RO_0002487) Domain [independent continuant](http://purl.obolibrary.org/obo/BFO_0000004)
  - [part of](http://purl.obolibrary.org/obo/BFO_0000050) o [existence starts during or after](http://purl.obolibrary.org/obo/RO_0002496) SubPropertyOf: [existence starts during or after](http://purl.obolibrary.org/obo/RO_0002496)
  - [independent continuant](http://purl.obolibrary.org/obo/BFO_0000004) DisjointWith [specifically dependent continuant](http://purl.obolibrary.org/obo/BFO_0000020)

# Axiom Impact 
## Axioms used 1 times
- [role](http://purl.obolibrary.org/obo/BFO_0000023) EquivalentTo [role](http://purl.obolibrary.org/obo/CHEBI_50906) [go-base.owl]
- [aciduria](http://purl.obolibrary.org/obo/MP_0010028) EquivalentTo [has part](http://purl.obolibrary.org/obo/BFO_0000051) some 
([increased amount](http://purl.obolibrary.org/obo/PATO_0000470) and ([inheres in](http://purl.obolibrary.org/obo/RO_0000052) some 
([acid](http://purl.obolibrary.org/obo/CHEBI_37527) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [urine](http://purl.obolibrary.org/obo/UBERON_0001088)))) and ([has modifier](http://purl.obolibrary.org/obo/RO_0002573) some [abnormal](http://purl.obolibrary.org/obo/PATO_0000460))) [mp-base.owl]
- [excreta](http://purl.obolibrary.org/obo/UBERON_0000174) EquivalentTo [organism substance](http://purl.obolibrary.org/obo/UBERON_0000463) and ([output of](http://purl.obolibrary.org/obo/RO_0002353) some [excretion](http://purl.obolibrary.org/obo/GO_0007588)) [uberon-base.owl]
- [urine](http://purl.obolibrary.org/obo/UBERON_0001088) EquivalentTo [excreta](http://purl.obolibrary.org/obo/UBERON_0000174) and ([produced by](http://purl.obolibrary.org/obo/RO_0003001) some [kidney](http://purl.obolibrary.org/obo/UBERON_0002113)) [uberon-base.owl]
- [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000) EquivalentTo [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) and ([has quality](http://purl.obolibrary.org/obo/RO_0000086) some [multicellular](http://purl.obolibrary.org/obo/PATO_0001993)) [uberon-base.owl]
- [realizable entity](http://purl.obolibrary.org/obo/BFO_0000017) SubClassOf [specifically dependent continuant](http://purl.obolibrary.org/obo/BFO_0000020) [bfo-classes-minimal.owl]
- [role](http://purl.obolibrary.org/obo/BFO_0000023) SubClassOf [realizable entity](http://purl.obolibrary.org/obo/BFO_0000017) [bfo-classes-minimal.owl]
- [acid](http://purl.obolibrary.org/obo/CHEBI_37527) SubClassOf [chemical role](http://purl.obolibrary.org/obo/CHEBI_51086) [chebi.owl]
- [chemical role](http://purl.obolibrary.org/obo/CHEBI_51086) SubClassOf [role](http://purl.obolibrary.org/obo/CHEBI_50906) [chebi.owl]
- [aminoaciduria](http://purl.obolibrary.org/obo/MP_0003311) SubClassOf [aciduria](http://purl.obolibrary.org/obo/MP_0010028) [mp-base.owl]
- [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) SubClassOf [existence starts during or after](http://purl.obolibrary.org/obo/RO_0002496) some [zygote stage](http://purl.obolibrary.org/obo/UBERON_0000106) [uberon-base.owl]
- [organism substance](http://purl.obolibrary.org/obo/UBERON_0000463) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [multicellular organism](http://purl.obolibrary.org/obo/UBERON_0000468) [uberon-base.owl]
- [multicellular organism](http://purl.obolibrary.org/obo/UBERON_0000468) SubClassOf [multicellular anatomical structure](http://purl.obolibrary.org/obo/UBERON_0010000) [uberon-base.owl]
- [independent continuant](http://purl.obolibrary.org/obo/BFO_0000004) DisjointWith [specifically dependent continuant](http://purl.obolibrary.org/obo/BFO_0000020) [bfo-axioms.owl]
- [existence starts during or after](http://purl.obolibrary.org/obo/RO_0002496) SubPropertyOf: [relation between physical entity and a process or stage](http://purl.obolibrary.org/obo/RO_0002487) [ro.owl]
- [relation between physical entity and a process or stage](http://purl.obolibrary.org/obo/RO_0002487) Domain [independent continuant](http://purl.obolibrary.org/obo/BFO_0000004) [ro.owl]
- [part of](http://purl.obolibrary.org/obo/BFO_0000050) o [existence starts during or after](http://purl.obolibrary.org/obo/RO_0002496) SubPropertyOf: [existence starts during or after](http://purl.obolibrary.org/obo/RO_0002496) [uberon-base.owl,ro.owl]



# Ontologies used: 
- bfo-axioms.owl (http://purl.obolibrary.org/obo/ro/bfo-axioms.owl)
- uberon-base.owl (http://purl.obolibrary.org/obo/uberon/uberon-base.owl)
- chebi.owl (http://purl.obolibrary.org/obo/chebi.owl)
- bfo-classes-minimal.owl (http://purl.obolibrary.org/obo/ro/bfo-classes-minimal.owl)
- go-base.owl (http://purl.obolibrary.org/obo/go/go-base.owl)
- mp-base.owl (http://purl.obolibrary.org/obo/mp/mp-base.owl)
- ro.owl (http://purl.obolibrary.org/obo/ro.owl)

**Comment by matentzn** [comment]
One question we should look at before I fully endorse this is why exactly the axiom is not imported from go. Is it in go or go plus?

**Comment by balhoff** [comment]
It's in `go-base.owl` (and `go-plus.owl`). It's not in `go.owl`; I don't think folks should be importing from `go.owl` if they're doing cross-ontology work, because it filters out all external references.

**Comment by matentzn** [comment]
So maybe that’s the right thing to do, move to go plus across the board? Is
there anything speaking against that?

**Comment by cmungall** [comment]
@matentzn not sure I follow - @balhoff said it was in go-plus already?

But in any case, I think this is moot, it doesn't belong in GO. See:  https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1443 (and see my comment from 3 days ago about the relationship between injected axioms and base files, which seems to me to be undefined).

I like Jim's pragmatic suggestion of moving this to RO. Obviously CHEBI is the correct place, but we know that it is hard for CHEBI to provide axioms like this. RO is a good substitute as it is fairly central. I think we should follow the practice recommended in the injection ticket, and tag it as an intentional injection, and we could get CHEBI's "signature" on it.

But let's look at the deeper problem here: over-enthusiasm in use of BFO. We are constantly seeing these kinds of issues caused by over-used of BFO classes instead of plain common-sense classification. One characteristic of these issues is that the tests to find them are highly brittle (as is in evidence here), and frequently manifest themselves downstream where they become hard and costly to debug.

Let's look at this example with CHEBI modeling "acid" as a role. If we were following common-sense, we would model "acid" as a chemical entity and not a role, as per every definition of acid, ever, e.g

 - https://goldbook.iupac.org/terms/view/A00071
 - https://en.wikipedia.org/wiki/Acid

In fact even the text definition in CHEBI itself says this is a molecular entity:

 - https://www.ebi.ac.uk/ols/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_37527
     - An acid is a **molecular entity** _capable of_ donating a hydron (Bronsted acid) or capable of forming a covalent bond with an electron pair (Lewis acid).

If ontologies really want to over-ontologize and represent ordinary things using confusing BFO classes, this should be clearly signified in both the label and the definition. E.g. "acid role". But really the most sensible thing to do here is just model it consistent with the text definition: a molecular entity that is capable of X.

It's time we in OBO stopped setting ourselves pointless crossword puzzle reasoning exercises that consume a lot of time and energy and focused on solving real problems. We must simplify our ontologies and avoid pointless costly abstractions that don't solve actual biologists' needs.

**Comment by balhoff** [comment]
@cmungall I totally agree with your points. However it seemed a lower barrier task to slip this axiom into RO rather than ask for a reworking of the CHEBI hierarchy. 😅 But probably we've been avoiding the real issue for too long. Given that experienced ontology editors make this "mistake" over and over again, it's probably not the right model.

Do you think the situation is as clear-cut for "hormone"? That's another one which frequently causes trouble.

**Comment by matentzn** [comment]
I agree with all you say: fwiw, my whole point was that maybe, instead of
pulling from go.owl, all our ontologies that refer to go should instead use
go-plus; but obviously yeah your points go much deeper than that. so then,
so what should we do then? organise meeting with chebi and ask them to
reconsider the role branch?

**Comment by cthoyt** [comment]
@balhoff I brought this up again in the COB repo here https://github.com/OBOFoundry/COB/issues/169

**Comment by dosumis** [comment]
> Instead of pulling from go.owl, all our ontologies that refer to go should instead use
go-plus

I strongly support this.  It will massively improve integration and co-ordination. It is particularly important for phenotype ontologies where patterns commonly define compound entities using GO-consistent patterns.

**Comment by dosumis** [comment]
On the broader ticket - it makes sense for bridging axioms such as the one discussed in this ticket to live in an upper ontology.   Not sure whether it makes sense for them to live only in COB - forcing any ontology who wants it to adopt broader COB commitments.

**Comment by balhoff** [comment]
It happened again (https://github.com/obophenotype/human-phenotype-ontology/issues/7224) so I opened a PR: #528

**Comment by cmungall** [comment]
This is already in COB

https://github.com/OBOFoundry/COB/blob/a2f7141c1e30e87352cb656a224fd31027d92701/src/ontology/components/cob-to-external.tsv#L107-L108

**Comment by cmungall** [comment]
Was fixed by @cthoyt in https://github.com/OBOFoundry/COB/pull/173

**Comment by nlharris** [comment]
So can this be closed now?
