### ISSUE TITLE
Broaden definition of ‘disease arises from structure’ (RO:0004030) 

### ISSUE THREAD

**Issue by sabrinatoro** [oborel/obo-relations#469]
We want to axiomatize chromosomal anomalies in MONDO (MONDO:0019040) by associated diseases to the chromosome/chromosome part affected.  

We think that we could use ‘disease arises from structure’ (RO:0004030) to create these axioms, however the current definition of this relation would have to be broaden.

The current definition specify that the relationship is between a disease and an anatomical structure 
(Definition: A relationship between a disease and an anatomical structure where the material basis of the disease is some pathological change in the structure.)

We suggest that the definition be broaden such that the relationship would be between a disease and an anatomical structure or cellular anatomical structure (which would include chromosome and part of chromosome).

**Comment by sabrinatoro** [comment]
@cmungall This is based on our discussion on the Mondo curation call. Please advise with the definition wording. Thank you!

**Comment by cmungall** [comment]
I agree with broadening the range. Of course, "anatomical structure" can be fuzzy but we generally draw the line above protein complexes.

**Comment by cmungall** [comment]
GO does consider chromosomes to be cellular anatomical entities, but I agree it is confusing, we can at least change the wording

We should change the ranges in RO from CARO to COB at some point
