### ISSUE TITLE
Remove fossilised slices of external ontologies from RO

### ISSUE THREAD

**Issue by dosumis** [oborel/obo-relations#473]
RO has some horribly stale imports

![image](https://user-images.githubusercontent.com/112839/127850516-29170266-b368-4e2f-ae3f-28615520988d.png)

![image](https://user-images.githubusercontent.com/7070631/127841130-64497cc6-7553-4425-9470-1fab18c9c6fd.png)

These have to go!

Suggest - replace with dynamic import of single terms.  @cmungall - do you think this would be sufficient?

see also: #472

**Comment by cmungall** [comment]
Made a specific ticket #474 for the symbiosis branch

**Comment by nlharris** [comment]
Is this done?

**Comment by matentzn** [comment]
Will be by #492

**Comment by anitacaron** [comment]
The RO migration to ODK was finished, so closing this issue.
