### ISSUE TITLE
NTR: Has exposure medium 

### ISSUE THREAD

**Issue by laurenechan** [oborel/obo-relations#477]
@diatomsRcool @cmungall 

Hello,
Within the Environmental Conditions, Treatments, and Exposures Ontology (ECTO) we are using the higher level model of Exposure Ontology (ExO) to develop our exposure event classes. This includes documenting the route, stressor, and medium of the exposure when available. 
We are currently using relations including 'has exposure stressor' and 'has exposure receptor', but we do not have a relation for 'has exposure medium'. 

We propose the following details for this term:
Label: has exposure medium
Parent: related via exposure (RO:0002244)
Definition: A broad relationship between an exposure event or process and any entity (e.g., an organism or environmental substance) through which something else is transmitted or carried during an exposure event.
Definition source: ExO_0000083

**Comment by laurenechan** [comment]
I'm wondering if the 'occurs in' object property would give the impression that the exposure is occurring in a specific location or medium. 
Exposure medium is defined in ExO as 'a substance through which something else is transmitted or carried during an exposure.', with some examples being soil, water, air, and food. Exposure mediums provide information about what entity is containing the exposure stimulus. I don't think this means the medium encompasses the location of the actual exposure itself whether that be a physical location or even that the exposure is happening in the medium being documented.

**Comment by mellybelly** [comment]
Could be a subproperty?

**Comment by laurenechan** [comment]
The exposure medium is not intended to pick out the location where the exposure occurs (e.g. lungs vs air vs room), but rather denote the entity that is allowing for the stimulus to be transmitted to the actual site of the exposure. So in your example, the medium would be air, stimulus is the smoke, and the location of the exposure is the lungs (because you and your lungs are the exposure receptor).

**Comment by laurenechan** [comment]
Hmm we currently use the second approach offered, but I wonder if it would be more meaningful to assign the medium to the stimulus itself instead of the exposure event generally? thoughts @diatomsRcool ?

Also spitballing on the first proposal, 
If we had the stimulus and medium packaged up together so to say, and then you had a second stimulus and the same medium packaged up, that might allow us to showcase simultaneous exposures within one exposure event without a mixture. Would that be of interest to us? For example if you have general pollution in the air that you breathe in, but you also have welding fumes at your work that you breathe. Two mixtures that are not technically one super big mixture, could we represent them as simultaneous exposures to separate stimuli within the same medium? 
Would also be interesting for nutrient exposures in food.

**Comment by wdduncan** [comment]
You can also have relations for both situations:
- `has stimulus medium` (the label needs work ...)
- `has exposure medium`

For the definition of `has exposure medium`, I suggest something like:

X `has exposure medium` Y means X is an exposure event (process), Y is an environmental material (maybe add more things that Y could be?), and the stimulus for X is transmitted or carried in Y.

**Comment by diatomsRcool** [comment]
@laurenechan that is essentially what we do because the assigning of the medium and the route is a part of the class itself. Exposure to mercury in food via ingestion is a separate class from exposure to mercury in air via inhalation. 
@wdduncan we do need something to link the stimulus to some sort of environmental material be it soil, air, food, water, etc. We don't really have need to talk about the actual location in which an exposure occurs - at least not yet. We may later get a use case where that is needed. The "receptor" is the lung or the organism or however specific you want to get. 
As I'm writing this, I'm realizing that the use case for this may be socioeconomic status, like exposure to lead in water via ingestion and the "occurs in" would be an economically depressed neighborhood.

**Comment by wdduncan** [comment]
Thanks @diatomsRcool   
In the definition I posted I only explicitly mention the stimulus being transmitted within an environmental material. I do not know if you want to include other media for transmission. @laurenechan original proposed definition also mentions organisms as being another such media.

**Comment by laurenechan** [comment]
I think @diatomsRcool is correct and maybe we should omit the mention of organisms being a potential medium as to avoid confusion for what the medium is actually supposed to represent as opposed to the receptor. 
So then your revised definition @wdduncan I think is appropriate.

**Comment by wdduncan** [comment]
Great!  
I think the definition still needs some clean up ... @laurenechan do you want to revise?

**Comment by laurenechan** [comment]
Revising my initial definition proposal,

Relation label: has exposure medium
Parent: related via exposure (RO:0002244)
Definition: A relationship between an exposure event or process and any entity (e.g., an environmental substance) through which a stimulus is transmitted or carried during an exposure event.
Definition source: ExO_0000083

Doesn't seem to particularly different, but removes organism from the example entities (although I am still thinking about whether there could be a separate organism/organism substance outside the receptor that could serve as a medium, maybe contaminated honey?). I've also strictly included stimulus int he definition as the entity being transmitted through the medium. Were you looking for other revisions as well @wdduncan ?

**Comment by wdduncan** [comment]
I don't know what the standards are regrading how definitions are to be written in RO. I often write definitions in the form:
```
X R Y means that X is a C1 and Y is C2 ...  
```
to make it painstakingly clear what the domains and ranges are. Also, it makes the definition a bit more formal.

I see a lot of variety in how definitions are written in RO, though. Perhaps @matentzn  knows if there are guidelines about how definitions should be submitted to RO?

**Comment by laurenechan** [comment]
I was using the other relations under the 'related via exposure to' branch as examples which don't have that format, but I think you are right @wdduncan , it seems like other relations use that format. I just slightly modified your proposed definition from above:

X has exposure medium Y if X is an exposure event (process), Y is a material entity or food material, and the stimulus for X is transmitted or carried in Y.

@diatomsRcool can you confirm whether or not we need further options for what Y can be? We only use terms from ENVO and FoodOn as media at this point, but if we want the definition to range further we can add that now.

**Comment by laurenechan** [comment]
@diatomsRcool did you have any comments on this or should I go ahead and create a pull request for this relation?

**Comment by diatomsRcool** [comment]
I think this is fine. Isn't food material a material entity?

**Comment by laurenechan** [comment]
@diatomsRcool yes, it is, shall we pare down to just 'Y is a material entity' then?

**Comment by diatomsRcool** [comment]
yes - then its fine
