### ISSUE TITLE
Using 'has phenotype' without a 'has disease' relationship

### ISSUE THREAD

**Issue by laurenechan** [oborel/obo-relations#478]
I am currently working on a schema to document environmental exposures at an instance level and am hoping to include a relationship between a "human individual" and a disease (for example a Mondo term). As I was developing this schema, I realized there is not currently a relationship 'has disease' that I can use to connect my individual person and their presenting disease for this instance.
I believe 'has phenotype' could be used in this scenario, but would it be appropriate to have a distinct 'has disease' relation to use? 

@cmungall

**Comment by cmungall** [comment]
I propose

 * has associated phenotype or disease NEW
     * has phenotype
     * has disease NEW

The domain intentionally broad as per has phenotype

**Comment by matentzn** [comment]
@laurenechan do you want to try to implement the proposed? I can help you on slack..

**Comment by nlharris** [comment]
@laurenechan did you get what you needed from Nico?

**Comment by ddooley** [comment]
Looks like this was implemented in RO, and issue should have been closed. Doing so now.
