### ISSUE TITLE
add 'has occurrent part' as inverse of 'occurrent part of' 

### ISSUE THREAD

**Issue by StroemPhi** [oborel/obo-relations#486]
There is no RO term for "has occurent part" which is the inverse of [ro:"occurent part of"](http://purl.obolibrary.org/obo/RO_0002012) but it is defined as such in TXPO ([TXPO_0002523](http://purl.obolibrary.org/obo/TXPO_0002523)). 
In order to prevent others from defining this in their own ontology, as they might not find (or look for) it in TXPO, I propose to:
- [ ]  add this inverse relation to RO 
- [ ] and then ask the TXPO maintainers to make TXPO_0002523 obsolete

**Comment by cthoyt** [comment]
I think there is discussion about a similar issue when dealing with has part / part of relations on occurrents in https://github.com/oborel/obo-relations/issues/489

**Comment by StroemPhi** [comment]
@cthoyt I don't think this is related to #489, as this is dealing with relations between continuants and occurents and the ones mentioned here are only limited to occurents in the domain and range.

**Comment by StroemPhi** [comment]
Also noteworthy, this relation is already in BFO 2.0 with the id [BFO_0000117](https://www.ontobee.org/search?ontology=&keywords=has+occurrent+part&submit=Search+terms), which is used by quite a few ontologies. however the BFO purl will resolve to the class only version, so this one cannot be resolved. Idk what's the most appropriate way to go, whether pulling BFO_0000117 into RO like 'has part' or to mint a new term.

**Comment by dosumis** [comment]
Makes sense to me to add inverse in RO.

**Comment by StroemPhi** [comment]
Just found https://github.com/oborel/obo-relations/issues/518. I don't really understand waht "if it [[ro:"occurrent part of"](http://purl.obolibrary.org/obo/RO_0002012)] is used e.g. in logical defs it will lead to cryptic lack of entailments unless complex rolification axioms used" means. But if this relation will be deleted than my NTR does not make any sense anymor. However, I think we need more clarification on why there should not be a subproperty of "part of" that is restricted to occurrents

**Comment by wdduncan** [comment]
One place to find BFO's `occurrent part of` (obo:BFO_0000132) is in the BFO-2020 OWL File (see [here](https://github.com/BFO-ontology/BFO-2020/tree/master/21838-2/owl)). Unfortunately, it doesn't seem that BFO-2020's terms are associated with a term lookup service (e.g., Ontobee, EBI/OLS).  

My memory is hazy about the reasons why only a classes version was released for BFO 2. I think agreement was just never reached about which relations should be included in BFO 2 (namely, there was a lot of debate over temporal relations).  

In the [bfo_ro.owl](https://github.com/BFO-ontology/BFO2/blob/master/ontology/src/bfo_ro.owl) file, `occurrent part of` is not included either.

**Comment by cmungall** [comment]
This is a really important point. There is more on

**Comment by StroemPhi** [comment]
Thank you @cmungall for clarifying with the link. I can now see why #518 was opened and I would have no objections to withdraw my NTR.
I just wanted to mention, that this matter should then probably get more publicity. Because using OLS' [also in feature](https://www.ebi.ac.uk/ols/search?q=part+of+occurrent&groupField=iri&start=0&type=property), we can see that currently 9 ontologies reuse ro:"occurent part of", 15+ reuse its unresolvable BFO equivalent ("part of occurrent") as well as its inverse.

**Comment by wdduncan** [comment]
> I would have no objections to withdraw my NTR

Do you want to close this as "not planned"?

**Comment by StroemPhi** [comment]
Yes, this can be closed and I will do so with this comment. 
I just think that part of resolving #518 would be to somehow announce this change broadly enough to the OBO based RO users and also refer that this somehow also entails the unresolvabel BFO equivalent relations.

**Comment by cmungall** [comment]
Great point. And to clear I am not unilaterally ruling out continuing these
but I want us all to be aware of interoperability impacts before making a
consensus decision

**Comment by StroemPhi** [comment]
The other option I see would be to keep these relations in RO (mint an inverse), map them to their BFO 2020 equivalent and put a big fat comment annotation on them that points to the RO docs to make sure they are used consistently if ever in logical definitions.
