### ISSUE TITLE
deal with missing BFO:has_part

### ISSUE THREAD

**Issue by GoogleCodeExporter** [oborel/obo-relations#49]
```
the current release has many object properties that hold over BFO:0000051 
(has_part), but this seems to be missing from BFO now:

http://purl.obolibrary.org/obo/BFO_0000051

this needs to get fixed asap!
```

Original issue reported on code.google.com by `nicole.l...@gmail.com` on 4 Mar 2015 at 11:39

**Comment by nlharris** [comment]
The URL above still doesn't work, though http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/BFO_0000051 does. Does this need to get fixed?

**Comment by jamesaoverton** [comment]
This works http://purl.obolibrary.org/obo/BFO_0000051

Because of https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/obo.yml#L27
