### ISSUE TITLE
stings

### ISSUE THREAD

**Issue by qgroom** [oborel/obo-relations#493]
There seems no relation that covers defensive attacks, such as stinging or biting. This might not result in the death of either organism, but is a relation and can have consequences. Both plants and animals can sting, but because plants do this passively I wonder if these should be be considered differently.

**Comment by ddooley** [comment]
Isn't this best modelled as a  "stinging process"?  Tho in OBI modelling it raises the question of whether the organism doing the stinging (and providing the stinger as input to the process!) can also be considered the performer of the process!
Object property heavy ontologies create  shortcut relations for every process imaginable but this usually skips over parts that other research finds useful, e.g. what happens to the stinger, or whether venom is imparted, etc.
