### ISSUE TITLE
Request for new relationship to connect unprocessed miRNA to mature miRNA

### ISSUE THREAD

**Issue by cthoyt** [oborel/obo-relations#495]
I'm converting miRBase to OBO with this script https://github.com/pyobo/pyobo/blob/master/src/pyobo/sources/mirbase.py. Each miRNA transcript in the [mirbase](https://bioregistry.io/mirbase) idspace is processed into a 3-prime and 5-prime mature miRNA in the [mirbase.mature](https://bioregistry.io/mirbase.mature) idspace.

Example for cel-let-7 ([mirbase:MI0000001](https://bioregistry.io/mirbase:MI0000001)). You can see I used `obo` as a namespace for a relationship `has_mature`, obviously `obo` isn't appropriate here, and ideally we could add an RO relation for this.

```
[Term]
id: mirbase:MI0000001
name: cel-let-7
def: "Caenorhabditis elegans let-7 stem-loop" []
xref: rfam:RF00027 ! let-7
xref: wormbase:C05G5/12462-12364
relationship: obo:has_mature mirbase.mature:MIMAT0000001 ! has mature miRNA cel-let-7-5p
relationship: obo:has_mature mirbase.mature:MIMAT0015091 ! has mature miRNA cel-let-7-3p
relationship: RO:0002162 ncbitaxon:6239 ! in taxon Caenorhabditis elegans
```

I'm a bit unsure about what the domain/range for this relationship should be in SO - there are several possibilities that are similar for pre-miRNA / unprocessed and actually not so many options for post-processed miRNA

**Comment by dosumis** [comment]
What about something more generic like derived_from/has_derivative? Also worth checking on what PRO uses for protein processing.

**Comment by cthoyt** [comment]
That's a good thought! I also was looking at the superclasses for translates to/transcribes to for something like this, but nothing seemed appropriate

**Comment by nlharris** [comment]
So is this a request for a new relation?

**Comment by cthoyt** [comment]
@nlharris yes indeed
