### ISSUE TITLE
Add new term request form

### ISSUE THREAD

**Issue by cthoyt** [oborel/obo-relations#496]
It would be great to add a template for new terms to make less effort for @nlharris for tagging issues and to help curators for RO. Can anyone tag on this issue what the most useful information (mandatory) for a new term, and what are the nice to have (optional) things?

See #466 (thanks Nico for digging that one up)

**Comment by matentzn** [comment]
Didnt we start doing that here?

**Comment by matentzn** [comment]
https://github.com/oborel/obo-relations/pull/466

**Comment by nlharris** [comment]
In addition to PR #466 note that issue #465 is very similar to this issue.
