### ISSUE TITLE
show error page on unknown RO purl instead of xml listing ontology resources.

### ISSUE THREAD

**Issue by jhpoelen** [oborel/obo-relations#500]
In #499 , a invalid purl attempted to be resolved. 

currently, some xml is shown (see attached image).

Suggest to show some human readable error page indicating that the term was unknown.

![Screenshot from 2021-09-21 08-16-39](https://user-images.githubusercontent.com/1084872/134200412-119efaef-2ead-465f-a78d-1c969703eee6.png)

**Comment by jamesaoverton** [comment]
This is an important issue that I think would be best addressed at the OBO PURL level: https://github.com/OBOFoundry/purl.obolibrary.org/issues/251

**Comment by jhpoelen** [comment]
Agree, thanks for making a note of this in the relevant OBOFoundry repo issue.
