### ISSUE TITLE
OBO Rel suggests that a hyper parasitoid is a hyper parasite, but this is not necessarily true

### ISSUE THREAD

**Issue by jhpoelen** [oborel/obo-relations#501]
when searching for "hyperparasitoid" http://www.ontobee.org/search?ontology=RO&keywords=hyperparasitoid&submit=Search+terms 

the term http://purl.obolibrary.org/obo/RO_0002553 pops up. (see screenshot attached).
![Screenshot from 2021-09-21 11-14-04](https://user-images.githubusercontent.com/1084872/134225285-64a37c7c-9f39-4c9d-83a4-8b340d160efb.png)

However, when searching for "hyperparasite" http://www.ontobee.org/search?ontology=RO&keywords=hyperparasite&submit=Search+terms , 

the term  http://purl.obolibrary.org/obo/RO_0002553 pops up again (see screenshot attached).
![Screenshot from 2021-09-21 11-15-02](https://user-images.githubusercontent.com/1084872/134225311-5a29dea1-73fd-432c-965d-33b50cc66fb4.png)

Expected that hyperparasitoid is treated as *a kind of* hyperparasite, *not* as an equivalent to a hyperparasite.

Suggest to create separate purl uri for hyper parasitoid terms.

**Comment by balhoff** [comment]
The text on the Ontobee page is a little bit misleading. RO:0002553 has label 'hyperparasite of', but it has a _related synonym_ 'hyperparasitoid of', which indicates that 'hyperparasitoid of' is not exactly the same kind of thing this relation denotes.

**Comment by jhpoelen** [comment]
@balhoff ok, thanks for clarifying. As far as I understand a hyperparasitoid is a hyponym of hyperparasite, not a synonym. Would you agree?

**Comment by balhoff** [comment]
I think you're right. In that case we would use `http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym`.
