### ISSUE TITLE
Add “material surface of” as a narrow synonym for “2D boundary of”

### ISSUE THREAD

**Issue by BarryFen** [oborel/obo-relations#509]
I am requesting the addition of a narrow synonym “material surface of” for the term “2D boundary of”. This will be used in the fields of food safety and microbiology to describe the type of material that different equipment or utensil surfaces are composed of.  Example: A conveyor belt has “material surface of” some plastic.

**Comment by nlharris** [comment]
See also Add 2D counterparts for boundary relations #297

**Comment by ddooley** [comment]
Can we have some action on this one?!  A paper in the wings wanting this relation or something like it.

**Comment by matentzn** [comment]
@BarryFen is asking for a synonym, right, not a relation. @ddooley you know how to edit RO, right? fork repo, edit src/ontology/ro-edit.o**?

**Comment by ddooley** [comment]
Yes just asking for a synonym, but also to double check the appropriateness of the synonym.  I've just taken a second look, and it appears that "**has material surface**" is a more correct synonym to have, and probably an exact synonym? (The "material surface of" synonym is actually about the reverse relation to "2D boundary of").
Ok, pending feedback on "has material surface", I can add to ro-edit.owl

**Comment by matentzn** [comment]
Best way. to elicit feedback in my experience? Make a PR, then post that PR in the obo RO slack group :D

**Comment by nlharris** [comment]
Too true! 😝

**Comment by ddooley** [comment]
This can close!
