### ISSUE TITLE
Can we safely have "characteristic of part of" capture physiological and anatomical phenotypes?

### ISSUE THREAD

**Issue by matentzn** [oborel/obo-relations#514]
From obo slack.

I asked: What is the risk of adding this role chain:

```
(characteristic of o occurs in) subPropertyOf characteristic of part of
```

to the existing ones:

```
(characteristic of part of o part of) subPropertyOf characteristic of part of
(characteristic of o part of) subPropertyOf characteristic of part of
```

@cmungall  responded: 

> located_in is safer

In uPheno 2, it becomes increasingly clear that general grouping like

"abnormal cardiovascular system phenotype"

should capture both

- Increased heart phenotype (defined in terms of an anatomical structure in UBERON) AND
- increased cell proliferation in the heart (defined in terms of a GO process that occurs in the heart)

I think in order to enable this, we need to add the above role chain. 

@cmungall can you explain how "located_in" fits into this?

**Comment by dosumis** [comment]
Potential problems with reasoning across part_of relationships between properties?

**Comment by matentzn** [comment]
Could you give an example, even if fictional?
