### ISSUE TITLE
relax range constraint on regulates

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#524]
change from process to process or characteristic

(there are other tickets to be linked here but I can't find them)

This change is necessary for go-plus to be coherent (currently crytpic incoherence as not caught by elk 0.43)

alternative:

create three parallel relations and use these in GO for the RoBQ branch

The two alternatives are not mutually exclusive - I think it is most practical to first relax, then we can make the GO change. But this is actually quite urgent

**Comment by pgaudet** [comment]
what problem does that solve? by 'characteristic' do you mean, regulation of quality?

**Comment by matentzn** [comment]
GO plus for example states that `regulation of biological quality` regulates a `quality`.. 

![image](https://user-images.githubusercontent.com/7070631/142472507-00de9f3c-a22f-41af-a85b-fe43011e92c7.png)

The other option would be to introduce new relations.

**Comment by balhoff** [comment]
@pgaudet relates to this GO issue: https://github.com/geneontology/go-ontology/issues/16524
