### ISSUE TITLE
Documentation request: how to join the RO meetings

### ISSUE THREAD

**Issue by matentzn** [oborel/obo-relations#526]
For current and prospective RO users it would be useful to know how to learn about and join the quarterly RO meetings. This should be added to the documentation https://oborel.github.io/obo-relations/

**Comment by nlharris** [comment]
I think the answer is that you should request to join the obo-relations mailing list (which is mentioned on https://github.com/oborel/obo-relations, but that README doesn't mention the quarterly meetings -- should it?).

**Comment by matentzn** [comment]
Yes it should. We should:

- [ ] Update https://github.com/oborel/obo-relations/blob/master/CONTRIBUTING.md to include a mention to the regular meetings and how to learn about them, and add a bullet on how to join the RO mailing list
- [ ] We need to be sure that RO mailing list is actually used to announce meetings in advance.. The person dedicated to organising the event should take care of that, not sure how to make sure they actually do.
- [ ] We need to add a link from the main README to https://github.com/oborel/obo-relations/blob/master/CONTRIBUTING.md "How to contribute to RO and join the RO working group".

**Comment by nlharris** [comment]
Thanks for the specifics! I have been announcing RO meetings on the mailing list. The other two tasks I just made PRs for.

**Comment by matentzn** [comment]
This is addressed now, thanks for all that @nlharris
