### ISSUE TITLE
Add relations "implemented during" and "implements"

### ISSUE THREAD

**Issue by rduerr** [oborel/obo-relations#533]
In NASA parlance, Missions implement or partially implement experiments.  This relationship is complex as 

1. an experiment can be carried out over multiple missions,
2. both experiments and missions are activities;
3. both activities (and many others) involve a variety of material, immaterial and temporal component parts (hardware, planned procedures, etc.)

In English (and in NASA data systems) there is a tendency to simply say that a named experiment is part of one or more named missions (thus the "implemented during" since all missions have a defined duration).  This simple relationship needs to carry over into the ontology which implies that BFO terms mostly won't work.

In general, the material parts of an experiment are either part of or carried by the material parts of a mission.  The temporal implementation of the experiment overlaps the temporal period of missions involved. 

Does this actually belong in RO and if so, where would it go.  Also, other suggestions?

**Comment by nlharris** [comment]
Does anyone have an opinion about this?

**Comment by balhoff** [comment]
Why not use `experiment-x part_of mission_y`?

**Comment by nlharris** [comment]
@rduerr does Jim's answer satisfy your request?

**Comment by wdduncan** [comment]
I would be careful about the use of the label 'implements'. What would the domain and ranges be? It needs to be broader than just experiments. For example, does a computer program "implement" an algorithm? I know of a paper that argues for this position.  Does an office building "implement" an architectural blue print?

Also, what sense of 'experiment' is being use? The process sense (i.e., the experiment being carried out), or the ICE sense (i.e., the documentation detailing how to perform the experiment)?
