### ISSUE TITLE
RO is importing and using the wrong Dublin Core license annotation

### ISSUE THREAD

**Issue by dillerm** [oborel/obo-relations#536]
I believe the correct one is dcterms:license (http://purl.org/dc/terms/license) and not dc:license (http://purl.org/dc/elements/1.1/license).

**Comment by matentzn** [comment]
Thank you @dillerm you are totally right!

@shawntanzk would you be able to deal?

**Comment by shawntanzk** [comment]
@matentzn do I just change that annotation in -edit file? I assume that would fix it with release right?

**Comment by shawntanzk** [comment]
-edit file seems to show correct annotation: 
`Prefix(dc:=<http://purl.org/dc/terms/>)`
`Annotation(dc:license <https://creativecommons.org/publicdomain/zero/1.0/>)`

**Comment by shawntanzk** [comment]
think (http://purl.org/dc/elements/1.1/license) would be dce:license

**Comment by matentzn** [comment]
@dillerm where did you see that wrong license property?

**Comment by dillerm** [comment]
RO-core, but it might exist elsewhere.

**Comment by matentzn** [comment]
Indeed, thx:

https://github.com/oborel/obo-relations/blob/master/src/ontology/core.owl @shawntanzk

**Comment by matentzn** [comment]
I think this is the only remaining place this is wrong.
