### ISSUE TITLE
`never_in_taxon` expands to invalid syntax

### ISSUE THREAD

**Issue by gouttegd** [oborel/obo-relations#546]
`never_in_taxon` (RO:0002161) has a `expand assertion to` (IAO_0000425) annotation defined as follows:

```
AnnotationAssertion(obo:IAO_0000425 obo:RO_0002161 "?X DisjointWith RO_0002162 some ?Y ")
```

It seems that the `--expand-macros` feature of `owltools` does not support this syntax. It errors out with

```
org.semanticweb.owlapi.manchestersyntax.renderer.ParserException: Encountered UBERON_0010289 at line 1 column 1. Expected one of:
	Individual:
	AnnotationProperty:
	Rule:
	Datatype:
	Class:
	DataProperty:
	ObjectProperty:
	Annotations:
	ValuePartition:

	at org.semanticweb.owlapi.manchestersyntax.parser.ManchesterOWLSyntaxParserImpl$ExceptionBuilder.build(ManchesterOWLSyntaxParserImpl.java:2521)
```

(where `UBERON_0010289` is the term carrying the `never_in_taxon` annotation)

Since `owltools` seems to expect the macro to expand to something in the Manchester syntax, I believe the annotation should be defined as:

```
AnnotationAssertion(obo:IAO_0000425 obo:RO_0002161 "Class: ?X DisjointWith: RO_0002162 some ?Y ")
```

which is accepted by `owltools` and yields the expected result.

**Comment by gouttegd** [comment]
Update: Contrary to what I wrote above, `OWLTools` does not actually _error out_ upon encountering the `never_in_taxon` macro. It logs an `ERROR`-level message but proceeds anyway. So the invalid syntax in the macro expansion does not cause any build failure anywhere. But it does cause the macro expansion to be ignored, so that the resulting ontology does _not_ contain the intended disjointness axiom but instead still contains the unexpanded `never_in_taxon` macro.

**Comment by gouttegd** [comment]
Yes, preparing the PR right now. :)

**Comment by balhoff** [comment]
@dosumis: https://github.com/ontodev/robot/issues/963

**Comment by matentzn** [comment]
Uberon uses SPARQL:

https://github.com/obophenotype/uberon/blob/master/src/sparql/taxon_constraint_never_in_taxon.ru

https://github.com/obophenotype/uberon/blob/master/src/ontology/uberon.Makefile#L101
