### ISSUE TITLE
Annotation property for tagging unilaterally injected axioms

### ISSUE THREAD

**Issue by dosumis** [oborel/obo-relations#550]
See https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1443#issuecomment-1012942543

label: modifies_externally_defined_OWL_entity
def: This axiom alters the meaning of an OWL Entity, but has not been officially sanctioned by the editors of the ontology to which this entity belongs.
range: Boolean

**Comment by cmungall** [comment]
Thus for APs minted in RO have primarily been APs about OPs or axiomatization involving OPs

I am keen to get this tag out, but there is discussion on slack about what home is best, RO or OMO

**Comment by dosumis** [comment]
Happy to move it.

**Comment by matentzn** [comment]
I think this should be OMO, as it will form part of our third circle of core annotations..

**Comment by nlharris** [comment]
Is there someone who could move this ticket to OMO?

**Comment by matentzn** [comment]
Just close here and copy / link to https://github.com/information-artifact-ontology/ontology-metadata/issues
