### ISSUE TITLE
add relations to connect multi-gene alleles to the genomic features altered by the allele

### ISSUE THREAD

**Issue by sbello** [oborel/obo-relations#562]
The Alliance of Genome resources would like to have a set of relations to connect alleles to the genes altered by the allele. These are primarily for multi-gene alleles such as large deletions or duplications.

We have a spreadsheet of suggested new terms (https://docs.google.com/spreadsheets/d/1q09xpN60ffJ5WKx6EFFSr3j5xyrgd8XMJTK53_pwU3E/edit?usp=sharing) with definitions and curator notes. Definitions are currently referencing sequence ontology terms for the mutation types but we need to consult with the SO team to refine some of these terms.

We would appreciate feedback on the definitions as we have been struggling to create definitions that conform to existing RO definitions and are comprehensible to the curators. For example for the term "mutation deletes" we have 4 variations of the definition:

1. "The marker relation in which the organizer is of type allele and evidence suggests that some part of the participant is involved in the mutation defined by the organizer."
2. "The relation in which the larger entity is a deletion allele (SO:0000159), and evidence suggests that part or all of the specified biological region (SO:0001411) is deleted."
3. "The relation in which the larger entity is a deletion allele (SO:0000159) that deletes part or all of the specified biological region (SO:0001411)."
4. "The relation in which a deletion allele (SO:0000159) deletes part or all of the specified biological region (SO:0001411)."
Note SO:0000159 is overly broad as we want the relation to connect a large deletion to genes that fall within the region.

Some examples of these relations as they are currently used in MGI
Del(3Bglap2-Bglap)1Kry www.informatics.jax.org/allele/mutationInvolves/MGI:4949086
Mp http://www.informatics.jax.org/allele/mutationInvolves/MGI:1861183 

Please let me know if you want to set up a meeting or have some of us join your call to discuss these.

Thanks,
Sue

**Comment by nlharris** [comment]
Can anyone help respond to this?

**Comment by sabrinatoro** [comment]
I have some comments: 
- the clinical community is staying away from using the word "mutation". They prefer the term "variation" instead.
- I know that the term "allele" is used to mean different concepts in different communities. Therefore we should be very careful about using this term, especially in definitions.
- I am confused by what is on the table, as these relations seem to refer to a "variant" and not "allele" as defined at the Alliance. 

More generally, I wonder whether these relations are needed: I am specifically referring to projects such as linkML. I feel like more discussions are needed. 
(my 2 cents)

**Comment by dosumis** [comment]
Second def sounds good to me.
