### ISSUE TITLE
Add "mentioned by" as inverse of "mentions" object property

### ISSUE THREAD

**Issue by ddooley** [oborel/obo-relations#565]
Due to our use of robot tables to associate instances with the data specifications they are associated with, it would be handy to have "mentioned by" or "mentioned in" as an inverse object property of "mentions".  (We're dealing with enumerations where the  enumeration has to stay looser about the kinds of things it references, so unable to use 'member of').

**Comment by matentzn** [comment]
@ddooley can you deal with this ticket yourself? If you need help we can support you!

**Comment by ddooley** [comment]
Cripes, I forgot "mentions" is IAO.  I'll do a pull request over there.
