### ISSUE TITLE
make 'has plasma membrane part' a subproperty of expresses

### ISSUE THREAD

**Issue by dosumis** [oborel/obo-relations#579]
**Use case:** - Grouping cell markers irrespective of whether they are recorded as gene, transcript or protein.

**Justification:**

'has plasma membrane part' is defined by the presence of a protein in the membrane.  

expresses is defined as the inverse of expressed_in, which has the definition.

> x expressed in y if and only if there is a gene expression process (GO:0010467) that occurs in y, and one of the following holds: (i) x is a gene, and x is transcribed into a transcript as part of the gene expression process (ii) x is a transcript, and the transcription of x is part of the gene expression process (iii) x is a mature gene product such as a protein, and x was translated or otherwise processed from a transcript that was transcribed as part of this gene expression process.

I think that the third clause + background knowledge about gene expression justifies placing 'has plasma membrane part' under expresses.  If the protein is present in the membrane, it will be as a result of a process of gene expression.   Edge case:  What if the protein on the cell surface is imported into the cell? We could potentially tighten the definition of 'has plasma membrane part' to specify it must be the result of expression in the cell.

**Comment by shawntanzk** [comment]
100% agree with the logic, but wonder how this will affect modelling - currently `has plasma membrane part` is under `has part` and i know that does a lot of the heavy lifting in queries etc. 
Either way will add this to RO call agenda for Wednesday :)

**Comment by shawntanzk** [comment]
Consider: 
changing label to `expresses endogenous plasma membrane part` and make minor change to definition and place it under expresses - this would address edge case (eg virus particle on membrane would be excluded from this). - thoughts on this @addiehl? (will bring this to CL call too) 

This way only endogenous markers are considered 

use case: query markers - this will show up if it is under expresses (part of is more "dirty") -> bridges transcriptomic and "classical" (eg FACS) 

edge-case something like CD-something -> its actually named after the hormone (but its probably a naming issue more than anything) (Bjoern)

**Comment by addiehl** [comment]
I will provide a longer response soon to this proposal -- Alex

**Comment by shawntanzk** [comment]
From CL call: 

Potential solution: in CL if something 'has plasma membrane part' protein -> inject axiom 'expresses' protein (do this in an automated way) - @dosumis is this ok? 

Details: 

Alex - there are some that are carbohydrates not proteins, so they are expressed quite indirectly, but not in the same way as a protein is expressed.
We use has part of transcription factors: question - querying might be tricky 

Bjoern- something like CD45 ro/ra - need to go down to isoform which cant be expresses 
we need to define queries - need to be interoperable with mRNA and protein etc. 

Alex - membrane part might not be an expressed thing but defines the cell 

Shawn - would it be sensible if to add an additional axiom for expresses? can we automate if say its from PR or part of gene etc. 

Alex - mass cells bind immunoglobulin E but it doesn't express and binding the immunoglobulin is a defining characteristic

Alex - we can make the assumption that in CL if something 'has plasma membrane part' protein (an entity that come from PRo ontology) that it expresses. We can inject this in the final output ontology.

**Comment by balhoff** [comment]
> From CL call:
> 
> Potential solution: in CL if something 'has plasma membrane part' protein -> inject axiom 'expresses' protein (do this in an automated way) - @dosumis is this ok?

@shawntanzk I think you could do this using a property chain and rolification of 'protein'.

**Comment by dosumis** [comment]
> Potential solution: in CL if something 'has plasma membrane part' protein -> inject axiom 'expresses' protein (do this in an automated way) - @dosumis is this ok?

Sounds good to me.  I like Jim's solution with property chain + rolification.  Could use Chris' new rolification template (presented at last RO call)
