### ISSUE TITLE
gene product and transcriptional connectivity

### ISSUE THREAD

**Issue by GoogleCodeExporter** [oborel/obo-relations#58]
```
there seems to be missing hierarchical relationships between the 'gene product' 
terms and the transcriptional/translational terms.  right now, they are all 
sibling relationships, but i think they should be hierarchical, as in:

gene product of (RO:0002204)
  transcribed from (RO:0002510)
  ribosomal translation of (RO:0002512)


has gene product (RO:0002205)
  transcribed to  (RO:0002511)
  ribosomally translates to (RO:0002513)


```

Original issue reported on code.google.com by `nicole.l...@gmail.com` on 14 Apr 2015 at 4:03

**Comment by sierra-moxon** [comment]
I may be misunderstanding the definition of RO:0002512, but it appears that we might have an x and y swapped? ie: 

Currently: "x is the ribosomal translation of y if and only if a ribosome reads x through a series of triplet codon-amino acid adaptor activities (GO:0030533) and produces y"

Proposed revision: "x (amino acid chain/polypeptide) is the ribosomal translation of y (transcript) if and only if a ribosome reads y (transcript) through a series of triplet codon-amino acid adaptor activities (GO:0030533) and produces x (amino acid chain/polypeptide)"

**Comment by nlharris** [comment]
Can this be closed?

**Comment by nlharris** [comment]
Can this be closed?

**Comment by nlharris** [comment]
Closing; please re-open with specific actions/requests if needed.
