### ISSUE TITLE
rename "exposure event or process" to "exposure of organism"

### ISSUE THREAD

**Issue by wdduncan** [oborel/obo-relations#599]
In ECTO, there is an `exposure event` class. However, due to the RO import, the class `exposure event or process` exists. It would be helpful and less confusing if ECTO used the same class as RO for these events. Would you be willing to change label for `exposure event or process` to simply be `exposure event`?

I am also going to see `exposure event` can be added to COB.

cc @nicolevasilevsky @laurenechan @diatomsRcool @cmungall

**Comment by nicolevasilevsky** [comment]
I don't have any objections but this is really up to @diatomsRcool.

**Comment by wdduncan** [comment]
Another suggestion may be for RO to use the ECTO class [exposure event](http://purl.obolibrary.org/obo/ExO_0000002) for the domain constraint. However, that may break existing usages.

**Comment by cmungall** [comment]
We should obsolete the RO class and use an ECTO or COB class (not ExO). classes are only in RO as placeholders.

**Comment by diatomsRcool** [comment]
I'm fine with changing the label. 
FYI - If memory serves the "event or process" was used to emphasize that an exposure event was a type of BFO process. There was a lot of discussion about event vs process.

**Comment by wdduncan** [comment]
COB has added an [exposure of organism](https://github.com/OBOFoundry/COB/issues/192) class.

Waiting on [new release of COB](https://github.com/OBOFoundry/COB/issues/210) before using this class.
