### ISSUE TITLE
Add inverseOf 'innervates' (RO_0002134)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [oborel/obo-relations#6]
```
presumably called "innervated by"

Also, presumably this relation pair can be used for vertebrate muscle 
innveration - if so, add example
```

Original issue reported on code.google.com by `cmung...@gmail.com` on 29 Apr 2013 at 4:35

**Comment by nlharris** [comment]
Is this still needed?

**Comment by dosumis** [comment]
Looks like we have it: https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002005
