### ISSUE TITLE
Expansion for RO:0002171

### ISSUE THREAD

**Issue by shawntanzk** [oborel/obo-relations#600]
Currently `mutually spatially disjoint with` expands to owl:Nothing 
Might have scaling issue
New robot expand (https://github.com/ontodev/robot/pull/964) uses SPARQL so moving forward we might want to change this to use a SPARQL to expand to use disjoint GCIs instead ("part of" some X disjoint_with "part of" some Y)

**Comment by balhoff** [comment]
I will implement this as an example of `robot expand`. Also it would be good to add a doc page about these expansions.
