### ISSUE TITLE
Standardize abbreviations/codes for common relations

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#613]
Many ontology browsers such as OLS and BioPortal use the symbol "P" to show part-of edges - this has been common convention for decades. OboEdit also made use of a wider variety of symbols, e.g. "I" for is-a, we still make use of these in AmiGO

Rather than being convention, can we codify this in RO? I suggest

- I: is_a (subClassOf between NCs)
- P: part_of
- D: develops_from
- T: rdf:type / instance-of

Currently we have a default visualization configuration in OAK specified in [kgviz](https://berkeleybop.github.io/kgviz-model/) format:

https://github.com/INCATools/ontology-access-kit/blob/main/src/oaklib/conf/obograph-style.json

(We are using unicode symbols for encircled letters)

We could use the default OAK config as the place to standardize this but it might be good to place this closer to the source

It may be the case that there would be too many claims over who gets to use each letter, but let's see, I suspect only a subset of ontologies that follow relational patterns would care about this, and there are already conventions in place here

See also:

 - https://github.com/EBISPOT/OLS/issues/304

**Comment by matentzn** [comment]
good idea! Not sure --develops-from merits its own code, but I agree with the general idea! An AP on the property itself? Something like `hasShortCode`?
