### ISSUE TITLE
Is there a reason why 'participates in' doesn't have a property chain?

### ISSUE THREAD

**Issue by StroemPhi** [oborel/obo-relations#622]
Looking at the property chain of 'has participant' `'has part' o 'has participant' -> 'has participant'`, I wonder why there isn't also a similar property chain axiom for 'participates in' `'part of' o 'participates in' -> 'participates in'`.

Is there a reason why such a property chain axiom shouldn't be there? Isn't it always the case that the part of a continuant that participates in a process also participates in that process? 

**Reason (use case) for my question:**
There is the planned process called Munin 2022 and when looking at its [conference website](https://site.uit.no/muninconf/about-the-conference/), I see six people being listed as members of the organizing committee. As part of my work I need to archive this fact in RDF. 

Now, I could assert that there is a subprocess (part) of Munin 2022, which is the planning process, and that each of the listed people participate in it. Due to the existing property chain on 'has participant', I could thus infer that they also participate in Munin 2022.
![grafik](https://user-images.githubusercontent.com/56996739/186883299-b8c9e27e-9e63-4e38-8291-98dbc9cbb27c.png)

But I'm not interested in this planning process and would not want to create that instance. For my use case, I'm rather only interested in who was responsible for the planning of Munin 2022, as in making assertions about its event committees. Thus it would be better to be able to only assert that the committee participates in Munin 2022 and that the people are the members of it. With the above mentioned property chain on 'participates in', I could then infer that they also participated in Munin 2022.
![grafik](https://user-images.githubusercontent.com/56996739/186892123-8f288316-81ea-4753-be22-90884a7f955e.png)

**Comment by cmungall** [comment]
this would entail that electrons in the left small toenails of each participant also participate

this is not inherently wrong - participation in the BFO/RO sense is already a broad concept that doesn't always align with normal natural language usage of the concept of participation. 

note we do entail the inverse property chain (which is different from what you propose) but we should materialize those inferences.

**Comment by StroemPhi** [comment]
Thank you for the reply @cmungall.

> this would entail that electrons in the left small toenails of each participant also participate

:smile: Indeed, if one uses a classical instead of quantum mechanical perspective.

> this is not inherently wrong - participation in the BFO/RO sense is already a broad concept that doesn't always align with normal natural language usage of the concept of participation.

I know my use case example is more in line with the natural language use of participation, but with my question I had the abstract BFO/RO meaning in mind.

> note we do entail the inverse property chain (which is different from what you propose) but we should materialize those inferences.

This I don't get, I'm afraid.

**Comment by cmungall** [comment]
r1 o r2 -> r3
<=>
r2’ o r1’ -> r3’

Where ‘ indicates inverse

Eg

Participatesin o partof-> participatesin
<=>
Haspart o hasparticipant -> hasparticipant

I think robot supports materialization of inferred property chains just
need to tweak the release makefile

**Comment by StroemPhi** [comment]
Thank you for the clarification. Should we close the issue, or wait until the makefile is tweaked?

**Comment by cmungall** [comment]
I made a separate issue for the materialization

And I have probably created confusion. Electrons are already inferred to participate in meetings.

I was actually thinking of the parallel scenario - right now we don't have a chain over part-of on the process side. This feels strangely lopsided. I'll leave this open to generate discussion here
