### ISSUE TITLE
broaden definition of 'existence overlaps'?

### ISSUE THREAD

**Issue by Clare72** [oborel/obo-relations#632]
Currently the start or end point of the existence of the physical entity must be within the process or stage.
Therefore the case where the existence of the physical entity encompasses the process or stage is not included.
This seems like it might be intentional, but it does not match the spatial relationship RO:0002131 'overlaps', which has BFO:0000051 'has part' as a child.
If it is not considered desirable to broaden 'existence overlaps', could we make a broader relationship to cover this case, i.e. an 'existence starts during or before and ends during or after' relationship?

**Comment by nlharris** [comment]
Does anyone have any comments on Clare's questions/requests?
