### ISSUE TITLE
Sunset issues that have been open for more that 2 years

### ISSUE THREAD

**Issue by wdduncan** [oborel/obo-relations#639]
In order to clean up the RO issue tracker, how about we sunset/close issues that have been open more than 2 years? If the submitter is still passionate about the issue, it can easily be reopened. Also, perhaps some of these issues are best moved to the `Discussions` tracker. Although, I'm not real sure what counts as an issue and what counts as a discussion in RO.

**Comment by nlharris** [comment]
> perhaps some of these issues are best moved to the Discussions tracker.

I don't recommend this. In other projects, Discussions is just yet another place for those who look at issues (who are mostly volunteers, in this case) to remember to check...and usually they don't remember.

**Comment by balhoff** [comment]
Here is the GitHub Action used to manage stale issues for Uberon: https://github.com/obophenotype/uberon/blob/master/.github/workflows/stale-issues.yml
