### ISSUE TITLE
Increase the frequency of RO meetings?

### ISSUE THREAD

**Issue by wdduncan** [oborel/obo-relations#641]
Should we increase the frequency of the RO meetings? E..g.: Monthly

**Comment by nataled** [comment]
The EWG has discussed the possibility of ceding one meeting each month to RO. This will have the following effects, if adopted:

1) Ops, RO, and EWG meetings will all be at the same time, so no new slot will be needed.
2) Ops meetings will happen twice a month, while EWG and RO will be once a month (ignoring, for simplicity, months with 5 Tuesdays).

**Comment by nataled** [comment]
This should probably be raised during the next Ops call.

**Comment by wdduncan** [comment]
@nataled @cmungall @balhoff @nlharris  
I am not able to make the 11/15/2022 meeting (conflict). Can one of you bring this up?

**Comment by cmungall** [comment]
Note that I don’t make ro or obo meetings any more as I have a standing
conflict except for the 2nd Tuesday of the month
