### ISSUE TITLE
Missing definitions for some ecological interactions

### ISSUE THREAD

**Issue by nleguillarme** [oborel/obo-relations#646]
Definitions are missing for the following ecological interactions (the list is not exhaustive):
- [eats](http://purl.obolibrary.org/obo/RO_0002470)
- [is eaten by](http://purl.obolibrary.org/obo/RO_0002471)
- [provide nutrients for](http://purl.obolibrary.org/obo/RO_0002469)
- [acquires nutrients from](http://purl.obolibrary.org/obo/RO_0002457)
- [parasite of](http://purl.obolibrary.org/obo/RO_0002444)
- [parasitized by](http://purl.obolibrary.org/obo/RO_0002445)
- [has pathogen](http://purl.obolibrary.org/obo/RO_0002557)
- [pathogen of](http://purl.obolibrary.org/obo/RO_0002556)

**Comment by nleguillarme** [comment]
We are working on trophic interactions as part of the [soil food web ontology](https://github.com/soilfoodwebontology/sfwo) project. Maybe we can discuss this with the people involved and come up with some suggestions?

**Comment by diatomsRcool** [comment]
Yes, I can help with these
