### ISSUE TITLE
NTR : symbiotrophically interacts with

### ISSUE THREAD

**Issue by nleguillarme** [oborel/obo-relations#647]
RO defines the following interactions : [symbiotically interacts with](http://purl.obolibrary.org/obo/RO_0002440) and [trophically interacts with](http://purl.obolibrary.org/obo/RO_0002438). 

Then there is the special case of [symbiotroph](https://en.wiktionary.org/wiki/symbiotroph), or symbiotrophic organisms, which are organisms that derives nourishment through a symbiotic relationship with another organism. Therefore, symbiotrophs symbiotrophically interact with other organisms, which is a subproperty of both symbiotically interacts with and trophically interacts with.

Examples of symbiotrophs are mycorrhizal fungi and trophic parasites.

**Comment by nleguillarme** [comment]
Related to this issue, RO provides no property to represent trophic parasitic interactions. Many ontologies use "parasite of" by default, but "parasite of" is not a trophic interaction according to RO. I would propose something like

- symbiotically interacts with
  - interacts with via parasite-host interaction
    - parasite of
      - trophic parasite of
  - symbiotrophically interacts with
      - trophic parasite of
- trophically interacts with
  - symbiotrophically interacts with
    - trophic parasite of

**Comment by ddooley** [comment]
Discussed on Jan 31 call: Could you supply an aristotelean definition for "symbiotrophically interacts with", and an example!  And then the same for "trophic parasite of".  

We are not sure how the two parents "symbiotically interacts with" and "trophically interacts with" might show up in the same araristotelean definition however, so RO curatorswill circle back to this. One suggestion is that for new "symbiotrophically interacts with" term the parent could be as high as "participates in a biotic-biotic interaction with".

**Comment by nleguillarme** [comment]
Here is a proposal, based on the fact that "symbiotrophically interacts with" would be a subproperty of "trophically interacts with" : _A trophic interaction in which one organism acquires nutrients through a symbiotic relationship with another organism._

An example of symbiotrophic interaction is mycorrhizal association.

Although symbiotroph mainly applies to Fungi, the ECOCORE ontology has defined [parasite](https://ontobee.org/ontology/ECOCORE?iri=http://purl.obolibrary.org/obo/ECOCORE_00000146) (implied "trophic parasite") as a subclass of "symbiotroph". So I would suggest "trophic parasite of" as a subproperty of "symbiotrophically interacts with" (and also a subproperty of "parasite of").

Concerning the definition of "trophic parasite of", I would suggest something like:  _A symbiotrophic interaction in which one organism acquires nutrients through a parasitic relationship with another organism._

Note that "parasite of" has no textual definition (in the same way as "eats", "preys on"), which makes it difficult to decide which term to use to axiomatize diet concepts.

**Comment by diatomsRcool** [comment]
I think what @nleguillarme has said above is correct. That is what we should do.

**Comment by wdduncan** [comment]
Just following up on this issue.

Is this definition adequate?:  
> A symbiotrophic interaction in which one organism acquires nutrients through a parasitic relationship with another organism.

If so, can someone make a PR? If this is not longer needed can we close the issue?
