### ISSUE TITLE
add process to domain to range of concretizes

### ISSUE THREAD

**Issue by wdduncan** [oborel/obo-relations#650]
In [BFO-2020](https://github.com/BFO-ontology/BFO-2020/blob/master/21838-2/owl/bfo-2020.owl) the domain of `concretizes at some time` is `process or 'specifically dependent continuant'`. The domain of RO's  `concretizes` should be updated to include `process` for sake of consistency.

**Comment by cmungall** [comment]
I have no objection but this should be taken to the main stakeholders of this relation, which would include OBI. I am not sure who else uses these abstract relations.

**Comment by bpeters42** [comment]
Discussed in OBI call 1/9/2023. Relaxing the domain from 'specifically dependent continuant' only to add 'process' should be okay from OBI's point of view.

**Comment by cmungall** [comment]
Summarizing from RO call today.

I'm going to rewrite the original ask more precisely: the goal is to relax the domain to change it from SDC to a union `SDC or biological process`.

If we do this, then we should:

1. Change the text definition to be consistent. Currently it is "A relationship between a specifically dependent continuant and..."
2. Add an example of usage. We currently have two examples of usages, and both have SDCs (IAs). We need an example of process.
3. There were various references in the call to a talk, and also to a previous discussion in an OBI call but we should have links here so we can all examine the case

As an aside, we also noticed that we are manually duplicating annotations for inverses. This is not good practice, it violates DRY. @cmungall will look for documentation on existing practice and what we should do here (refer vs automatically propagate in release file)
