### ISSUE TITLE
NTR: is characteristic measurement of 

### ISSUE THREAD

**Issue by wdduncan** [oborel/obo-relations#654]
Add `is measurement of characteristic` to be more generic than IAO's `is quality measurement of`. E.g., processes can have characteristics, and this would allow the process in the range of the relations.

**Comment by matentzn** [comment]
When I read this on slack I was hoping this would relate the measurement process, not its output, to the characteristic. But I guess we could get both?

**Comment by wdduncan** [comment]
Sorry not following ... 
I requested this term as a first step to allow for shortcut relations of the form:  
`process` -- **output**--> `datum` -- **is characteristic measurement of** --> `characteristic`  

Did I misunderstand your need?

**Comment by matentzn** [comment]
Yes, I understand.. I was hoping for something direct, like:

`process` -- **output of which is characteristic measurement of** --> `characteristic`

**Comment by wdduncan** [comment]
How about the label `has output that measures characteristic`, and the inverse `characteristic is measured by output of`?

A definition will be needed too. I know you don't work on content, though :)

Once `is characteristic measurement of` is added, we can define the the property chain:
`has output` **o** `is characteristic measurement of`

**Comment by matentzn** [comment]
Its a mouthful.. But not too bad! I think I could get behind it! Thanks for suggestion.

**Comment by cthoyt** [comment]
@wdduncan can you put a concrete example of `process -- output--> datum -- is characteristic measurement of --> characteristic` on the issue header please?

**Comment by wdduncan** [comment]
@cthoyt This issue is for adding `is characteristic measurement of`. Although we've been discussion the addition of `has output that measures characteristic` (or whatever it will be calling), adding this relation should go in a separate issue. Do you want to submit the separate issue?
