### ISSUE TITLE
Import ORCIDIO

### ISSUE THREAD

**Issue by cthoyt** [oborel/obo-relations#666]
Following #664, there are now a lot more canonical ORCID URIs. while this has the benefit of making the provenance information in RO structured and actionable, it comes with the cost of readability. ORCIDIO (https://github.com/cthoyt/orcidio) is an ontology that declares canonical ORCID URIs as named individuals and adds labels, so you can see beautifully annotated term editors, creators, contributors, etc.

What's the best way to import ORCIDO? Some possibilities:

1. During release time (this doesn't benefit people who are working on the ro-edit.owl
2. Directly into ro-edit.owl. How should this get maintained? Could ODK do this for us?

**Comment by matentzn** [comment]
It will just be a normal import module which is visible both in edit and release. 

Blocked by:

- [ ] #492
