### ISSUE TITLE
`chemical.owl` uses OWL functional syntax while all other imports use RDF/XML

### ISSUE THREAD

**Issue by udp** [oborel/obo-relations#673]
Though RO and nearly all of the imports are RDF/XML: https://raw.githubusercontent.com/oborel/obo-relations/master/ro.owl

one single import: https://raw.githubusercontent.com/oborel/obo-relations/master/chemical.owl is in functional syntax. This seems inconsistent and we are unlikely to support the functional syntax in the next version of the Ontology Lookup Service given how few ontologies are published using it.

**Comment by wdduncan** [comment]
@udp It looks like the last time the ontology was modified was 4 years ago. Do you know if it is still in use?  
Maybe @matentzn or @balhoff know how to modify the pipeline to produce an RDF/XML version.

**Comment by matentzn** [comment]
This will be fixed once I get around to review #492

**Comment by anitacaron** [comment]
After updating RO to use ODK v1.4, the content of this file is now part of the ro-edit file, and then this file was removed.
