### ISSUE TITLE
NTR: owns; is owned by

### ISSUE THREAD

**Issue by CDowland** [oborel/obo-relations#674]
NTR 1: 
Label: owns
Elucidation: x owns y if and only if y is at x’s full disposal. This primitive relation is the foundation of the owner’s right to have the owned entity at his/her full disposal.  
Definition editor: Mathias Brochhausen

NTR 2:
Label: is owned by
Definition: The inverse of owns. 
Definition editor: Mathias Brochhausen

**Comment by wdduncan** [comment]
@CDowland I've added to the 01/31/2023 agenda.

**Comment by cstoeckert** [comment]
Note that these relations are currently in OBIB (http://purl.obolibrary.org/obo/OBIB_0000732,  http://purl.obolibrary.org/obo/OBIB_0000735) and originated from OMIABIS (which has been integrated into OBIB). OBIB is asking for these relations to be included in RO as per OBOF principles.

**Comment by cthoyt** [comment]
@CDowland can you give some concrete examples that use these relationships (including CURIEs for subject/object)?

**Comment by StroemPhi** [comment]
an example proposal of me owning this particular record box:
https://www.discogs.com/de/user/wan.2 ro:owns https://www.discogs.com/de/release/4218752-QNS-QNS-Box

**Comment by wdduncan** [comment]
An example from OBIB would be helpful.

**Comment by StroemPhi** [comment]
Axioms from OBIB that use these two relations copied from Ontobee and reformated for better readabilty:

- **biobank** equivalentClass : 
```
object aggregate and ( 
  has part some (
    object aggregate and ( 
      has part only ( 
        specimen and ( 
          participates in some storage )))))
  and ( 
    has part some ( 
      material information bearer and ( 
        participates in some ( 
          digital curation and ( 
            has_specified_output some ( 
              data set and ( 
                is about some ( 
                  object aggregate and ( 
                    has part only specimen))))))))) 
  and (is owned by some biobank organization)
```
- **biobank organization** equivalentClass : 
```
organization 
    and ((owns some biobank) or (administrates some biobank))
    and (has characteristic some legal person role)
```

**Comment by wdduncan** [comment]
The next RO call is March 28, 2023 at 9am PT, 18:00 CET. It would be great if you could attend.   
Here is the [Zoom link](https://lbnl.zoom.us/j/97163538233?pwd=czlTWTRzb0YvY0sxa1hwWERZUTFEQT09).

**Comment by CDowland** [comment]
@cthoyt In addition to the above examples:

Where a person X owns both a mobile phone Y and a house Z:
    X instance of NCBITaxon:9606
    Y instance of ENVO:01000581
    Z instance of ENVO:01000417
    X owns Y (or Y owned by X)
    X owns Z (or Z owned by X)

@wdduncan Thanks, I will add it to my calendar.

**Comment by wdduncan** [comment]
Thanks @CDowland !

**Comment by cstoeckert** [comment]
Examples discussed on March 2, 2023 OBIB call:
biobank organization owns a specimen
hospital owns a laboratory facility
CT scanner is owned by hospital
freezer is owned by a biobank organization

**Comment by zhengj2007** [comment]
@wdduncan Can I know the domain and range of the relations? Thanks!

**Comment by wdduncan** [comment]
@zhengj2007 That is a good question. I don't know the answer ... I was going off the ticket. 

@CDowland Do you know?

**Comment by CDowland** [comment]
In OBIB the domain of _owns_ is:

'Homo sapiens' or organization or 'collection of humans' or 'aggregate of organizations'

And it's range is:

'material entity' or 'information content entity'

For _is owned by_ those are swapped.

**Comment by zhengj2007** [comment]
If we want replace the OBIB one with RO one, it would be better to keep the domain and range defined in the OBIB and also copy over the OBIB definition. How do you think @wdduncan ?

**Comment by CDowland** [comment]
@zhengj2007 
Do you mean using the current OBIB definition instead of the one requested here? We don't want that. We made the above definition for the purpose of this request, and it is a revised version of what's currently in OBIB. 

Or do you mean including it as an additional annotation (something other than definition)?

**Comment by zhengj2007** [comment]
The current Definition is: 'The inverse of owns.'. I'd prefer to use descriptive definition and use inverse axiom to indicate it is the inverse relation of owns. @CDowland

**Comment by wdduncan** [comment]
@zhengj2007 Nice catch about the inverse of axiom! I've added it to the PR.

As for the definition of `is owned by`, it is standard practice for the inverse definition to state that it is an inverse. E.g. see [active ingredient in](http://purl.obolibrary.org/obo/RO_0002249). 

If you want a more verbose definition, please supply one :)

**Comment by CDowland** [comment]
Sorry for the misunderstanding. I was mixing up the two requested terms. 

If a descriptive definition is preferable, then instead of importing the old OBIB one, perhaps making it more closely mirror the definition of 'owns' would be better:

y is owned by x if and only if y is at x’s full disposal. This primitive relation is the foundation of the owner’s right to have the owned entity at his/her full disposal.

As for whether to use that or instead stick with the requested one, I'm neutral.

**Comment by wdduncan** [comment]
Adding @matentzn to the thread regarding adding classes for domains/ranges.  
We would need to import the classes: `'Homo sapiens' or organization or 'collection of humans' or 'aggregate of organizations'`.

Is this handled through ODK or do we manually add the classes to `other_imports.owl`?

**Comment by zhengj2007** [comment]
@CDowland It's fine. OBIB does not have relation 'owns'.

**Comment by wdduncan** [comment]
@CDowland I add the definition for `owns` as:
```
A primitive relation the holds between entities x and y in which y is at x’s full disposal.
```
RO does not have an `elucidation` annotation. I have found the `if and only if` locution to be confusing to users that aren't familiar with FOL.

I also added a `dcterms:description` annotationation:
```
This primitive relation is the foundation of the owner’s right to have the owned entity at his/her full disposal.
```

**Comment by CDowland** [comment]
@zhengj2007 OBIB currently has both 'owns' and 'is owned by': http://purl.obolibrary.org/obo/OBIB_0000732, http://purl.obolibrary.org/obo/OBIB_0000735

@wdduncan "the holds" should be "that holds." Otherwise, it looks good to me.

**Comment by zhengj2007** [comment]
@CDowland Thanks for catching it.

**Comment by wdduncan** [comment]
> @wdduncan "the holds" should be "that holds." Otherwise, it looks good to me.  

Thanks. Typo was fixed. See [change](https://github.com/oborel/obo-relations/pull/705/commits/dbd0e91d3444a807457caa3127ec493500774ec8)

Added `OBIB:0000735` as source for `owns`. See [change](https://github.com/oborel/obo-relations/pull/705/commits/6d9adc0a59f8cd45c6a1a1d672515187d40bfe05)

**Comment by zhengj2007** [comment]
Thanks @wdduncan

**Comment by nlharris** [comment]
can this be closed?

**Comment by wdduncan** [comment]
Not yet. The [PR](https://github.com/oborel/obo-relations/pull/705) is still open.
