### ISSUE TITLE
Suggest restoring `annotations.owl`

### ISSUE THREAD

**Issue by jamesaoverton** [oborel/obo-relations#683]
OBI uses <http://purl.obolibrary.org/obo/ro/releases/2015-10-07/core.owl>, which imports <http://purl.obolibrary.org/obo/ro/annotations.owl>, which no longer resolves (404) after #563. The underlying problem is that the old releases such as 2015-10-07 used imports without versions, as mentioned in #154. That old release also imports `bfo-classes-minimal.owl`, but that file was not dropped by #563.

The simplest solution would be to just restore `annotations.owl` at the top level of this repo.

**Comment by matentzn** [comment]
@cmungall did this now but the better solution imo would have been to have the purl redirect to the latest tag the file existed - but either way is fine. Thanks for letting me know!
