### ISSUE TITLE
How to access RO Core?

### ISSUE THREAD

**Issue by jamesaoverton** [oborel/obo-relations#684]
OBI uses an older version of RO Core. The ODK update in #563 broke that older version, as explained in #683. I would be happy to update to a newer version of RO Core, but I don't see how. This [`src/ontology/components/core.owl`](https://github.com/oborel/obo-relations/blob/master/src/ontology/components/core.owl) file seems to be what I want, and seems to include the annotations missing from #683, but does not include `bfo-classes-minimal.owl`. I could import them separately. My bigger concern is that these are buried deep in the repo, without their own PURLs, and maybe likely to change again.

**Comment by matentzn** [comment]
Wait, what is wrong with https://github.com/oborel/obo-relations/blob/master/core.owl?

**Comment by jamesaoverton** [comment]
You're right these will work: <http://purl.obolibrary.org/obo/ro/core.owl> or <http://purl.obolibrary.org/obo/ro/releases/2023-02-22/core.owl>.
