### ISSUE TITLE
Clarifying the meaning/usage of expresses

### ISSUE THREAD

**Issue by dosumis** [oborel/obo-relations#686]
There is some confusion over the meaning/usage of expresses due to the relevant definition being on its reciprocal (expressed_in).  See https://github.com/obophenotype/cell-ontology/issues/1859 for an example. This is a common pattern in RO, but may place too high a burden on users/editors.  In this case I propose that we add a definition on expresses to avoid future confusion:

`y expresses x if and only if there is a gene expression process (GO:0010467) that occurs in y, and one of the following holds: (i) x is a gene, and x is transcribed into a transcript as part of the gene expression process (ii) x is a transcript, and the transcription of x is part of the gene expression process (iii) x is a mature gene product such as a protein, and x was translated or otherwise processes from a transcript that was transcribed as part of this gene expression process.`

**Comment by dosumis** [comment]
@bvarner-ebi - I've added you as an RO editor.  Can you have add the def and make a PR?  Thanks.

**Comment by cmungall** [comment]
> There is some confusion over the meaning/usage of expresses due to the relevant definition being on its reciprocal (expressed_in).

See also:

- #51

I think the PR is good but in general I'd like to avoid manually crafting definitions for both directions and risk drift
