### ISSUE TITLE
Document evidential relationships

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#69]
cc @hdietze @mchibucos

**Comment by cmungall** [comment]
Added this http://purl.obolibrary.org/obo/RO_0002162 'axiom has evidence'

 * Def: *A relationship between a sentence and an instance of a piece of evidence in which the evidence supports the axiom*
 * curator note: *This annotation property is intended to be used in an OWL Axiom Annotation to connect an OWL Axiom to an instance of an ECO (evidence type ontology class). Because in OWL, all axiom annotations must use an Annotation Property, the value of the annotation cannot be an OWL individual, the convention is to use an IRI of the individual.*

Unfortunately it's hard to disentangle some aspects of modeling evidential relationships from the host language (OWL). This AP must be an AP, and is intended specifically for axiom->individual relationships (using IRI as a proxy)

**Comment by cmungall** [comment]
How should we related an instance of an ECO class to a publication?

IAO has the OP:
http://purl.obolibrary.org/obo/IAO_0000136

I recommend we do this. Forces a commitment to ECO classes being ICEs but I think this is in line with @mchibucos' thinking

**Comment by nlharris** [comment]
Is this still needed?

**Comment by mchibucos** [comment]
I'm actually not sure, but I just sent Michelle Giglio this ticket. She'd be in a better position to tell you about current development. Thank you!

**Comment by mgiglio99** [comment]
Hello @nlharris and @cmungall 
I wasn't involved in this issue originally and in reading it now, I'm not clear on what was happening here.
Happy to chat on this if you'd like.
Michelle

**Comment by nlharris** [comment]
If you're also not sure what this is about, I think we can probably close this ticket. Ok?

**Comment by nlharris** [comment]
closing; reopen (or start a new ticket) if needed.
