### ISSUE TITLE
should contained_in be a sub-property of located_in?

### ISSUE THREAD

**Issue by jclerman** [oborel/obo-relations#693]
I didn't see this question mentioned in earlier issues, nor do I see it addressed in the descriptions of the respective properties, so:

As best I can tell, `contained_in` ([RO:0001018](http://purl.obolibrary.org/obo/RO_0001018)) is a special case of `located_in` ([RO:0001025](http://purl.obolibrary.org/obo/RO_0001025)) - would it make sense to acknowledge that by making the former a sub-property of the latter?

I'm trying to decide how best to use these in an ontology I'm developing, and insight on this question would be helpful.

**Comment by wdduncan** [comment]
The range for `contained in` is 
<img width="247" alt="image" src="https://user-images.githubusercontent.com/3186638/224330142-8772bf99-ff54-48b0-8432-1d151d7abe7c.png">

Whereas, the range for `located in` is 
<img width="264" alt="image" src="https://user-images.githubusercontent.com/3186638/224330015-9d5fe53d-f7d9-4c42-8ec6-c014e4a52943.png">

So, it seems that `located in` should be a subproperty of `contained in`.  

I do not understand why `located in` excludes spatial regions in its range. Perhaps `located in` is meant to be reserved for cased where a material entity bounds the spatial region (in some sense). I'm only speculating here. Maybe one of the RO gurus (e.g., @cmungall @balhoff @dosumis ) can shed more light on this.

**Comment by jclerman** [comment]
Ah, I somehow hadn't noticed the domain & range for `located in`.  Something's a bit odd about it (but maybe that's in deference to the reasoners in common use) since technically, the 2nd element of the range-intersection (`independent continuant`) is redundant.

I understand that it might not be acceptable for `located in` to be a subproperty of `contained in`, since `located in` is marked as transitive, but `contained in` is not.

My original question was rooted in my understanding based on the textual definitions of the two properties.  Paraphrasing:

* `contained in` is a relationship between **material** and **immaterial** continuants (this is already in conflict with the asserted OWL range `independent continuant` - so it'd be nice to get those into alignment if possible).  Examples include physical things that are related to immaterial spaces ("lung in thoracic cavity", etc) and so this is stipulated not to be a transitive relation (though with correct domain & range criteria, that stipulation should be unnecessary, I think).
* `located in` appears, based on textual description, to be broader than `contained in` - it's just any two independent continuants, one of which is entirely "within" the other.  That seems (to me) to be true of any `contained in` relation - thus my suggestion.

**Comment by wdduncan** [comment]
> the 2nd element of the range-intersection (independent continuant) is redundant.

Yes. It is redundant. I don't know why it is there.

>  it might not be acceptable for located in to be a subproperty of contained in, since located in is marked as transitive, but contained in is not

Nice catch! I didn't notice that. This raises the question (to me at least) as to why `contained in` isn't defined as transitive. Seems to make sense that if X `contained in` Y and Y `contained in` Z, then X `contained in` Z. However, the reason for creating the relation may involve a use case for which transitivity doesn't apply. I don't know the history of the relation.

> contained in is a relationship between material and immaterial continuants 

Yes. The domain of `contained in` is **more** restrictive (`material entity`) than the domain of `located in`, which incudes `immaterial entity` (such as `site`) sans `spatial region`.

However the range of `contained in` is **less** restrictive than the range `located in`

> (this is already in conflict with the asserted OWL range independent continuant ...)

Sorry ... not following you here. A `spatial region` is a type of `immaterial entity` (i.e., a type of immaterial continuant).

> located in appears, based on textual description, to be broader than contained in ...

Linguistically, this seems to be the case. Perhaps this is good reason for `contained in` to be a subproperty of `located in`. 

Can others more familiar with the history of the `contained in` relation weigh in?

**Comment by cmungall** [comment]
This comes from the bfo reference guide. I do not think SR is a useful
class and I do not think we should have unusual complex expressions as
ranges or domains

The solution here is a simple range plus an additional complementof axiom
to exclude SR

**Comment by jclerman** [comment]
I should have been more clear in my original issue-description, I think.

As noted, it seems from the textual description of `located in` and `contained in` that the former is broader than the latter, and that it would therefore be convenient for `contained in` to be modeled as a sub-property of `located in`.  But that's based on an implicit assumption on my part, which may be incorrect.  To wit:

### `located in`
The `definition` annotation for `located in` is:
> a relation between two independent continuants, the target and the location, in which the target is entirely within the location

So, it sounds like the OWL range & domain should both be `independent continuant`.  `spatial region` is excluded in the current OWL range & domain - but I don't see an explanation for that in the above definition, nor is it obvious what modeling benefit that exclusion confers.

### `contained in`
The `definition` annotation for `contained in` begins:
> Containment obtains in each case between **material** and **immaterial** **continuants**, for instance: lung contained_in thoracic cavity; bladder contained_in pelvic cavity. Hence containment is not a transitive relation.

To me, it sounds like that should translate to an OWL domain & range of `material entity` and `immaterial entity`, respectively.  The currently modeled range for `contained in` is `independent continuant`, which is too broad given the textual description (that's what I meant above, when I said the OWL range was "in conflict" with the textual definition).

**So**, that's what led to my original question.  If the OWL range and domain of the two properties were to be updated to what it sounds like their textual descriptions describe, `located in` could at least possibly be a super-property of `contained in`, and that would make for a slightly simpler more elegant model (IMO) - since it does seem natural that things that are "contained" in something are also "located" in it (though not necessarily vice-versa).

**Comment by wdduncan** [comment]
@jclerman There is RO call on Tues. 03/28 at 12pm ET.  [Zoom link](https://lbnl.zoom.us/j/97163538233?pwd=czlTWTRzb0YvY0sxa1hwWERZUTFEQT09)

Are you able to join?

See [here]( http://bit.ly/ro-minutes) for the meeting minutes if you want to comment on your issue.

**Comment by jclerman** [comment]
Thanks @wdduncan, happy to! I should be able to join for the first 30 minutes; not sure how long those meetings usually go. I'll look at the minutes doc tonight or tomorrow.

**Comment by jclerman** [comment]
Unfortunately, I won't be able to attend the mtg today.

**Comment by wdduncan** [comment]
> "Containment obtains in each case between material and immaterial continuants, for instance: lung contained_in thoracic cavity; bladder contained_in pelvic cavity. Hence containment is not a transitive relation."

Thanks @cmungall I didn't catch that!

> the range of located_in comes from BFO, and the BFO reference guide

Yes. I was well aware of that. I just don't understand the reasoning behind it :(

I agree with your proposals:
- obsolete `contained in`
- leave `located in` as is
