### ISSUE TITLE
Port remaining ChEBI relations to RO

### ISSUE THREAD

**Issue by cthoyt** [oborel/obo-relations#697]
Following #643, there are a few relations from ChEBI that would benefit from inclusion in RO (also as part of a more general effort to get rid of hash relations across the OBO ecosystem):

- has functional parent
- has parent hydride
- is enantiomer of
- is substituent group of
- is tautomer of

These are described in [this internal Google doc for ChEBI annotators](https://docs.google.com/document/d/1EZHaOEl-iPZPbqD_GRyIetDoA4U8U2SPr9Qk6RKVRc0/edit#heading=h.o8b3r6la80rf), but some of the descriptions are pretty difficult to decipher

**Comment by wdduncan** [comment]
@cthoyt I don't know that much about functional groups and molecular graphs, so I am not qualified to review these relations. Is there someone you would like to review them?

I noticed that definitions include the word `obo:has_part `. Can you just say `has part`? Does using `obo:has_part` have special significance?

**Comment by cthoyt** [comment]
I hate to put more on his plate, but Chris Mungall is a good candidate. @bvarner-ebi was active in the last discussion and as always input from the chebi side from @amalik01 is valuable
