### ISSUE TITLE
NTR: supplies blood to; drains blood from

### ISSUE THREAD

**Issue by dosumis** [oborel/obo-relations#699]
Make new subproperties of supplies/drains: "supplies blood to" / "drains blood from" with domains 'arterial blood vessel' and 'venous blood vessel'' respectively (these classes cover the microvasculature as well as arteries and veins.). 

Background: These will replace usage of supplies and drains in Uberon, where they have been used extensively but with domain and range added locally - illegally restricting the meaning of these relations & being the the potential source of problematic inferences where drains and supplies are used outside of an anatomical context (e.g. for rivers).

**Comment by cthoyt** [comment]
does this apply to ticks, mosquitos, and/or vampires?

**Comment by dosumis** [comment]
I guess tempting to 'drains blood from' for feeding ticks, mosquitos and vampires, but domain restricts it to vertebrate(?) veinous vessels (veins, venules)

**Comment by bvarner-ebi** [comment]
Of note- this issue is dependent on the completion of https://github.com/oborel/obo-relations/issues/695 as there is currently no Uberon import to RO. Without the import, the requested domains can not be added.

**Comment by wdduncan** [comment]
I've submitted #701 to address consistency for domains and/or ranges.

**Comment by wdduncan** [comment]
Notes for RO Call:

Are just intending to constrain the current [RO drains](http://purl.obolibrary.org/obo/RO_0002179) so that it only involves blood? If so, are you okay with syringe also being used with this relation?

Label suggestion: `vessel drains blood` / `vessel supplies blood`

**Comment by dosumis** [comment]
Decision punted to @cmungall :

Either 
(a) - Roll back from all this complexity and just promote much more general use of drains and supplies.  I  just reviewed a bunch of tickets on drains/supplies/channels - I worry that the complexity is unsustainable.  There is a very small amount of positive inference in Uberon coming from the domain of each of these terms (a hand full of inferences) but it would be no big deal to add these manually. The downside is losing some consistency checking in Uberon, but are we really that worried about these being used for something dumb?  The inconsistencies we have found all look defensible to me if we allow for a more general usage/meaning (e.g draining calyces of the kidney).
(b) Add as requested but with more specific names - 'vessel drains blood' & 'vessel supplies blood'.  These were requested in the RO call as without them drains_blood might be applies to medical devices or mosquitos.

**Comment by wdduncan** [comment]
Any update on this?

**Comment by cmungall** [comment]
I favor b, with names "vessel for draining blood from" and "vessel for supplying blood to"

or another naming convention that might be more scalable is "(domain) genericRelation (range)" [including the parentheses]

E.g. "(vessel) drains (blood)"

I am wondering if we want to revise the shoreline and just include these in uberon with uberon IDs They are not reusable outside uberon or a descendant of uberon (e.g ZFA). This feels more modular.

**Comment by wdduncan** [comment]
I like the naming convention `(domain) genericRelation (range)`, but I worry it will be off putting to user.

**Comment by wdduncan** [comment]
Note: `(vessel) drains (blood)` does not contain "from" or "to". So, it may not be clear what the intent is.

E.g.: 
(vessel) for draining (blood) from  
However, if "(blood)" is the domain indicated by this syntactic convention, it obfuscates that there is an organ from which the blood is being drained.

To make this more specific you would something like:
(vessel) for draining blood from (organ)  

This seems awkward. Perhaps that may be of use for more general relations.

The sentiment on RO call is to not implement the syntactic convention. 

Minor suggestion is to add an "is" to the front of the label:  
"is vessel for draining blood from" and "is vessel for supplying blood to"

Another suggestion is to define a general `vessel drains` relation and then check for consistency using GCIs in UBERON.

**Comment by balhoff** [comment]
Can Uberon folks provide an example of the consistency checking that would be lost by just using the existing RO [drains](http://purl.obolibrary.org/obo/RO_0002179)? There may be a reasonable way to implement the constraints in Uberon using GCIs or rolification.

**Comment by bvarner-ebi** [comment]
Checking in on this ticket.
Is there consensus on creating new Uberon terms [as suggested here](https://github.com/oborel/obo-relations/issues/699#issuecomment-1639520546) with no change in RO?

**Comment by allenbaron** [comment]
The use of supplies/drains as a general property could get confusing in the case of something where multiple different substances are supplied or drained. Even limiting to liquids in anatomy the example of the 'urinary bladder' demonstrates this. In Uberon v2023-12-08, the 'urinary bladder' is currently listed with a "supplies" axiom from 'superior vesical artery' and a "drains" axiom from 'vesical vein'. That's fine for blood but what about urine which is also supplied to and drained from it?

**Comment by jamesamcl** [comment]
In the interest of getting things moving here as it has been 10+ months, I spoke to @cmungall  about this. We have agreed the best plan of action is to create specific relations, but to keep them in RO as we already have very specific relations here.
