### ISSUE TITLE
Objection to including "atemporal" versions of BFO2 relations in RO

### ISSUE THREAD

**Issue by GoogleCodeExporter** [oborel/obo-relations#7]
```
These are not well defined and would function equivalently outside RO. I see no 
reason to change existing  identifiers, but their inclusion in RO dilutes the 
goal of having RO being an artifact that aspires to Foundry, given that they 
lack pertinent definitions.
```

Original issue reported on code.google.com by `alanruttenberg@gmail.com` on 7 May 2013 at 7:00

**Comment by nlharris** [comment]
Is there an action item here?

**Comment by balhoff** [comment]
These relations are widely used at this point. A proposal for temporal relations could be made in a new pull request is someone wants to work on that.
