### ISSUE TITLE
causal relations for environmental process?

### ISSUE THREAD

**Issue by pbuttigieg** [oborel/obo-relations#71]
I'd like to use the experimental causal relations like:
`ObjectProperty: <http://purl.obolibrary.org/obo/RO_0002404> # causally downstream of
ObjectProperty: <http://purl.obolibrary.org/obo/RO_0002427> # causally downstream of or within
ObjectProperty: <http://purl.obolibrary.org/obo/RO_0002411> # causally upstream of
ObjectProperty: <http://purl.obolibrary.org/obo/RO_0002418> # causally upstream of or within`

...for environmental processes.
e.g. `deforestation` 'causally upstream of' `reforestation` 

Is there scope to broaden the `causally related to` definition to accommodate such things? Seems a shame to restrict such a seemingly general class to activation and inhibition.

**Comment by nlharris** [comment]
@pbuttigieg what is the status of this?

**Comment by nlharris** [comment]
This is a very old ticket; can it be closed?
