### ISSUE TITLE
New term request: ‘positively correlated with’ and ‘negatively correlated with’

### ISSUE THREAD

**Issue by CDowland** [oborel/obo-relations#710]
This request is for two subtypes of the preexisting RO term 'correlated with' (http://purl.obolibrary.org/obo/RO_0002610), which is annotated as follows:
```
Definition: A relationship that holds between two entities, where the entities exhibit a statistical dependence relationship. The entities may be statistical variables, or they may be other kinds of entities such as diseases, chemical entities or processes.

Curator note: Groups both positive and negative correlation
```

I’m requesting 'positively correlated with' and 'negatively correlated with' as subtypes of 'correlated with'.

## Preferred term label
`positively correlated with`

## Textual definition
`Correlation for which the statistical dependence is positive.`

## Suggested parent term
`RO: correlated with (http://purl.obolibrary.org/obo/RO_0002610)`

## Attribution
`ORCID ID: 0000-0003-1909-9269`

## Preferred term label
`negatively correlated with`

## Textual definition
`Correlation for which the statistical dependence is negative.`

## Suggested parent term
`RO: correlated with (http://purl.obolibrary.org/obo/RO_0002610)`

## Attribution
`ORCID ID: 0000-0003-1909-9269`

As the definition for 'correlated with' notes, a variety of ontological types can occupy the domain and range positions. No domain and range are specified for it, which seems like the right approach for these subtypes as well. 

The definitions are based on the definitions of 'correlated with,' adapted to indicate whether the correlation is positive or negative. But perhaps there are clearer/better ways to define them.

**Comment by wdduncan** [comment]
The definition references the use of statistics, but the label does not. Not all "correlations" are statistical in nature. If you intend this relation to be about things calculated using statistical methods, then we suggest modifying the label to reflect this.

**Comment by CDowland** [comment]
I'm proposing these as subtypes of RO: 'correlated with', which is indeed a statistical relation, and likewise mentions statistics in the definition but not in the label.

**Comment by CDowland** [comment]
Below is a revised request for the two terms that I hope avoids the concerns raised.  

Label: positively correlated with
Alternative term: directly correlated with
Definition: A relation between entities in which one increases or decreases as the other does the same.
Definition source: [](https://dictionary.apa.org/positive-correlation)
Suggested parent term: RO: correlated with [](http://purl.obolibrary.org/obo/RO_0002610)
Characteristics: Symmetric, Reflexive
Attribution: ORCID ID: 0000-0003-1909-9269

Label: negatively correlated with
Alternative term: inversely correlated with
Definition: A relation between entities in which one increases as the other decreases. 
Definition source: [](https://dictionary.apa.org/negative-correlation)
Suggested parent term: RO: correlated with [](http://purl.obolibrary.org/obo/RO_0002610)
Characteristics: Symmetric, Irreflexive
Attribution: ORCID ID: 0000-0003-1909-9269


> Also, it would be quite helpful if you (or another member of the OBIB) would join the RO calls when new terms from the OBIB group are requested. It helps move the term approval process more quickly.

This request is not from the OBIB group, but point taken. I’ve now joined the Google group and have the meeting series on my calendar.

**Comment by wdduncan** [comment]
@bpeters42 and @nataled are you satisfied with the definition? (I am.)

Re 'statistical' in label: The revised definitions don't mention statistics. So, I think the label is fine.

**Comment by nataled** [comment]
Looks good to me.

**Comment by wdduncan** [comment]
@CDowland You term is approved :)   
If I assign an IRI for the term are you (or someone in your group) able to make a PR for this?

**Comment by CDowland** [comment]
Great, thanks! And yes on the pull request.

**Comment by wdduncan** [comment]
Thanks @CDowland   
Please use id `RO_0017003`.

**Comment by CDowland** [comment]
@wdduncan We'll need one more since there are two terms. Thanks.

**Comment by wdduncan** [comment]
Hah! Good catch @CDowland !  
Please also use `RO_0017004`

**Comment by wdduncan** [comment]
Close via https://github.com/oborel/obo-relations/pull/719.
