### ISSUE TITLE
NTR: 'contains measured amount'

### ISSUE THREAD

**Issue by jmwhorton** [oborel/obo-relations#712]
Note: this relationship is currently in OBIB (http://purl.obolibrary.org/obo/OBIB_0000038)

## Preferred term label

has actual load

## Textual definition

A relation that relates a container to a measurement datum that specifies the actual amount of material in the container.

## Definition Source

Penn Group

## Term Editor

Person: Jie Zheng, Chris Stoeckert

**Comment by wdduncan** [comment]
By 'amount' do you mean its weight? Or volume? Or would categorical units be allows, e.g. 'half full'.

It was also suggested that 'actual' be removed from the name.

**Comment by jmwhorton** [comment]
I'm going to tag @zhengj2007 and @cstoeckert to address any feedback on this term.

**Comment by cstoeckert** [comment]
For the same reasons as commented in https://github.com/oborel/obo-relations/issues/711 I think this should apply to both weight and volume. I also think including "actual" in the label helps distinguish which relation to use for the case of a 50 ml conical tube (has max capacity) containing 25 ml (has actual load). The restriction is for a measurement datum so categorical units are fine for that in my opinion.

**Comment by nataled** [comment]
Definitely not 'has actual capacity' since that would be synonymous with 'has maximum capacity'. And although I think it's mildly superfluous, I don't have much objection to including 'actual' in the name since people often refer to 'actual amounts' of things.

**Comment by wdduncan** [comment]
> Definitely not 'has actual capacity' since that would be synonymous with 'has maximum capacity'.

Right! My mistake :)

> I don't have much objection to including 'actual' in the name since people often refer to 'actual amounts' of things.

Sure ... In most (maybe all) contexts I've dealt with dealing with measurements (e.g., weight, volume, height, duration), 'actual' was assumed, and max/min had to be stated.

**Comment by wdduncan** [comment]
> How about 'has contained amount' ?  

'contains amount' sounds more natural to me, but I'm okay with the label 'has contained amount'.  

The way definition current reads it would be necessary to import `measurement datum` to formally specify the range. One way to do this would be to create a COB import that includes `measurement datum`. @matentzn do you suggest a better way?

@cstoeckert If I assign an IRI for the term are you (or someone in your group) able to make a PR for this?

**Comment by cstoeckert** [comment]
@wdduncan yes I or someone from OBIB can work on this. Thanks.

**Comment by wdduncan** [comment]
Thanks @cstoeckert   
Please use `RO_0017002` as the namespace id in the new term.

**Comment by cstoeckert** [comment]
@wdduncan I'm planning to bring this up at the next OBIB call (scheduled for May 25) to get someone to work on it. They will need write access to this repository.

**Comment by cmungall** [comment]
> They will need write access to this repository.

This is not necessary for RO, nor for any other public repo on github. The beauty of github is that anyone can fork and make a PR

Having said that, it's sometimes a bit less hassle to make PRs on origin rather than a fork and we grant access to regular editors for this purpose. But not having merge abilities should never be an obstacle to contribution!

**Comment by wdduncan** [comment]
@jmwhorton has been submitting terms to RO. Will he be handling this?

**Comment by jmwhorton** [comment]
I am, yes.  This one actually has a pull request, which might not be obvious since a new label was picked (and the pull request named accordingly): #726

**Comment by wdduncan** [comment]
Thanks @jmwhorton ! I forgot about #726.  
Added a 'fixes' comment.
