### ISSUE TITLE
import COB into RO

### ISSUE THREAD

**Issue by wdduncan** [oborel/obo-relations#716]
@cmungall @matentzn @nataled @balhoff @jamesaoverton:
On the 2023-04-25 call, @bpeters42 mentioned importing COB in order allow for assignment of domains and ranges. E.g., #712 mentions `measurement data item` in the definition. 

This sounds reasonable to me, but what are your thoughts.

**Comment by wdduncan** [comment]
If we are going to import COB terms, we need to decide if the import will have COB IRI or the IRI of the equivalent 3rd party term (e.g., OBI:organism).  
At present, we can't use COB to import 3rd party terms.

**Comment by matentzn** [comment]
> we need to decide if the import will have COB IRI or the IRI of the equivalent 3rd party term

Whatever cob.owl says! If the terms are officially rewired during the COB release process, they should be used, i.e. https://www.ebi.ac.uk/ols4/ontologies/cob

> At present, we can't use COB to import 3rd party terms.

Very interesting problem! This requires a COB issue "Who owns COB terms imported from 3rd parties?"  and a bit of discussion.. In my opinion, something super weird should be done: The original IDs should be effectively ceded to COB (I am only 50,01% sure this is a good idea though, and 55% that its going to be very difficult). Very interesting point, thanks for raising it.
