### ISSUE TITLE
NCIt Term Suggestions for Cross-Reference

### ISSUE THREAD

**Issue by ssyeds3** [oborel/obo-relations#720]
The NCI Cancer Research Data Commons (CRDC) Program (https://datacommons.cancer.gov/) is developing data standards for submitting data to the CRDC ecosystem. As part of this effort, the CRDC Data Standards Service (DSS) Team is identifying industry standards that can be leveraged for this harmonization and standardization effort.

In the process of mapping valid values between various ontologies and NCIt we (the DSS Team) came across terms in the RO ontology that either did not have a cross-reference to NCIt terms or that we thought did not cross-reference to the correct NCIt term (please see below):

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/syeds3/AppData/Local/Temp/1/msohtmlclip1/10/clip.htm">
<link rel=File-List
href="file:///C:/Users/syeds3/AppData/Local/Temp/1/msohtmlclip1/10/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

RO Term | RO ID | NCIt Term   Suggestion for Cross-Reference
-- | -- | --
surrounded by | RO:0002219 | Surrounding   (C52247)

</body>

</html>

**Comment by wdduncan** [comment]
Hi @ssyeds3  
Mappings between NCIT and RO could be established. However, thinking of the top of my head, I think the [OBO version of the NCIT](https://ontobee.org/ontology/NCIT) might be the better place for such mappings. What do you think @cmungall ?

In regards to your specific example (`Surrounding`). The semantics are different than `surrounded by`. `Surrounding` is a `Property or Attribute` in NCIT, but `surrounded by` is an object property in RO. So, while a mapping is possible, it won't line up exactly the same from a semantic standpoint.

**Comment by wdduncan** [comment]
We discussed this on the RO call and decided due to the issues mentioned that this is not something we can implement right now.
