### ISSUE TITLE
Issues remaining after #732

### ISSUE THREAD

**Issue by cthoyt** [oborel/obo-relations#733]
Because of the decision to do many PRs that conflated revers and updates, it was very difficult to find issues. Here's what I found so far

1. Merge conflict left sitting here (should be handled by CI) https://github.com/oborel/obo-relations/blob/97a906a4d3d6ac2b44339f1928a0d2555523dc49/src/ontology/catalog-v001.xml#L22
2. Non HTTPS orcid url (should be handled by CI)
https://github.com/oborel/obo-relations/blob/97a906a4d3d6ac2b44339f1928a0d2555523dc49/src/ontology/ro-edit.owl#L6485
3. Five spurious `^^xsd:dateTime` added (these are actually correct, but not it's frustrating that they just showed up during the recent mess)
   - https://github.com/oborel/obo-relations/blob/97a906a4d3d6ac2b44339f1928a0d2555523dc49/src/ontology/ro-edit.owl#L6660
   - https://github.com/oborel/obo-relations/blob/97a906a4d3d6ac2b44339f1928a0d2555523dc49/src/ontology/ro-edit.owl#L6673
   - https://github.com/oborel/obo-relations/blob/97a906a4d3d6ac2b44339f1928a0d2555523dc49/src/ontology/ro-edit.owl#L6686
   - https://github.com/oborel/obo-relations/blob/97a906a4d3d6ac2b44339f1928a0d2555523dc49/src/ontology/ro-edit.owl#L6699
   - https://github.com/oborel/obo-relations/blob/97a906a4d3d6ac2b44339f1928a0d2555523dc49/src/ontology/ro-edit.owl#L6712

**Comment by anitacaron** [comment]
The item 3 is correct this way. If there're properies of type date whithout the datatype xsd:dateTime, it'll be read as string which is wrong.

**Comment by wdduncan** [comment]
Can this be closed now?

**Comment by anitacaron** [comment]
No, we still need to fix these minor issues.
