### ISSUE TITLE
Add additional biotic interaction relations

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#74]
EOL and globi use relations like 'kills'
https://github.com/jhpoelen/eol-globi-data/issues/143

We should provide these relations in a systematic way. So far they have been added on an as-needed basis, but as these relations are convenience shortcuts that wrap a behavior process, we should add something that generates this, e.g. from NBO.

**Comment by pbuttigieg** [comment]
+1
ping me if you'd like assistance here.

**Comment by jhpoelen** [comment]
@cmungall please feel free to close this issue. Term "kills" has been added.

**Comment by jhpoelen** [comment]
Please note that this has been addressed by http://purl.obolibrary.org/obo/RO_0002626 and http://purl.obolibrary.org/obo/RO_0002627 . @cmungall @pbuttigieg thanks!
