### ISSUE TITLE
Form RO governance domains

### ISSUE THREAD

**Issue by wdduncan** [oborel/obo-relations#745]
In order make RO more efficient, @cmungall has suggested that we modularize the governance of RO into groups that are responsible for reviewing new term requests (or editing of current terms) with their specific domain.

An incomplete list of domains include:
* RO core
* Anatomical relations
* Relations involving organizations (e.g., appointed administrator of)
* Ecological interactions
* Environment relations
* Genomic relations
* Chemical relations

cc @balhoff @diatomsRcool @nataled @ddooley @nlharris @bpeters42 @matentzn @CDowland @dosumis @addiehl @anitacaron @zhengj2007 @yongqunh @cthoyt @diatomsRcool 

Apologies if I left someone off.

**Comment by cmungall** [comment]
I think there are multiple ways to set this up:

If a group decide to get together to maintain a branch of RO, they make a PR to add a markdown file to the docs/ folder, where they document what branche(s) are covered, who the people involved are (github handles), and their roles, and their preferred means of communication (slack, meetings, github mentions, ...). The RO core group would merge this if they approve, and this group would have autonomy over that branch
