### ISSUE TITLE
Add a new causal property chain

### ISSUE THREAD

**Issue by ukemi** [oborel/obo-relations#746]
To create inferences that will result in additional GO annotations from GO-CAM models, can we add a property chain:

causally_upstream_of _or _within o part _of -> causally_upstream_of _or _within

and perhaps any similar that are missing?

**Comment by ukemi** [comment]
acts_upstream_of_or_within o part_of -> acts_upstream_of_or_within

**Comment by balhoff** [comment]
@ukemi I'm reconsidering whether this is right. If you have these instances:

- `<1> 'causally upstream of' <2>`
- `<2> 'part of' <3>`

Inference (among others):
- `<1> 'causally upstream of or within' <2>`

But we know that 1 is upstream of 2, not within. We used to have chains like `regulates o 'part of' -> regulates` (in GO), but took them out. I think this is similar. I guess the question is: if a process is causally upstream of one part of another process X, is it causally upstream of X itself? Maybe so...

**Comment by ukemi** [comment]
Hi @balhoff. If the part_of is a relationship between an MF and a BP. Even if MF1 is causally_upstream_of MF2 and MF2 is part_of BP1, MF1 can be causally_upstream_of BP1 or part_of BP1. Right?

**Comment by balhoff** [comment]
@ukemi if MF1 regulates MF2, which is part_of BP2, is MF1 necessarily one of these two?
- causally_upstream_of BP2
- part_of BP2

I think the proposed chain implies that one of those two must be true. But is that necessary? If an MF regulates an MF that is part of a BP, is it definitely causally upstream of the whole BP?

**Comment by ukemi** [comment]
@balhoff 

 _If an MF regulates an MF that is part of a BP, is it definitely causally upstream of the whole BP?_

Think of a signaling cascade where successive function regulate the next downstream function. They are all part of the cascade.

**Comment by balhoff** [comment]
I added `'causally upstream of or within' o 'part of' -> 'causally upstream of or within'` in #771. I considered whether we could add `'causally upstream of' o 'part of' -> 'causally upstream of'`, but realized that would not work for a subprocess upstream of another subprocess of a larger process. Since the 'causally upstream of' is a subproperty of 'precedes', the first process can't be both part of and precede the larger process.
