### ISSUE TITLE
relationship between an intrinsic neuron and its neuropil of innervation

### ISSUE THREAD

**Issue by Clare72** [oborel/obo-relations#754]
Ideally, intrinsic neurons have all of their synapses restricted to a particular region of the CNS. In real life there may be a few stray synapses just outside the region.

Label: 'synapses restricted to region'
Exact synonym: 'intrinsic to'
Definition: 'A relationship between a neuron and a region, where the neuron has essentially all of its synapses in that region.'
Comment: 'Relationship may still be used if a very small number of synapses fall slightly outside the boundaries of the region.'
Parent: RO:0013001 ('has synaptic IO in region')
Domain: CL:0000540 ('neuron') - will be inherited from 'has synaptic terminal in'

I don't think we want to make this a subproperty of input and output relationships, in case there are neurons that do not have one or the other - some sensory neurons might not have synaptic inputs(?)

related to https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/issues/1626

**Comment by addiehl** [comment]
Suggested that text definition be based on parent property phrasing (per David OS):

A relationship between a neuron and a region, where all of the functionally relevant input and output synapses are in that region.

Add a comment that any class using this relation should not have another restriction using this relation to a non-overlapping region.

**Comment by ddooley** [comment]
Reviewed On Nov4 2024. @Clare72 Are you able to finalize the textual definition based on above comments?

**Comment by Clare72** [comment]
Does the existing PR need changing?
