### ISSUE TITLE
Use of material entity relations on GDCs borne by material entities

### ISSUE THREAD

**Issue by mbrush** [oborel/obo-relations#76]
In practice, do people use properties that are defined as having a material entity as a domain when the subject of the relation is a generically dependent continuants (GDCs) that is _materialized in_ a material entity ('materialized in' being a shortcut over  'is concretized as' o 'inheres in')?  This is particularly relevant in the area of sequence/genetic entities, as the Sequence Ontology models these as GDCs. Here a genetic variant such as a single nucleotide polymorphism is a GDC that 'is concretized as' some specifically-dependent continuant that 'inheres in' some material entity such as a DNA molecule. 

A specific example of such a property is RO_0002600 - 'capable of upregulating or causing pathological process'. This property is under the 'causal relation between material entity and a process' branch of RO, which of course holds properties relating material entities to processes.  A SNP modeled in accordance with SO is a GDC, not a material entity. So it is ontologically incorrect to use RO_0002600 to link a SNP individual to a disease where it is known to play a causal role. But it would be nice to be able to use a single relation for relating variants as materials or GDCs to diseases they cause - rather than have to create a second relation with the same meaning that holds for GDCs instead of material entities. 

So what is recommended here? How are properties such as this applied practice? Can the scope of such properties be expanded to allow for applications such as the one outlined above?

**Comment by rlwalls2008** [comment]
Seems like a possible solution is to add to the domain of 'causal relation
between material entity and a process' a GDC that 'is concretized as' o
'inheres in' some 'material entity' although that clearly conflicts with
the label of 'causal relation between material entity and a process'.
Alternatively, maybe a superclass like 'causal relation' could be added,
that has an expanded domain.

I definitely see the utility of what you want to do.

>

**Comment by dosumis** [comment]
Hi Matt,

You should check on the progress of molecular SO and how this is formalised.  This is an ontology of hte materialised (concretized?) forms of SO GDCs.  At GO we use SO as if it refers to the material forms right now, but aim to switch to using MSO once it is available.

**Comment by mbrush** [comment]
HI David.  I have looked into this, as we had been helping with this work a while back.  I don't think their planned work will address the issue at hand however.  Last I heard, the MSO will be where logical axioms live, which will describe material sequence entities. Classes in the parallel SO ontology will for the most part only have logical axioms linking to the corresponding MSO term.  For example, the SO:gene class might be defined as an SO:region that is *materialized_in* or *is_about* some MSO:gene (the exact bridging relation is t.b.d, as is the status of SO regions as GDCs or ICEs). 

So given that axiomitization will live in MSO, there will be no logical link from an SO:variant to related entities such as diseases except through the MSO counterpart.  But point taken that we should coordinate with them in making a decision on how to address the issue in this ticket.

**Comment by nlharris** [comment]
@mbrush was this resolved?

**Comment by nlharris** [comment]
Can this be closed?

**Comment by nlharris** [comment]
Closing; please reopen if needed.
