### ISSUE TITLE
Adding the now deprecated relation "has divisor entity" from PATO

### ISSUE THREAD

**Issue by LarsVogt** [oborel/obo-relations#774]
For new term requests, please provide the following information:

## Preferred term label

has divisor entity

## Synonyms

has divisor

## Textual definition

A relationship between a ratio or proportion and its divisor.

## Suggested parent term

[RO](http://purl.obolibrary.org/obo/RO_0002502)

## Attribution

https://orcid.org/0000-0002-8280-0487

**Comment by LarsVogt** [comment]
This issue relates to the issue https://github.com/pato-ontology/pato/issues/454 in PATO. Nico told me to ask @anitacaron for help adding this.

**Comment by nataled** [comment]
Can have 'has denominator' as synonym.

**Comment by rays22** [comment]
This relationship would be relevant to model phenotypic traits, for example, the traits that represent the ratio of urinary sodium to potassium concentration in biological samples, or the waist circumference to height ratio.

Similar relationships are used to model ratio-related plant phenotypic traits and attributes, e.g.[TO:0000278 root to shoot ratio](https://www.ebi.ac.uk/ols4/ontologies/to/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FTO_0000278) :
1. [TO:has_dividend_quality](https://www.ebi.ac.uk/ols4/ontologies/to/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FTO_has_dividend_quality?lang=en)
2. [TO:has_divisor_quality](https://www.ebi.ac.uk/ols4/ontologies/to/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FTO_has_divisor_quality?lang=en)

Regarding the label or synonyms, both `has numerator` and `has dividend` look fine to me.
Regarding the label or synonyms, both `has denominator` and `has divisor` look fine to me.

Maybe also add a new `arithmetic relationship` to group this and any [related relationships.](https://github.com/oborel/obo-relations/issues/775)
