### ISSUE TITLE
Consider adding global reflexivity axiom for part of

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#78]
Continued from https://github.com/obophenotype/uberon/issues/1159

We avoid global reflexivity for reasons outlined here:
https://github.com/oborel/obo-relations/wiki/ROGuideDraft#local-reflexivity

However, I would argue an exception can be made for part-of, as it is a universally applicable relation regardless of upper level category

As the uberon ticket shows, it is certainly useful for inference

See also #43

**Comment by dosumis** [comment]
I don't think we should change the semantics of such a widely used
relationship.  There could be serious consequences for query answering,
classification and scaling for resources built assuming no reflexivity. No
harm in adding a reflexive po relation.  If the use case is improved
consistency checking, why not just set up a test that switches on
reflexivity of po just for the test?

**Comment by cmungall** [comment]
I think an additional axiom as powerful as this one would have to approved by all ontologies using it. This ticket is intended to be more about exploring the consequences rather than actually making the change

**Comment by cmungall** [comment]
It seems one of the main unintented consequences is things like "X part" or "X segment" terms classifying under "X"

**Comment by nlharris** [comment]
This is very old -- is it still relevant or can we close it?

**Comment by balhoff** [comment]
I vote to close. I used to want a reflexive part_of but I think it would be too disruptive to make this change now. Would be good to get some other opinions.
