### ISSUE TITLE
Add `develops from o part of -> develops from` property chain

### ISSUE THREAD

**Issue by anitacaron** [oborel/obo-relations#784]
> Let's make a separate RO issue for adding the rolification constraint on the 1st. This is low priority as I will wager there are zero tbox existentials in OBO connecting organism to anything bigger. But the point is this should be a RO issue 

 _Originally posted by @cmungall in [#2381](https://github.com/obophenotype/uberon/issues/2381#issuecomment-1648318731)_

**Comment by ddooley** [comment]
@anitacaron We are closing this in favour of Damien's https://github.com/oborel/obo-relations/issues/814.
