### ISSUE TITLE
Edit `has developmental contribution from` property chain

### ISSUE THREAD

**Issue by anitacaron** [oborel/obo-relations#785]
Discussion with @cmungall @anitacaron @matentzn:
- add property chain `'has part' o 'has developmental contribution from' -> 'has developmental contribution from'` (edit existing which I think uses 'develops from')

_Originally posted by @balhoff in https://github.com/obophenotype/uberon/pull/3197#pullrequestreview-1863441756_

**Comment by ddooley** [comment]
@anitacaron closing this in favour of Damien's https://github.com/oborel/obo-relations/issues/814
