### ISSUE TITLE
[BUG] RO purls are broken

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [oborel/obo-relations#799]
When I checked today I noticed that the RO purls resolve to an error page at OLS4. An example for this is the following link: 
http://purl.obolibrary.org/obo/RO_0002533
This redirects me to this site: https://www.ebi.ac.uk/ols4/error
Could you check this strange redirecting?

**Comment by jamesamcl** [comment]
Yes you can swap “properties” in the URL for “terms”
