### ISSUE TITLE
Unclear meaning of `has potential to develop into`

### ISSUE THREAD

**Issue by gouttegd** [oborel/obo-relations#810]
[has potential to develop into](http://purl.obolibrary.org/obo/RO_0002387) (RO:0002387) is defined as

> _x_ has the potential to develop into _y_ iff _x_ develops into _y_ or if _x_ is capable of developing into _y_

I find it unclear what it means exactly to be “capable of developing into”.

In particular, if an anatomical entity _A1_ has potential to develop into another anatomical entity _A2_ and _A2_ only exists in taxon _T_, does that imply that _A1_ also can only exist in _T_?

My spontaneous understanding (and that of several other Uberon editors) is “no”, on the rationale that a “precursor” structure can exist in a broader range of species that (one of) the structure(s) it “has potential to develop into”.

However @cmungall [disagrees](https://github.com/obophenotype/uberon/pull/3336#issuecomment-2297136945):

> Think of it as being there is genetic programming to make A develop into B. It is stronger than “may”.

In which case, it is (still) unclear to me how that relation really differs from its subproperty [develops into](http://purl.obolibrary.org/obo/RO_0002203) – I assume it is “less strong” but how exactly?

So I’d like RO editors to please clarify the intended meaning of RO:0002387 (e.g. by amending its definition and/or adding an explanatory comment).

Also, note that Uberon is defining a property chain involving that property:

> [has potential to develop into](http://purl.obolibrary.org/obo/RO_0002387) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)

which is consistent with @cmungall’s interpretation but such a property chain, if it is indeed intended, should really be defined directly in RO rather than in Uberon: since both [has potential to develop into](http://purl.obolibrary.org/obo/RO_0002387) and [in taxon](http://purl.obolibrary.org/obo/RO_0002162) belong in RO, I believe any property chain involving both of them should itself belong in RO.

**Comment by dosumis** [comment]
Like capable_of  - this gets around strict quantification.  all X develops_into some Y vs all C has_potential_to_develop_into some Y.  

I think that this relation (and maybe an inverse?) will become increasingly important.   We have increasing evidence for trans-differentiation of differentiated cells in some tissues. There's quite a bit of recent work on this in the lung epithelium, where there is a population of basal stem cells with potential to develop into a variety of epithelial cells types but also some cell types may transform to other cell types depending on environmental conditions.  has_potential_to_develop_into could work well for these cases.

On the taxon thing - I'd go with the strict interpretation. For  "all X has_potential_to_develop_into some Y" to make sense, it must apply to all species. 

=> [has potential to develop into](http://purl.obolibrary.org/obo/RO_0002387) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)

I agree that this should be in RO, but there should be a smooth transition. 

My one worry is that it is being confident enough to make this assertion in a multi-species ontology given the limits of knowledge, but that' a general issue for multi-species anatomy and cell type ontologies.

**Comment by jhpoelen** [comment]
Was discussed in RO Meeting, Monday Sep 09, 2024 (8am PT, 11am ET, 5pm CET) see https://docs.google.com/document/d/19dhzj5QoliQZQgDJRczI878rLtexzMDo1g0K9_LRUWk/edit . 

This discussion appears to be caused by the lack of taxon context in the first part of the definition (re: A1). 

@nataled suggests to update the definition to make the taxonomic context clear (pending a review of already existing subrelations that may or may not cover this more specific definition).

**Comment by bpeters42** [comment]
@gouttegd - please let us know if you have what you need to proceed.

**Comment by gouttegd** [comment]
@bpeters42: It would make more sense to me if those who created that relation (and seem to have a clear idea of what it is intended to mean) took care of updating the definition, but fine, I’ll make do with what I have.

**Comment by bpeters42** [comment]
You are 100% correct. I was hoping that you would weigh in if the things discussed so far make sense to you, and ideally come up with a strawman revised definition? That will make it much more likely that this issue moves forward.

**Comment by gouttegd** [comment]
> I was hoping that you would weigh in if the things discussed so far make sense to you, and ideally come up with a strawman revised definition?

Will do. :)

Though the more I think about it, the more I believe the definition may not actually need to be amended _if_ the property chain 

```
'has potential to develop into' o 'in taxon' SubPropertyOf: 'in taxon'
```

is moved from Uberon to RO, because the very existence of that property chain answers formally the question that Uberon editors and myself were asking.

So what I’d suggest right now:

1. Leave the definition as it is.
2. Add to RO the property chain above (which currently only exists in Uberon, where it does not belong).
3. Possibly, add a comment based on @cmungall ’s explanation, just to avoid any misunderstanding and make it clear that the property chain is intentional and _not_ a mistake (something like: “this relation has a stronger meaning than merely indicating that _x_ MAY develop into _y_, in that the capability of developing into _y_ is always present, even if _x_ does not ALWAYS develop into _y_. In particular, this means that if _y_ is restricted to a given taxon, _x_ is necessarily likewise restricted.”)

Thoughts?
