### ISSUE TITLE
NTR: uncorrelated with

### ISSUE THREAD

**Issue by miseminger** [oborel/obo-relations#811]
For new term requests, please provide the following information:

## Preferred term label

uncorrelated with

## Synonyms

none

## Textual definition

A relationship that holds between two entities, where the entities do not exhibit a statistical dependence relationship. The entities may be statistical variables, or they may be other kinds of entities such as diseases, chemical entities or processes.

## Suggested parent term

none (should be sibling to ['correlated with' [RO_0002610]](http://purl.obolibrary.org/obo/RO_0002610))

## Attribution

[https://orcid.org/0000-0002-0548-891X](https://orcid.org/0000-0002-0548-891X), [https://orcid.org/0000-0002-8844-9165](https://orcid.org/0000-0002-8844-9165)

## Motivation

Our use case for "uncorrelated with" is to be able to write statements about mutations that are either positively correlated with or uncorrelated with some biological characteristic, as in the model shown below. For example, [Mishra et al. (2021)](https://doi.org/10.1101/2021.10.04.463028) report that the combination of E156_R158delinsG and D614G in SARS-CoV-2 are not correlated with host syncytia formation.

![evidence_model drawio](https://github.com/user-attachments/assets/5f47286e-fa83-4b86-b170-ff7648fea1f3)

**Comment by jhpoelen** [comment]
fyi @zedomel @seltmann as related to our desire to describe "not a relation" claim.

**Comment by bpeters42** [comment]
Discussed on 10/7 call; ventured all the way down the rabbitholes... This raises general questions about how to connect conclusions / study findings /propositions with the studies they come from, which can be contradictory. Damion will follow up to attempt to do that at the instance level. OBI should also clarify how this can be done in OBI in addition to how this is done in SEPIO here.

**Comment by ddooley** [comment]
Michelle Giglio has volunteered to talk about this topic in OBI Oct 21 curation call. She's presenting some past draft work on a solution.  

Basically, we were seeking a representational solution where a database of possibly conflicting papers could express their hypotheses and conclusions without leading to unsatisfiability.  Hence the SEPIO solution. As an aside, I see we could just add one more  property now to the SEPIO has_subject, has_predicate, has_object trio, namely, has_negation (true/false) to keep a meta vision, if that happens to be an attractive solution from a SEPIO view. It avoids adding negated versions of object properties.

James notes that a foundational ontology issue is about the longstanding absence of propositions in the BFO paradigm, though they are common in philosophy.

So from a BFO/OWL view, currently it is problematic to describe a paper's experimental hypothesis (OBI "testable hypothesis") as a triple directly at class or instance level: say there is a "testable hypothesis" of "X related to Y" in one paper, which concludes "X not related to Y" as a "conclusion based on data".  Dedicating a knowledge graph to just that one paper would lead to contradiction, let alone a knowledge graph of conflicting papers.

In RO call discussion Jim raised possibility of using a Negative Object Property Assertion to express the proposition or conclusion, however this only works at an instance level, not a universal level, and doesn't allow us to point to the proposition directly, but rather only indirectly by way of axioms on the subject X instance.

**Comment by ddooley** [comment]
Just a heads up that we will be testing something like this in Protege.  Of course I'm wondering how this might align with past OBI work on subject.  Not quite sure about relation between experimental evidence, measurement datum but will sort that and other things out with further consultation and OBI defns.
<img width="1079" alt="image" src="https://github.com/user-attachments/assets/006b14f7-797e-4c8c-9673-095853d2967a">

**Comment by ddooley** [comment]
So we have dropped our request for the "no correlation" relation, and as well are using SEPIO constructs rather than above attempt to attach relations indirectly to hypothesis and conclusion instances, something like:
<img width="834" alt="image" src="https://github.com/user-attachments/assets/4832c727-dc06-437d-820a-3d1e712aa2f3">

**Comment by jhpoelen** [comment]
@ddooley thanks for taking the time to share the approach you've settled on re: "uncorrelated to" statements.
