### ISSUE TITLE
Have DOI

### ISSUE THREAD

**Issue by tpoisot** [oborel/obo-relations#83]
I was wondering whether it would be worth having DOIs for the different releases of the ontology? It can be done automatically with http://zenodo.org/ from GitHub releases.

This would probably be a good way to identify the different versions, over time. I am willing to set up the system if you think this is useful.

**Comment by cmungall** [comment]
Thanks! I've done this for other ontologies but setting up permissions always seems a bit of a mystery.

I granted access to the org:

<img width="1028" alt="screen shot 2015-10-18 at 4 30 57 pm" src="https://cloud.githubusercontent.com/assets/50745/10567329/cd80bf80-75b5-11e5-884f-203ef72ab8c2.png">

However, it doesn't show up here https://zenodo.org/account/settings/github/ -- even though I am an owner of oborel

<img width="903" alt="screen shot 2015-10-18 at 4 32 57 pm" src="https://cloud.githubusercontent.com/assets/50745/10567332/f0a7e844-75b5-11e5-996f-29c9d49f487b.png">

Note that releases already have PURLs. For RO these are integrated into the GH release mechanism. For example https://github.com/oborel/obo-relations/releases/tag/v2015-10-07 artefacts have the prefix http://purl.obolibrary.org/obo/ro/releases/2015-10-07 e.g. http://purl.obolibrary.org/obo/ro/releases/2015-10-07/subsets/ro-interaction.owl

Although it could be confusing having two ways to reference the release, I think there is no harm in having a backup

**Comment by rlwalls2008** [comment]
I think it is redundant to have a DOI as well as a PURL, and intentionally creating two permanant IDs for the same object seems like maybe a bad (but totally realistic) practice. If ontologies do adopt DOIs for releasess, perhaps it would be a good policy to have the DOI point to the corresponding PURL.

**Comment by mellybelly** [comment]
I agree seems unnecessary and confusing? Unless we don't believe in PURL anymore? Why is DOI more persistent than PURL? What does adding the DOI gain us? Perhaps I am not in the know, though.

**Comment by cmungall** [comment]
I'm neutral. Seems to do not much harm to have both. Regardless of the sociological magic conferred by the prefixes "doi" or "purl", Zenodo is an extra free backup of contents. This is not to be sniffed at, given there is no dedicated money for centralized OBO infrastructure. If it wasn't for a lot of catherding, we'd have essentially lost versioned purl contents once gcode and sourceforge go away.

Note that if done correctly, the doi will resolve to a valid owl/zip file whose ontology IRI is the official purl, and has the correct versionIRI. This is not quite the same as the DOI pointing at the purl, but I think kind of neat nonetheless.

**Comment by tpoisot** [comment]
Can be cited easily, and a good mechanism to track credit. I think both can coexist, but a doi is important. 


Sent from a mobile device - pardon the brevity/typos.

-------- Message d'origine --------
De : Melissa Haendel <notifications@github.com> 
Date : 2015-10-19  10:19 PM  (GMT-05:00) 
À : oborel/obo-relations <obo-relations@noreply.github.com> 
Cc : Timothée Poisot <tim@poisotlab.io> 
Objet : Re: [obo-relations] Have DOI (#83) 

I agree seems unnecessary and confusing? Unless we don't believe in PURL anymore? Why is DOI more persistent than PURL? What does adding the DOI gain us? Perhaps I am not in the know, though.

**Comment by tpoisot** [comment]
Just to be clear: doi great for citation purposes. 


Sent from a mobile device - pardon the brevity/typos.

-------- Message d'origine --------
De : Melissa Haendel <notifications@github.com> 
Date : 2015-10-19  10:19 PM  (GMT-05:00) 
À : oborel/obo-relations <obo-relations@noreply.github.com> 
Cc : Timothée Poisot <tim@poisotlab.io> 
Objet : Re: [obo-relations] Have DOI (#83) 

I agree seems unnecessary and confusing? Unless we don't believe in PURL anymore? Why is DOI more persistent than PURL? What does adding the DOI gain us? Perhaps I am not in the know, though.

**Comment by mellybelly** [comment]
Thanks to both, agree extra back up is a good idea. That said, ontologies are notoriously difficult to attribute, not sure that a DOI will help with that. @tpoisot if you have ideas I will make another ticket, trying hard right now to figure out simply "who is using my ontology" - turns out that is rather hard. I think the ontology community needs to figure this out much better.

**Comment by tpoisot** [comment]
@mellybelly Maybe you should go ahead and create this other ticket. I think DOI may help since people see DOI on articles, so they recognize the name (as opposed to PURL). In a sense, PURL can talk to machines, and DOI to people. It make sense for an ontology to talk to both.

**Comment by cmungall** [comment]
Comments welcome on the linked OBO ticket. Currently the zenodo button is 'on' for RO, but a DOI won't be minted til next release.
