### ISSUE TITLE
PURL failing for 2015-04-12/core.owl

### ISSUE THREAD

**Issue by jamesaoverton** [oborel/obo-relations#84]
OBI uses this PURL for an RO release from earlier this year: <http://purl.obolibrary.org/obo/ro/releases/2015-04-12/core.owl>

The PURL is now redirecting to <https://raw.githubusercontent.com/oborel/obo-relations/v2015-04-12/core.owl> which is not a valid OWL file.

**Comment by jamesaoverton** [comment]
This newer release works fine: <http://purl.obolibrary.org/obo/ro/releases/2015-10-07/core.owl>.

**Comment by jamesaoverton** [comment]
I've updated OBI to use 2015-10-07, so this issue is just a heads up.

**Comment by cmungall** [comment]
Fixed with version-specific OCLC entry
