### ISSUE TITLE
Add causation properties between genetic variants or environments and conditions (disease or phenotype)

### ISSUE THREAD

**Issue by mbrush** [oborel/obo-relations#91]
Current causation properties are all restricted to hold between materials and materials, materials and processes, or processes and processes.  G2P association modeling requires causation between genotypes, genetic variants, or environments and 'conditions' (diseases or phenotypes).  

with @cmungall and @mellybelly, we proposed the following:

causally related to (exists already)
---causes or contributes to condition (new property)
------causes condition (new property)
------contributes to condition (new property)
----------contributes to severity of condition (new property)
----------contributes to frequency of condition (new property)
------preventative for condition (new property)

correlated with (exists already)
----correlated with condition (new property)

**Comment by mbrush** [comment]
Locking ro-edit to add proposed relations in a fork - will submit as pull request when complete.

**Comment by cmungall** [comment]
Message received, edit away!

**Comment by mbrush** [comment]
Proposed changes implemented in ro-edit.
