### ISSUE TITLE
Add relations for process boundaries

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#93]
In the RO temporal text definitions we have `α(x)` and `ω(x)` denoting start and end points. 

Note we can unroll expressions like `α(x) <= ω(y)` to property chains like `starts-at o before-or-equal o inv(ends-at)`, to derive property chain axioms that can be partially expressed in OWL.

See: http://biorxiv.org/content/early/2014/06/27/006650

Rough draft (incomplete)

```
ends-at-point o inv(starts-at-point) -> immediately-precedes
ends-at-point o precedes o inv(starts-at-point) -> precedes
```

Requested for https://github.com/obophenotype/uberon/issues/1172

**Comment by Public-Health-Bioinformatics** [comment]
Hi,
Has more work been done on this?  I wanted to follow up, esp. with regard to how >= and <= translate to english.  For GenEpiO I was looking for temporal boundary relations, so threw in:

    necessarily_follows
    necessarily_is_or_follows
    necessarily_is_or_precedes
    necessarily_precedes

as relations.  Seems like this is what you are talking about above? (I'd say that these relations aren't restricted to temporal dimension; they can map events, objects etc. to ordinal positions ore number line too). I was trying to anticipate how to describe a life cycle, briefly,

    date of conception
    date of birth
    date of death

    date of birth necessarily follows date of conception
    date of death necessarily is or follows date of birth (to allow for stillbirth etc.)

One tricky thing is that the granularity of measurement or display entails that at one scale (days say) events look like singular points in time, whereas at other scales (minutes say) events have duration.  Thus the need to use a >= "is or follows" relation vs. a "follows" or > relation.  Stillbirth must always be proceeded by birth; but the datum date-time of the two might appear as one.  A reasoner would likely have trouble over the data granularity proviso!

**Comment by cmungall** [comment]
The relations you need are likely in RO already:

 * [RO:0002222](http://purl.obolibrary.org/obo/RO_0002222) ! temporally related to
    * [BFO:0000063](http://purl.obolibrary.org/obo/BFO_0000063) ! precedes  
       * [RO:0002090](http://purl.obolibrary.org/obo/RO_0002090) ! immediately precedes  
    * [RO:0002086](http://purl.obolibrary.org/obo/RO_0002086) ! ends after
       * [BFO:0000062](http://purl.obolibrary.org/obo/BFO_0000062) ! preceded by  
          * [RO:0002087](http://purl.obolibrary.org/obo/RO_0002087) ! immediately preceded by  

The modal qualifier 'necessarily' is not clear - it may be built into OWL depending on what sense you mean.

Definition of `α(x)` and `ω(x)` are required for formal completeness (to see where I'm going with this, see the sequence analog here - http://biorxiv.org/content/early/2014/06/27/006650), but for most purposes existing relations should be fine.

Relations that link an occurrent to some kind of timepoint is a bit more difficult and depends on the use case - e.g. do you want to use xsd dates?

More on this later. In the interim you may be interested in the temporal modeling in https://github.com/obophenotype/developmental-stage-ontologies -- this ticket may be of interest: https://github.com/obophenotype/developmental-stage-ontologies/issues/19

**Comment by Public-Health-Bioinformatics** [comment]
Yes I was going to use xsd dates for conception/birth/death.  And indeed "necessarily" isn't actually adding anything ('twas a floppy attempt to constrain states of a system, not just their order). So with RO:

    "date of death" preceded by "date of birth" OR "date of death" is "date of birth" 
  
Which is the substance of a "is or precedes" relation.
 
Thanks for your details there, I will examine closely in the next week.

**Comment by nlharris** [comment]
What is the status of this?

**Comment by nlharris** [comment]
Can this be closed?

**Comment by nlharris** [comment]
Closing; reopen if needed.
