### ISSUE TITLE
Malformed PURL: http://purl.obolibrary.org/obo/RO_HOM0000001

### ISSUE THREAD

**Issue by alanruttenberg** [oborel/obo-relations#94]
Is the ontology supposed to be RO? According to ID policy, the digit part (with only PRO as exception) is preceded by an "_".

Perhaps the ontology is RO_HOM? In that case the purl should be

http://purl.obolibrary.org/obo/RO_HOM_0000001

**Comment by alanruttenberg** [comment]
Also note that this PURL does not resolve

**Comment by cmungall** [comment]
I think what needs to be done is to configure the purl redirects to be 
less restrictive for RO. The CURIEs are RO:HOMnnnnn and are synchronized 
with HOM classes

**Comment by alanruttenberg** [comment]
It's not a matter of ontobee. It's a matter of spec. If these are in HOM then we shouldn't have a second identifier for them.

**Comment by cmungall** [comment]
classes are in HOM. Relations in RO.

**Comment by alanruttenberg** [comment]
Then give the proper RO identifiers. But they don't have to be in RO. If their definitions are managed by the HOM ontology then simply import the HOM ids into RO. 

With MIREOT there's no reason to have all relations in the RO namespace. Moreover RO is so large that it only makes sense to MIREOT a fraction of terms that are needed. That fraction can just as easily be MIREOTed from HOM.

**Comment by alanruttenberg** [comment]
I've had a look at HOM. It seems clear to me that the relation should be defined in HOM and, if desired for convenience, MIREOTed into RO. It is the way ;-)

**Comment by nlharris** [comment]
What is the status of this?

**Comment by nlharris** [comment]
This is a very old ticket; I'm assuming it's been fixed or is no longer relevant. Reopen if needed.

**Comment by cmungall** [comment]
actually the PURLs don't resolve so we need to fix this. These are already in use so I think the action is to curate an exception in the OBO purl config
