### ISSUE TITLE
transformation_of is more specific than its label suggests

### ISSUE THREAD

**Issue by cmungall** [oborel/obo-relations#97]
Currently `transformation-of -> develops_from`.

develops_from is intended for developmental biology use cases (@dosumis suggests committing specifically to cell-based definitions)

There is a use case for a more generic TF, see
https://github.com/EnvironmentOntology/envo/issues/274

We should create a more generic TF for these use cases; in which case we should relabel
[RO:0002494](http://purl.obolibrary.org/obo/RO_0002494) 

to 'developmental transforms'

**Comment by wdduncan** [comment]
This issue is being closed because it has not had any activity in the last 2 years. If you think it is still worth pursuing, please reopen the issue and comment on its status.
